#
# Makefile.fpc for Free Pascal testing utilities
#

[package]
name=testsuite
version=3.3.1

[require]
packages=fcl-base fcl-db fcl-web rtl-objpas pthreads fcl-net rtl-extra postgres fcl-image paszlib hash
libc=y

[compiler]
unitdir=..

[target]
programs=testsuite

[default]
fpcdir=../../..

[rules]
testsuite$(SRCEXEEXT): testsuite.pp  tsconsts.pas  tsgraph.pas  tshistory.pas  tshtml.pas  tssql.pas
	$(COMPILER) $<
