#
# Makefile.fpc for Free Pascal testing utilities
#

[package]
name=testsuite
version=1.9.9

[require]
packages=fcl-base fcl-db
libc=y

[compiler]
unitdir=..

[target]
programs=testsuite

[default]
fpcdir=../../..
