#
#   Makefile.fpc for pas2fpm
#

[package]
name=pas2fpm
version=2.7.1

[require]
packages=fcl-passrc

[target]
programs=pas2ut
rst=pas2ut

[compiler]
options=-S2h

[install]
fpcpackage=y

[default]
fpcdir=../..

[rules]
.NOTPARALLEL:
pas2ut$(EXEEXT): pas2fpm.pp

