{
    This file is part of the Free Component Library (FCL)
    Copyright (c) 2026 by Michael Van Canneyt

    Consolidates packages/*/namespaces.lst into the fpsonar namespace table

    See the file COPYING.FPC, included in this distribution,
    for details about the copyright.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 **********************************************************************}
program mknamespacemap;

{$mode objfpc}{$H+}

uses
{$IFDEF FPC_DOTTEDUNITS}
  System.SysUtils, System.Classes;
{$ELSE}
  SysUtils, Classes;
{$ENDIF}

type
  TNamespaceEntry = record
    Key, Value: string;
  end;

  TNamespaceEntryArray = array of TNamespaceEntry;

const
  cDefaultOutDir = 'packages' + DirectorySeparator + 'fcl-sonar';
  cMapName = 'fpsonar-namespaces.map';
  cUnitName = 'fpsonar.namespacemap.pp';
  cListName = 'namespaces.lst';
  cMapHeader = '# generated by mknamespacemap from packages/*/namespaces.lst';

  cUnitProlog: array[0..26] of string = (
    '{',
    '    This file is part of the Free Component Library (FCL)',
    '    Copyright (c) 2026 by Michael Van Canneyt',
    '',
    '    Non-dotted to dotted unit-name table',
    '',
    '    See the file COPYING.FPC, included in this distribution,',
    '    for details about the copyright.',
    '',
    '    This program is distributed in the hope that it will be useful,',
    '    but WITHOUT ANY WARRANTY; without even the implied warranty of',
    '    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.',
    '',
    ' **********************************************************************}',
    'unit FpSonar.NamespaceMap;',
    '',
    '{ Generated by mknamespacemap from packages/*/namespaces.lst.',
    '  Do not edit by hand; regenerate instead. }',
    '',
    '{$mode objfpc}{$H+}',
    '',
    'interface',
    '',
    'type',
    '  // One non-dotted/dotted unit-name pair.',
    '  TNamespacePair = record',
    '    Plain, Dotted: string;'
    );

  cUnitMiddle: array[0..3] of string = (
    '  end;',
    '',
    '  TNamespacePairArray = array of TNamespacePair;',
    ''
    );

  cUnitEpilog: array[0..206] of string = (
    '',
    '// True iff aPlain has an entry in the active table; aDotted receives its',
    '// dotted name.',
    'function LookupNamespace(const aPlain: string; out aDotted: string): boolean;',
    '// Replaces the active table with the key=value pairs read from aPath.',
    'function LoadNamespaceMap(const aPath: string; out aError: string): boolean;',
    '// Discards a loaded table, making the baked-in one active again.',
    'procedure ResetNamespaceMap;',
    '',
    'implementation',
    '',
    'uses',
    '{$IFDEF FPC_DOTTEDUNITS}',
    '  System.SysUtils, System.Classes;',
    '{$ELSE}',
    '  SysUtils, Classes;',
    '{$ENDIF}',
    '',
    'var',
    '  GLoaded: boolean;',
    '  GLoadedMap: TNamespacePairArray;',
    '',
    '// Byte order on Plain, then Dotted.',
    'function ComparePairs(const aLeft, aRight: TNamespacePair): integer;',
    '',
    'begin',
    '  Result := CompareStr(aLeft.Plain, aRight.Plain);',
    '  if Result = 0 then',
    '    Result := CompareStr(aLeft.Dotted, aRight.Dotted);',
    'end;',
    '',
    '',
    '// In-place quicksort of aPairs[aLo..aHi] by ComparePairs.',
    'procedure SortPairs(var aPairs: TNamespacePairArray; aLo, aHi: integer);',
    '',
    'var',
    '  i, j: integer;',
    '  lPivot, lTmp: TNamespacePair;',
    '',
    'begin',
    '  if aLo >= aHi then',
    '    Exit;',
    '  i := aLo;',
    '  j := aHi;',
    '  lPivot := aPairs[(aLo + aHi) div 2];',
    '  repeat',
    '    while ComparePairs(aPairs[i], lPivot) < 0 do',
    '      Inc(i);',
    '    while ComparePairs(aPairs[j], lPivot) > 0 do',
    '      Dec(j);',
    '    if i <= j then',
    '      begin',
    '      lTmp := aPairs[i];',
    '      aPairs[i] := aPairs[j];',
    '      aPairs[j] := lTmp;',
    '      Inc(i);',
    '      Dec(j);',
    '      end;',
    '  until i > j;',
    '  SortPairs(aPairs, aLo, j);',
    '  SortPairs(aPairs, i, aHi);',
    'end;',
    '',
    '',
    'function ActiveCount: integer;',
    '',
    'begin',
    '  if GLoaded then',
    '    Result := Length(GLoadedMap)',
    '  else',
    '    Result := Length(cNamespaceMap);',
    'end;',
    '',
    '',
    'function ActivePair(aIndex: integer): TNamespacePair;',
    '',
    'begin',
    '  if GLoaded then',
    '    Result := GLoadedMap[aIndex]',
    '  else',
    '    Result := cNamespaceMap[aIndex];',
    'end;',
    '',
    '',
    'function LookupNamespace(const aPlain: string; out aDotted: string): boolean;',
    '',
    'var',
    '  lKey: string;',
    '  lLo, lHi, lMid, lCmp: integer;',
    '',
    'begin',
    '  Result := False;',
    '  aDotted := '''';',
    '  lKey := LowerCase(aPlain);',
    '  lLo := 0;',
    '  lHi := ActiveCount - 1;',
    '  while lLo <= lHi do',
    '    begin',
    '    lMid := (lLo + lHi) div 2;',
    '    lCmp := CompareStr(ActivePair(lMid).Plain, lKey);',
    '    if lCmp = 0 then',
    '      begin',
    '      aDotted := ActivePair(lMid).Dotted;',
    '      Result := True;',
    '      Exit;',
    '      end',
    '    else if lCmp < 0 then',
    '      lLo := lMid + 1',
    '    else',
    '      lHi := lMid - 1;',
    '    end;',
    'end;',
    '',
    '',
    'function LoadNamespaceMap(const aPath: string; out aError: string): boolean;',
    '',
    'var',
    '  lLines: TStringList;',
    '  lPairs: TNamespacePairArray;',
    '  lLine, lKey, lValue: string;',
    '  i, j, lCount, lKept, lSep: integer;',
    '',
    'begin',
    '  Result := False;',
    '  aError := '''';',
    '  if not FileExists(aPath) then',
    '    begin',
    '    aError := Format(''namespace map %s not found'', [aPath]);',
    '    Exit;',
    '    end;',
    '  lLines := TStringList.Create;',
    '  try',
    '    try',
    '      lLines.LoadFromFile(aPath);',
    '    except',
    '      on E: Exception do',
    '        begin',
    '        aError := Format(''cannot read namespace map %s: %s'', [aPath, E.Message]);',
    '        Exit;',
    '        end;',
    '    end;',
    '    SetLength(lPairs, lLines.Count);',
    '    lCount := 0;',
    '    for i := 0 to lLines.Count - 1 do',
    '      begin',
    '      lLine := Trim(lLines[i]);',
    '      if (lLine = '''') or (lLine[1] = ''#'') then',
    '        Continue;',
    '      lKey := '''';',
    '      lValue := '''';',
    '      lSep := Pos(''='', lLine);',
    '      if lSep > 0 then',
    '        begin',
    '        lKey := LowerCase(Trim(Copy(lLine, 1, lSep - 1)));',
    '        lValue := Trim(Copy(lLine, lSep + 1, Length(lLine) - lSep));',
    '        end;',
    '      if (lKey = '''') or (lValue = '''') then',
    '        begin',
    '        aError := Format(''namespace map %s line %d: expected key=value'',',
    '          [aPath, i + 1]);',
    '        Exit;',
    '        end;',
    '      lPairs[lCount].Plain := lKey;',
    '      lPairs[lCount].Dotted := lValue;',
    '      Inc(lCount);',
    '      end;',
    '    if lCount = 0 then',
    '      begin',
    '      aError := Format(''namespace map %s holds no entries'', [aPath]);',
    '      Exit;',
    '      end;',
    '    SetLength(lPairs, lCount);',
    '    SortPairs(lPairs, 0, High(lPairs));',
    '    // Identical duplicates collapse; a key with two distinct values is dropped.',
    '    lKept := 0;',
    '    i := 0;',
    '    while i <= High(lPairs) do',
    '      begin',
    '      j := i;',
    '      while (j < High(lPairs)) and (lPairs[j + 1].Plain = lPairs[i].Plain) do',
    '        Inc(j);',
    '      if lPairs[i].Dotted = lPairs[j].Dotted then',
    '        begin',
    '        lPairs[lKept] := lPairs[i];',
    '        Inc(lKept);',
    '        end;',
    '      i := j + 1;',
    '      end;',
    '    SetLength(lPairs, lKept);',
    '    GLoadedMap := lPairs;',
    '    GLoaded := True;',
    '    Result := True;',
    '  finally',
    '    lLines.Free;',
    '  end;',
    'end;',
    '',
    '',
    'procedure ResetNamespaceMap;',
    '',
    'begin',
    '  SetLength(GLoadedMap, 0);',
    '  GLoaded := False;',
    'end;',
    '',
    '',
    'end.'
    );

// Byte order on Key, then Value.
function CompareEntries(const aLeft, aRight: TNamespaceEntry): integer;

begin
  Result := CompareStr(aLeft.Key, aRight.Key);
  if Result = 0 then
    Result := CompareStr(aLeft.Value, aRight.Value);
end;


// In-place quicksort of aEntries[aLo..aHi] by CompareEntries.
procedure SortEntries(var aEntries: TNamespaceEntryArray; aLo, aHi: integer);

var
  i, j: integer;
  lPivot, lTmp: TNamespaceEntry;

begin
  if aLo >= aHi then
    Exit;
  i := aLo;
  j := aHi;
  lPivot := aEntries[(aLo + aHi) div 2];
  repeat
    while CompareEntries(aEntries[i], lPivot) < 0 do
      Inc(i);
    while CompareEntries(aEntries[j], lPivot) > 0 do
      Dec(j);
    if i <= j then
      begin
      lTmp := aEntries[i];
      aEntries[i] := aEntries[j];
      aEntries[j] := lTmp;
      Inc(i);
      Dec(j);
      end;
  until i > j;
  SortEntries(aEntries, aLo, j);
  SortEntries(aEntries, i, aHi);
end;


function CompareNames(aList: TStringList; aLeft, aRight: integer): integer;

begin
  Result := CompareStr(aList[aLeft], aList[aRight]);
end;


// Every packages/<dir>/namespaces.lst under the current directory, sorted.
function CollectListFiles: TStringList;

var
  lInfo: TSearchRec;
  lBase, lPath: string;

begin
  Result := TStringList.Create;
  lBase := 'packages' + DirectorySeparator;
  if FindFirst(lBase + '*', faDirectory, lInfo) = 0 then
    try
      repeat
        if (lInfo.Name = '.') or (lInfo.Name = '..') then
          Continue;
        if (lInfo.Attr and faDirectory) = 0 then
          Continue;
        lPath := lBase + lInfo.Name + DirectorySeparator + cListName;
        if FileExists(lPath) then
          Result.Add(lPath);
      until FindNext(lInfo) <> 0;
    finally
      FindClose(lInfo);
    end;
  Result.CustomSort(@CompareNames);
end;


// Appends the src/...=namespaced/... mappings of aPath to aEntries.
procedure ReadListFile(const aPath: string; var aEntries: TNamespaceEntryArray);

var
  lLines: TStringList;
  lLine, lLeft, lRight: string;
  i, lCount, lSep: integer;

begin
  lLines := TStringList.Create;
  try
    lLines.LoadFromFile(aPath);
    lCount := Length(aEntries);
    SetLength(aEntries, lCount + lLines.Count);
    for i := 0 to lLines.Count - 1 do
      begin
      lLine := Trim(lLines[i]);
      if Copy(lLine, 1, 4) <> 'src/' then
        Continue;
      lSep := Pos('=namespaced/', lLine);
      if lSep = 0 then
        Continue;
      lLeft := Copy(lLine, 1, lSep - 1);
      lRight := Copy(lLine, lSep + 1, Length(lLine) - lSep);
      aEntries[lCount].Key := LowerCase(ChangeFileExt(ExtractFileName(lLeft), ''));
      aEntries[lCount].Value := ChangeFileExt(ExtractFileName(lRight), '');
      Inc(lCount);
      end;
    SetLength(aEntries, lCount);
  finally
    lLines.Free;
  end;
end;


// Sorts aEntries, collapses identical duplicates and removes every key mapped
// to more than one value. Returns the number of keys removed.
function Consolidate(var aEntries: TNamespaceEntryArray): integer;

var
  i, j, lKept: integer;

begin
  Result := 0;
  SortEntries(aEntries, 0, High(aEntries));
  lKept := 0;
  i := 0;
  while i <= High(aEntries) do
    begin
    j := i;
    while (j < High(aEntries)) and (aEntries[j + 1].Key = aEntries[i].Key) do
      Inc(j);
    if aEntries[i].Value <> aEntries[j].Value then
      Inc(Result)
    else
      begin
      aEntries[lKept] := aEntries[i];
      Inc(lKept);
      end;
    i := j + 1;
    end;
  SetLength(aEntries, lKept);
end;


function RenderMap(const aEntries: TNamespaceEntryArray): TStringList;

var
  i: integer;

begin
  Result := TStringList.Create;
  Result.Add(cMapHeader);
  for i := 0 to High(aEntries) do
    Result.Add(aEntries[i].Key + '=' + aEntries[i].Value);
end;


function RenderUnit(const aEntries: TNamespaceEntryArray): TStringList;

var
  i: integer;
  lLine: string;

begin
  Result := TStringList.Create;
  for i := Low(cUnitProlog) to High(cUnitProlog) do
    Result.Add(cUnitProlog[i]);
  for i := Low(cUnitMiddle) to High(cUnitMiddle) do
    Result.Add(cUnitMiddle[i]);
  Result.Add('const');
  Result.Add(Format('  cNamespaceMap: array[0..%d] of TNamespacePair = (',
    [High(aEntries)]));
  for i := 0 to High(aEntries) do
    begin
    lLine := Format('    (Plain: ''%s''; Dotted: ''%s'')',
      [aEntries[i].Key, aEntries[i].Value]);
    if i < High(aEntries) then
      lLine := lLine + ',';
    Result.Add(lLine);
    end;
  Result.Add('    );');
  for i := Low(cUnitEpilog) to High(cUnitEpilog) do
    Result.Add(cUnitEpilog[i]);
end;


// Writes aLines to aPath, each terminated by #10 whatever the host convention.
procedure WriteLines(const aPath: string; aLines: TStringList);

var
  lStream: TFileStream;
  lText: string;
  i: integer;

begin
  lStream := TFileStream.Create(aPath, fmCreate);
  try
    for i := 0 to aLines.Count - 1 do
      begin
      lText := aLines[i] + #10;
      lStream.WriteBuffer(lText[1], Length(lText));
      end;
  finally
    lStream.Free;
  end;
end;


procedure Run;

var
  lFiles, lMap, lUnit: TStringList;
  lEntries: TNamespaceEntryArray;
  lOutDir, lUnitDir: string;
  lDropped, i: integer;

begin
  lOutDir := cDefaultOutDir;
  if ParamCount >= 1 then
    lOutDir := ParamStr(1);
  lOutDir := ExcludeTrailingPathDelimiter(lOutDir);
  lUnitDir := lOutDir + DirectorySeparator + 'src' + DirectorySeparator + 'base';

  lFiles := CollectListFiles;
  try
    if lFiles.Count = 0 then
      begin
      Writeln(StdErr, 'mknamespacemap: no packages/*/' + cListName +
        ' found under ' + GetCurrentDir);
      ExitCode := 1;
      Exit;
      end;
    SetLength(lEntries, 0);
    i := 0;
    while i < lFiles.Count do
      begin
      try
        ReadListFile(lFiles[i], lEntries);
      except
        on E: Exception do
          begin
          Writeln(StdErr, 'mknamespacemap: cannot read ' + lFiles[i] + ': ' +
            E.Message);
          ExitCode := 1;
          Exit;
          end;
      end;
      Inc(i);
      end;
    lDropped := Consolidate(lEntries);
    if Length(lEntries) = 0 then
      begin
      Writeln(StdErr, 'mknamespacemap: no mappings in packages/*/' + cListName +
        ' under ' + GetCurrentDir);
      ExitCode := 1;
      Exit;
      end;

    if not ForceDirectories(lUnitDir) then
      begin
      Writeln(StdErr, 'mknamespacemap: cannot create ' + lUnitDir);
      ExitCode := 1;
      Exit;
      end;
    lMap := RenderMap(lEntries);
    lUnit := RenderUnit(lEntries);
    try
      try
        WriteLines(lOutDir + DirectorySeparator + cMapName, lMap);
        WriteLines(lUnitDir + DirectorySeparator + cUnitName, lUnit);
      except
        on E: Exception do
          begin
          Writeln(StdErr, 'mknamespacemap: cannot write output: ' + E.Message);
          ExitCode := 1;
          Exit;
          end;
      end;
    finally
      lMap.Free;
      lUnit.Free;
    end;
    Writeln(Format('mknamespacemap: %d files, %d pairs, %d ambiguous keys dropped',
      [lFiles.Count, Length(lEntries), lDropped]));
  finally
    lFiles.Free;
  end;
end;


begin
  Run;
end.
