{

   This file contains all includes needed by gtk.pp

   Note: The order of the files is important !!
}

{$i gtkfeatures.pp}
{$i gtkenums.pp}
{$i gtkobjects.pp}
{$i gtktypeutils.pp}
{$i gtkdata.pp}
{$i gtkadjustment.pp}
{$i gtkaccelgroup.pp}
{$i gtkwidget.pp}
{$i gtkstyle.pp}
{$i gtkmisc.pp}
{$i gtklabel.pp}
{$i gtkprivate.pp}
{$i gtkaccellabel.pp}
{$i gtkthemes.pp}
{$i gtkmain.pp}
{$i gtkdrawingarea.pp}
{$i gtkcontainer.pp}
{$i gtkbin.pp}
{$i gtksignal.pp}
{$i gtkitem.pp}
{$i gtkarg.pp}
{$i gtkmarshal.pp}
{$i gtkbindings.pp}
{$i gtkinvisible.pp}
{$i gtkalignment.pp}
{$i gtkwindow.pp}
{$i gtkplug.pp}
{$i gtksocket.pp}
{$i gtkpacker.pp}
{$i gtklayout.pp}
{$i gtkframe.pp}
{$i gtkaspectframe.pp}
{$i gtkviewport.pp}
{$i gtkrange.pp}
{$i gtkrc.pp}
{$i gtkeditable.pp}
{$i gtktext.pp}
{$i gtkarrow.pp}
{$i gtkpixmap.pp}
{$i gtkbutton.pp}
{$i gtktogglebutton.pp}
{$i gtkcheckbutton.pp}
{$i gtkmenuitem.pp}
{$i gtkcheckmenuitem.pp}
{$i gtktearoffmenuitem.pp}
{$i gtkcurve.pp}
{$i gtkdialog.pp}
{$i gtkentry.pp}
{$i gtkeventbox.pp}
{$i gtkfilesel.pp}
{$i gtkfixed.pp}
{$i gtkgc.pp}
{$i gtkhandlebox.pp}
{$i gtkimage.pp}
{$i gtkinputdialog.pp}
{$i gtklist.pp}
{$i gtklistitem.pp}
{$i gtkmenushell.pp}
{$i gtkmenufactory.pp}
{$i gtkmenu.pp}
{$i gtkmenubar.pp}
{$i gtkoptionmenu.pp}
{$i gtkpreview.pp}
{$i gtkitemfactory.pp}
{$i gtkprogress.pp}
{$i gtkprogressbar.pp}
{$i gtkradiobutton.pp}
{$i gtkradiomenuitem.pp}
{$i gtkscrolledwindow.pp}
{$i gtkselection.pp}
{$i gtkdnd.pp}
{$i gtkspinbutton.pp}
{$i gtktable.pp}
{$i gtktipsquery.pp}
{$i gtktooltips.pp}
{$i gtktoolbar.pp}
{$i gtktreeitem.pp}
{$i gtktree.pp}
{$i gtkbox.pp}
{$i gtkhbox.pp}
{$i gtkvbox.pp}
{$i gtkbbox.pp}
{$i gtkhbbox.pp}
{$i gtkvbbox.pp}
{$i gtkpaned.pp}
{$i gtkhpaned.pp}
{$i gtkvpaned.pp}
{$i gtkruler.pp}
{$i gtkhruler.pp}
{$i gtkvruler.pp}
{$i gtkscale.pp}
{$i gtkhscale.pp}
{$i gtkvscale.pp}
{$i gtkscrollbar.pp}
{$i gtkhscrollbar.pp}
{$i gtkvscrollbar.pp}
{$i gtkseparator.pp}
{$i gtkhseparator.pp}
{$i gtkvseparator.pp}
{$i gtkcombo.pp}
{$i gtkstatusbar.pp}
{$i gtkcolorsel.pp}
{$i gtkgamma.pp}
{$i gtkclist.pp}
{$i gtknotebook.pp}
{$i gtkctree.pp}
{$i gtkcalendar.pp}
{$i gtkfontsel.pp}

