#
#   Makefile.fpc for Free Pascal Runtime Library
#

[package]
name=rtl
version=1.0.5

[target]
dirs=linux win32 go32v2 go32v1 os2 freebsd

[install]
fpcpackage=y

[default]
fpcdir=..
dir=$(OS_TARGET)
