#
#   Makefile.fpc for Free Pascal Runtime Library
#

[package]
name=rtl
version=1.0.6

[target]
dirs_linux=linux
dirs_win32=win32
dirs_go32v2=go32v2
dirs_go32v1=go32v1
dirs_os2=os2
dirs_emx=emx
dirs_freebsd=freebsd
dirs_beos=beos
dirs_amiga=amiga

[install]
fpcpackage=y
createpackagefpc=y

[default]
fpcdir=..
