insert into users (uLogin,uFullName,uPassword) values ('Michael','Michaël Van Canneyt','secret');
insert into users (uLogin,uFullName,uPassword) values ('Mattias','Mattias Gaertner','secret');
insert into users (uLogin,uFullName,uPassword) values ('Detlef','Detlef overbeek','secret');
insert into projects (pName,pDescription) values ('Pas2JS','Pas2JS - Pascal to Javascript converter');
insert into projects (pName,pDescription) values ('FPC','FPC - Open source pascal compiler');
insert into projects (pName,pDescription) values ('Lazarus','Lazarus - Open source IDE for Pascal');
insert into projects (pName,pDescription) values ('JSONViewer','Lazarus JSON viewer tool');
insert into ExpenseTypes (etName,etDescription) values ('Transport','Travel by bus/train/airplane');
insert into ExpenseTypes (etName,etDescription) values ('Car','Travel by car');
insert into ExpenseTypes (etName,etDescription) values ('Food','expenses in Bar, Restaurant');
