#
#   Makefile.fpc for TDataSet for FCL
#

[package]
main=fcl

[target]
dirs=sdf memds sqldb unmaintained
# dirs_i386=dbase
dirs_linux=dbase sqlite
dirs_freebsd=dbase sqlite
dirs_darwin=sqlite
dirs_netbsd=sqlite
dirs_openbsd=sqlite
dirs_win32=dbase sqlite
dirs_wince=dbase sqlite
units=dbconst db dbwhtml
rsts=dbwhtml dbconst

[compiler]
options=-S2

[install]
fpcpackage=y

[default]
fpcdir=../..

