#
#   Makefile.fpc for Free Pascal Message Compiler
#

[target]
programs=fpmc
programs_linux=fpmcgtk
programs_win32=fpmcgtk
rsts=frmabout frmmain frmoptions msgcomp

[clean]
units=frmmain msgcomp frmabout frmoptions

[require]
packages=fcl fpgtk

[compiler]

[install]
fpcpackage=y

[default]
fpcdir=../..

[rules]
fpmc$(EXEEXT): msgcomp.pp fpmc.pp

fpmcgtk$(EXEEXT): msgcomp.pp fpmcgtk.pp $(wildcard frm*.pp)
