{ Google Calendar demo: list calendars and the upcoming events of a calendar,
  using the Calendar API units generated by discovery2pas and OAuth2
  (loopback redirect) for authorization. }
program calendardemo;

{$mode objfpc}{$H+}

uses
  Classes, SysUtils, DateUtils, CustApp, fpjson, jsonparser, fphttpwebclient, opensslsockets,
  fpoauth2, fpoauth2ini, fpopenapiclient, googleapi.client,
  calendar.Dto, calendar.Serializer, calendar.Service.Intf, calendar.Service.Impl,
  GoogleAPI.OAuthRedirect;

const
  CalendarBaseURL = 'https://www.googleapis.com/calendar/v3';
  CalendarScope = 'https://www.googleapis.com/auth/calendar';
  DefaultPort = 8085;
  DefaultEventCount = 25;

type
  ECalendarDemo = class(Exception);

  { TGoogleCalendarApplication }

  TGoogleCalendarApplication = class(TCustomApplication)
  private
    FConfig: String;
    FCredentials: String;
    FSession: String;
    FLogFile: String;
    FPort: Word;
    FManual: Boolean;
    FClient: TGoogleAPIClient;
    FCalendarList: TCalendarListProxy;
    FEvents: TEventsProxy;
    procedure DoUserConsent(const aURL: String; out aAuthCode: String);
    procedure EnsureService;
    procedure ListCalendars;
    procedure ListEvents(const aCalendarID: String; aCount: Integer);
  protected
    procedure DoRun; override;
  public
    constructor Create(aOwner: TComponent); override;
    // Show usage information, with aMsg as error message if not empty, and stop.
    procedure WriteHelp(const aMsg: String); virtual;
  end;

// Raise an exception if a service call did not succeed.
procedure CheckServiceResult(aSuccess: Boolean; aCode: Integer; const aText, aAction: String);

begin
  if not aSuccess then
    raise ECalendarDemo.CreateFmt('Failed to %s: HTTP %d %s',[aAction,aCode,aText]);
end;


// Return the start of an event as display text.
function EventStartText(aEvent: TEvent): String;

begin
  if not Assigned(aEvent.start) then
    Result:='(unspecified time)'
  else if aEvent.start.dateTime<>0 then
    Result:=DateTimeToStr(aEvent.start.dateTime)
  else if aEvent.start.date<>0 then
    Result:=DateToStr(aEvent.start.date)
  else
    Result:='(unspecified time)';
end;


{ TGoogleCalendarApplication }

constructor TGoogleCalendarApplication.Create(aOwner: TComponent);

begin
  inherited Create(aOwner);
  StopOnException:=True;
end;


procedure TGoogleCalendarApplication.DoUserConsent(const aURL: String; out aAuthCode: String);

var
  lURL, lInput: String;
  lListener: TOAuthRedirectListener;

begin
  // Request a refresh token so the next runs need no consent
  lURL:=aURL+'&access_type=offline&prompt=consent';
  Writeln;
  Writeln('User consent required. Open the following URL in a browser:');
  Writeln;
  Writeln(lURL);
  Writeln;
  if FManual then
    begin
    Writeln('After granting access, the browser is sent to ',FClient.RedirectUri);
    Writeln('and shows a connection error. Copy the full address from the');
    Writeln('browser address bar (or only the code parameter) and paste it here.');
    Writeln;
    Write('URL or code: ');
    ReadLn(lInput);
    aAuthCode:=ExtractAuthCode(lInput);
    end
  else
    begin
    lListener:=TOAuthRedirectListener.Create(FPort);
    try
      Writeln('Waiting for the browser to return to ',lListener.RedirectURI,' ...');
      aAuthCode:=lListener.WaitForCode;
    finally
      lListener.Free;
    end;
    end;
  if aAuthCode='' then
    raise ECalendarDemo.Create('No authorization code received');
  Writeln('End user consent, returning to Google API...');
  Writeln;
end;


procedure TGoogleCalendarApplication.EnsureService;

var
  lStore: TFPOAuth2IniStore;

begin
  FClient:=TGoogleAPIClient.Create(Self);
  FClient.WebClient:=TFPHTTPWebClient.Create(Self);
  if FLogFile<>'' then
    FClient.WebClient.LogFile:=FLogFile;
  lStore:=TFPOAuth2IniStore.Create(Self);
  lStore.ConfigFileName:=FConfig;
  lStore.SessionFileName:=FConfig;
  FClient.AuthHandler.Store:=lStore;
  FClient.AuthHandler.LoadConfig;
  if FCredentials<>'' then
    begin
    FClient.RedirectUri:='';
    FClient.LoadCredentials(FCredentials);
    end;
  if not FClient.HasCredentials then
    raise ECalendarDemo.CreateFmt('No OAuth2 client ID/secret found in %s. Use -j to import the client JSON file.',[FConfig]);
  FClient.Scopes:=CalendarScope;
  FClient.RedirectUri:=Format('http://127.0.0.1:%d',[FPort]);
  FClient.AuthHandler.Config.AccessType:=atOffline;
  if FCredentials<>'' then
    FClient.AuthHandler.SaveConfig;
  FClient.AuthHandler.LoadSession(FSession);
  FClient.OnUserConsent:=@DoUserConsent;
  FCalendarList:=TCalendarListProxy.Create(Self);
  FCalendarList.BaseURL:=CalendarBaseURL;
  FClient.ConfigureService(FCalendarList);
  FEvents:=TEventsProxy.Create(Self);
  FEvents.BaseURL:=CalendarBaseURL;
  FClient.ConfigureService(FEvents);
end;


procedure TGoogleCalendarApplication.ListCalendars;

var
  lResult: TCalendarListServiceResult;
  lEntry: TCalendarListEntry;
  lPageToken, lName: String;
  lCount: Integer;

begin
  lPageToken:='';
  lCount:=0;
  repeat
    lResult:=FCalendarList.List(250,'',lPageToken,False,False,False,'');
    CheckServiceResult(lResult.Success,lResult.ErrorCode,lResult.ErrorText,'list calendars');
    try
      for lEntry in lResult.Value.items do
        begin
        Inc(lCount);
        lName:=lEntry.summary;
        if lName='' then
          lName:=lEntry.description;
        Writeln(lCount,': ID: ',lEntry.id,' (',lName,')');
        end;
      lPageToken:=lResult.Value.nextPageToken;
    finally
      lResult.Value.Free;
    end;
  until lPageToken='';
end;


procedure TGoogleCalendarApplication.ListEvents(const aCalendarID: String; aCount: Integer);

var
  lResult: TEventsServiceResult;
  lEvent: TEvent;
  lTimeMin, lName: String;
  lCount: Integer;

begin
  lTimeMin:=FormatDateTime('yyyy"-"mm"-"dd"T"hh":"nn":"ss"Z"',LocalTimeToUniversal(Now));
  lResult:=FEvents.List(False,aCalendarID,'','',100,'startTime','','','','',False,False,True,'','',lTimeMin,'','',aCount);
  CheckServiceResult(lResult.Success,lResult.ErrorCode,lResult.ErrorText,'list events of '+aCalendarID);
  try
    lCount:=0;
    for lEvent in lResult.Value.items do
      begin
      Inc(lCount);
      lName:=lEvent.summary;
      if lName='' then
        lName:=lEvent.id+' ('+lEvent.description+')';
      Writeln(lCount,': ',EventStartText(lEvent),' : ',lName);
      end;
    if lCount=0 then
      Writeln('No upcoming events.');
  finally
    lResult.Value.Free;
  end;
end;


procedure TGoogleCalendarApplication.DoRun;

var
  lError: String;

begin
  lError:=CheckOptions('hle:n:c:j:s:o:p:m',
    ['help','list','entry:','count:','config:','credentials:','session:','logfile:','port:','manual']);
  if (lError<>'') or HasOption('h','help') then
    WriteHelp(lError);
  FConfig:=GetOptionValue('c','config');
  if FConfig='' then
    FConfig:=ExtractFilePath(ParamStr(0))+'google.ini';
  FCredentials:=GetOptionValue('j','credentials');
  FSession:=GetOptionValue('s','session');
  if FSession='' then
    FSession:='me';
  FLogFile:=GetOptionValue('o','logfile');
  FPort:=StrToIntDef(GetOptionValue('p','port'),DefaultPort);
  FManual:=HasOption('m','manual');
  EnsureService;
  try
    if HasOption('e','entry') then
      ListEvents(GetOptionValue('e','entry'),StrToIntDef(GetOptionValue('n','count'),DefaultEventCount))
    else
      ListCalendars;
  finally
    FClient.AuthHandler.SaveSession(FSession);
  end;
  Terminate;
end;


procedure TGoogleCalendarApplication.WriteHelp(const aMsg: String);

begin
  if aMsg<>'' then
    Writeln('Error : ',aMsg);
  Writeln('Usage: ',ExeName,' [options]');
  Writeln('Where options : ');
  Writeln('-h --help             This help.');
  Writeln('-l --list             List calendars (default action).');
  Writeln('-e --entry=calID      List upcoming events of the calendar with ID calID ("primary" for your own).');
  Writeln('-n --count=N          Maximum number of events to list (default ',DefaultEventCount,').');
  Writeln('-c --config=FILE      Config file with client data and tokens (default google.ini).');
  Writeln('-j --credentials=FILE Import OAuth client JSON from Google Cloud Console into the config file.');
  Writeln('-s --session=NAME     Session to load from the config file (default: me).');
  Writeln('-p --port=PORT        Local port for the OAuth2 redirect (default ',DefaultPort,').');
  Writeln('-m --manual           Paste the redirect URL instead of running a local listener.');
  Writeln('-o --logfile=FILE     Log HTTP requests and responses to FILE.');
  Halt(Ord(aMsg<>''));
end;


var
  Application: TGoogleCalendarApplication;

begin
  Application:=TGoogleCalendarApplication.Create(nil);
  Application.Title:='Google Calendar demo';
  Application.Run;
  Application.Free;
end.
