# $Id$
#
# Here we set processor dependent include file names.
#

CPUNAMES=x86_64
CPUINCNAMES=$(addsuffix .inc,$(CPUNAMES))
#
# $Log$
# Revision 1.1  2003-01-06 19:40:18  florian
#   + initial revision
#
#
