#
#   Makefile.fpc for FPC demo package
#

[targets]
dirs=text graph
dirs_go32v2=modex
dirs_win32=win32
dirs_linux=linux

[install]
packagename=demo
sourcesubdir=0

[defaults]
defaultrule=all

[dirs]
fpcdir=..
targetdir=.

[rules]
info:
        @echo Makefile targets are
        @echo - all
        @echo - text
        @echo - graph
        @echo - modex
        @echo - win32
