{
    This file is part of the Free Component Library (FCL)
    Copyright (c) 2026 by Michael Van Canneyt

    Tests for the non-dotted to dotted unit-name table

    See the file COPYING.FPC, included in this distribution,
    for details about the copyright.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 **********************************************************************}
unit utstNamespaceMap;


{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, fpcunit, testregistry,
  FpSonar.NamespaceMap, UtstFixtures;

type
  { Baked-in table, loader and regenerate-and-compare tests. }
  TNamespaceMapTest = class(TTestCase)
  private
    function RepoRoot: string;
    function DeriveMapLines(const aRoot: string): TStringList;
  published
    procedure BakedInTableAnswersRecordedAliases;
    procedure LookupIsCaseInsensitive;
    procedure LookupOfUnknownNameFails;
    procedure LookupOfAmbiguousNameFails;
    procedure LoadedTableReplacesBakedInUntilReset;
    procedure LoadedTableCollapsesDuplicatesAndDropsConflicts;
    procedure LoadedTableTrimsAroundTheSeparator;
    procedure EmptyFileIsRejectedNamingThePath;
    procedure MalformedFileIsRejectedNamingTheLine;
    procedure AbsentFileIsRejectedNamingThePath;
    procedure DerivedTableMatchesCommittedArtefacts;
  end;

implementation

const
  cMapRelPath = 'packages/fcl-sonar/fpsonar-namespaces.map';
  cMapHeader = '# generated by mknamespacemap from packages/*/namespaces.lst';

// The key part of a 'key=value' line.
function KeyOf(const aLine: string): string;

begin
  Result := Copy(aLine, 1, Pos('=', aLine) - 1);
end;


function CompareMapLines(aList: TStringList; aLeft, aRight: integer): integer;

begin
  Result := CompareStr(KeyOf(aList[aLeft]), KeyOf(aList[aRight]));
  if Result = 0 then
    Result := CompareStr(aList[aLeft], aList[aRight]);
end;


// The nearest enclosing directory carrying both repository markers.
function TNamespaceMapTest.RepoRoot: string;

const
  cThisFile = {$I %FILE%};
  cMarkers: array[0..1] of string = ('rtl/namespaces.lst',
    'packages/fcl-sonar/fpmake.pp');

var
  lStarts: array[0..2] of string;
  lDir, lPrev: string;
  i: Integer;

begin
  Result := '';
  lStarts[0] := ExpandFileName('.');
  lStarts[1] := ExpandFileName(ExtractFilePath(ParamStr(0)));
  lStarts[2] := ExtractFilePath(ExpandFileName(cThisFile));
  for i := Low(lStarts) to High(lStarts) do
    begin
    lDir := IncludeTrailingPathDelimiter(ExpandFileName(lStarts[i]));
    repeat
      if FileExists(lDir + cMarkers[0]) and FileExists(lDir + cMarkers[1]) then
        begin
        Result := lDir;
        Exit;
        end;
      lPrev := lDir;
      lDir := IncludeTrailingPathDelimiter(ExpandFileName(lDir + '..'));
    until lDir = lPrev;
    end;
end;


// Re-derives the .map rendering from every packages/*/namespaces.lst under aRoot.
function TNamespaceMapTest.DeriveMapLines(const aRoot: string): TStringList;

var
  lInfo: TSearchRec;
  lLines, lAll: TStringList;
  lBase, lPath, lLine, lLeft, lRight: string;
  i, j, lSep: integer;

begin
  lAll := TStringList.Create;
  try
    lBase := aRoot + 'packages' + DirectorySeparator;
    if FindFirst(lBase + '*', faDirectory, lInfo) = 0 then
      try
        repeat
          if ((lInfo.Attr and faDirectory) = 0) or (lInfo.Name = '.')
            or (lInfo.Name = '..') then
            Continue;
          lPath := lBase + lInfo.Name + DirectorySeparator + 'namespaces.lst';
          if not FileExists(lPath) then
            Continue;
          lLines := TStringList.Create;
          try
            lLines.LoadFromFile(lPath);
            for i := 0 to lLines.Count - 1 do
              begin
              lLine := Trim(lLines[i]);
              if Copy(lLine, 1, 4) <> 'src/' then
                Continue;
              lSep := Pos('=namespaced/', lLine);
              if lSep = 0 then
                Continue;
              lLeft := Copy(lLine, 1, lSep - 1);
              lRight := Copy(lLine, lSep + 1, Length(lLine) - lSep);
              lAll.Add(LowerCase(ChangeFileExt(ExtractFileName(lLeft), '')) +
                '=' + ChangeFileExt(ExtractFileName(lRight), ''));
              end;
          finally
            lLines.Free;
          end;
        until FindNext(lInfo) <> 0;
      finally
        FindClose(lInfo);
      end;
    lAll.CustomSort(@CompareMapLines);

    Result := TStringList.Create;
    Result.Add(cMapHeader);
    i := 0;
    while i < lAll.Count do
      begin
      j := i;
      while (j + 1 < lAll.Count) and (KeyOf(lAll[j + 1]) = KeyOf(lAll[i])) do
        Inc(j);
      if lAll[i] = lAll[j] then
        Result.Add(lAll[i]);
      i := j + 1;
      end;
  finally
    lAll.Free;
  end;
end;


procedure TNamespaceMapTest.BakedInTableAnswersRecordedAliases;

var
  lDotted: string;

begin
  AssertTrue('fpjson is in the table', LookupNamespace('fpjson', lDotted));
  AssertEquals('fpjson alias', 'FpJson.Data', lDotted);
  AssertTrue('pscanner is in the table', LookupNamespace('pscanner', lDotted));
  AssertEquals('pscanner alias', 'Pascal.Scanner', lDotted);
end;


procedure TNamespaceMapTest.LookupIsCaseInsensitive;

var
  lUpper, lMixed: string;

begin
  AssertTrue('FPJSON resolves', LookupNamespace('FPJSON', lUpper));
  AssertTrue('FpJson resolves', LookupNamespace('FpJson', lMixed));
  AssertEquals('same answer whatever the casing', lUpper, lMixed);
  AssertEquals('the recorded alias', 'FpJson.Data', lUpper);
end;


procedure TNamespaceMapTest.LookupOfUnknownNameFails;

var
  lDotted: string;

begin
  AssertFalse('an absent name has no alias',
    LookupNamespace('nosuchunitanywhere', lDotted));
  AssertEquals('and yields an empty string', '', lDotted);
end;


procedure TNamespaceMapTest.LookupOfAmbiguousNameFails;

var
  lDotted: string;

begin
  // 'serial' is mapped to a different dotted name by six packages.
  AssertFalse('an ambiguous key carries no entry',
    LookupNamespace('serial', lDotted));
  AssertEquals('and yields an empty string', '', lDotted);
end;


procedure TNamespaceMapTest.LoadedTableReplacesBakedInUntilReset;

var
  lFix: TTempFixtures;
  lPath, lErr, lDotted: string;

begin
  lFix := TTempFixtures.Create;
  try
    lPath := lFix.Add('good.map', ['# a table of two', 'fpjson=Test.Json',
      'zzunit=Test.Zz']);
    try
      AssertTrue('the file loads', LoadNamespaceMap(lPath, lErr));
      AssertEquals('no error text', '', lErr);
      AssertTrue('fpjson answers from the file',
        LookupNamespace('fpjson', lDotted));
      AssertEquals('the loaded alias', 'Test.Json', lDotted);
      AssertTrue('zzunit answers from the file',
        LookupNamespace('ZZUNIT', lDotted));
      AssertEquals('the loaded alias', 'Test.Zz', lDotted);
      AssertFalse('the baked-in table is no longer consulted',
        LookupNamespace('pscanner', lDotted));
    finally
      ResetNamespaceMap;
    end;
    AssertTrue('the baked-in table is back',
      LookupNamespace('fpjson', lDotted));
    AssertEquals('the recorded alias', 'FpJson.Data', lDotted);
  finally
    lFix.Free;
  end;
end;


procedure TNamespaceMapTest.LoadedTableCollapsesDuplicatesAndDropsConflicts;

var
  lFix: TTempFixtures;
  lPath, lErr, lDotted: string;

begin
  lFix := TTempFixtures.Create;
  try
    lPath := lFix.Add('dup.map', ['same=Test.Same', 'same=Test.Same',
      'clash=Aaa.One', 'clash=Zzz.Two', 'trio=Aaa.One', 'trio=Bbb.Two',
      'trio=Aaa.One']);
    try
      AssertTrue('the file loads', LoadNamespaceMap(lPath, lErr));
      AssertTrue('identical duplicates collapse to one entry',
        LookupNamespace('same', lDotted));
      AssertEquals('the shared value', 'Test.Same', lDotted);
      AssertFalse('a key with two values carries no entry',
        LookupNamespace('clash', lDotted));
      AssertEquals('and yields an empty string', '', lDotted);
      AssertFalse('a repeated value does not outvote a distinct one',
        LookupNamespace('trio', lDotted));
    finally
      ResetNamespaceMap;
    end;
  finally
    lFix.Free;
  end;
end;


procedure TNamespaceMapTest.LoadedTableTrimsAroundTheSeparator;

var
  lFix: TTempFixtures;
  lPath, lErr, lDotted: string;

begin
  lFix := TTempFixtures.Create;
  try
    lPath := lFix.Add('spaced.map', ['  fpjson  =  FpJson.Data  ']);
    try
      AssertTrue('the file loads', LoadNamespaceMap(lPath, lErr));
      AssertTrue('the key is trimmed', LookupNamespace('fpjson', lDotted));
      AssertEquals('the value is trimmed', 'FpJson.Data', lDotted);
    finally
      ResetNamespaceMap;
    end;
    lPath := lFix.Add('blankvalue.map', ['fpjson =   ']);
    try
      AssertFalse('a blank value is still rejected',
        LoadNamespaceMap(lPath, lErr));
      AssertTrue('the error names the line number', Pos('line 1', lErr) > 0);
    finally
      ResetNamespaceMap;
    end;
  finally
    lFix.Free;
  end;
end;


procedure TNamespaceMapTest.EmptyFileIsRejectedNamingThePath;

var
  lFix: TTempFixtures;
  lPath, lErr, lDotted: string;

begin
  lFix := TTempFixtures.Create;
  try
    lPath := lFix.Add('empty.map', ['# nothing but a comment', '', '   ']);
    try
      AssertFalse('a file without entries is rejected',
        LoadNamespaceMap(lPath, lErr));
      AssertTrue('the error names the path', Pos(lPath, lErr) > 0);
      AssertTrue('the baked-in table is untouched',
        LookupNamespace('fpjson', lDotted));
      AssertEquals('the recorded alias', 'FpJson.Data', lDotted);
    finally
      ResetNamespaceMap;
    end;
  finally
    lFix.Free;
  end;
end;


procedure TNamespaceMapTest.MalformedFileIsRejectedNamingTheLine;

var
  lFix: TTempFixtures;
  lPath, lErr, lDotted: string;

begin
  lFix := TTempFixtures.Create;
  try
    lPath := lFix.Add('bad.map', ['# a table', 'good=Test.Good',
      'noseparatorhere']);
    try
      AssertFalse('a line without = is rejected',
        LoadNamespaceMap(lPath, lErr));
      AssertTrue('the error names the line number', Pos('line 3', lErr) > 0);
      AssertTrue('the baked-in table is untouched',
        LookupNamespace('fpjson', lDotted));
      AssertEquals('the recorded alias', 'FpJson.Data', lDotted);
      AssertFalse('nothing from the file is active',
        LookupNamespace('good', lDotted));
    finally
      ResetNamespaceMap;
    end;
  finally
    lFix.Free;
  end;
end;


procedure TNamespaceMapTest.AbsentFileIsRejectedNamingThePath;

var
  lFix: TTempFixtures;
  lPath, lErr, lDotted: string;

begin
  lFix := TTempFixtures.Create;
  try
    lPath := IncludeTrailingPathDelimiter(lFix.Dir) + 'missing.map';
    try
      AssertFalse('an absent path is rejected',
        LoadNamespaceMap(lPath, lErr));
      AssertTrue('the error names the path', Pos(lPath, lErr) > 0);
      AssertTrue('the baked-in table is untouched',
        LookupNamespace('fpjson', lDotted));
      AssertEquals('the recorded alias', 'FpJson.Data', lDotted);
    finally
      ResetNamespaceMap;
    end;
  finally
    lFix.Free;
  end;
end;


procedure TNamespaceMapTest.DerivedTableMatchesCommittedArtefacts;

var
  lDerived, lCommitted: TStringList;
  lRoot, lMapPath: string;
  i: integer;

begin
  lRoot := RepoRoot;
  if lRoot = '' then
    begin
    Ignore('the repository root could not be located from ' + ParamStr(0));
    Exit;
    end;
  lMapPath := lRoot + cMapRelPath;
  if not FileExists(lMapPath) then
    Fail('the committed map is missing: ' + lMapPath);
  lCommitted := TStringList.Create;
  try
    try
      lCommitted.LoadFromFile(lMapPath);
    except
      on E: Exception do
        Fail('the committed map cannot be read: ' + E.Message);
    end;
    lDerived := DeriveMapLines(lRoot);
    try
      AssertEquals('regenerated line count', lCommitted.Count, lDerived.Count);
      for i := 0 to lDerived.Count - 1 do
        if lDerived[i] <> lCommitted[i] then
          Fail(Format('line %d: committed %s, regenerated %s',
            [i + 1, lCommitted[i], lDerived[i]]));
    finally
      lDerived.Free;
    end;

    AssertEquals('the unit holds as many pairs as the map',
      lCommitted.Count - 1, Length(cNamespaceMap));
    for i := 0 to High(cNamespaceMap) do
      if lCommitted[i + 1] <> cNamespaceMap[i].Plain + '=' + cNamespaceMap[i].Dotted then
        Fail(Format('line %d: map %s, unit %s=%s', [i + 2, lCommitted[i + 1],
          cNamespaceMap[i].Plain, cNamespaceMap[i].Dotted]));
  finally
    lCommitted.Free;
  end;
end;


initialization
  RegisterTest(TNamespaceMapTest);
end.
