#
#   Makefile.fpc for FPC Netware clib demos (part of FPC demo package)
#

[target]
programs_netware=nutmon check nuttest

[default]
fpcdir=../..

[rules]
nutmon.nlm: nutmon.pp nutconnection.pp

nuttest.nlm: nuttest.pp ../netwlibc/nuttest.pp