#
#   Makefile.fpc for FCL lnet examples
#

[require]
packages=fcl

[target]
dirs=ltcp ludp ltelnet lftp lsmtp lhttp
dirs_os2=ltcp ludp ltelnet lftp lsmtp

[compiler]
options=-S2

[install]
fpcpackage=y

[default]
fpcdir=../../..
