program const_test;

uses
  ncurses;

begin
   //writeln('NCURSES_TRIPLE_CLICKED', NCURSES_TRIPLE_CLICKED);
   writeln('BUTTON1_RELEASED ', BUTTON1_RELEASED);
   writeln('BUTTON1_PRESSED ', BUTTON1_PRESSED);
   writeln('BUTTON1_CLICKED ', BUTTON1_CLICKED);
   writeln('BUTTON1_DOUBLE_CLICKED ', BUTTON1_DOUBLE_CLICKED);
   writeln('BUTTON1_TRIPLE_CLICKED ', BUTTON1_TRIPLE_CLICKED);



   writeln('BUTTON2_RELEASED', BUTTON2_RELEASED);
   writeln('BUTTON2_PRESSED', BUTTON2_PRESSED);
   writeln('BUTTON2_CLICKED', BUTTON2_CLICKED);
   writeln('BUTTON2_DOUBLE_CLICKED', BUTTON2_DOUBLE_CLICKED);
   writeln('BUTTON2_TRIPLE_CLICKED', BUTTON2_TRIPLE_CLICKED);

   writeln('BUTTON3_RELEASED', BUTTON3_RELEASED);
   writeln('BUTTON3_PRESSED', BUTTON3_PRESSED);
   writeln('BUTTON3_CLICKED', BUTTON3_CLICKED);
   writeln('BUTTON3_DOUBLE_CLICKED', BUTTON3_DOUBLE_CLICKED);
   writeln('BUTTON3_TRIPLE_CLICKED', BUTTON3_TRIPLE_CLICKED);

   writeln('BUTTON4_RELEASED', BUTTON4_RELEASED);
   writeln('BUTTON4_PRESSED', BUTTON4_PRESSED);
   writeln('BUTTON4_CLICKED', BUTTON4_CLICKED);
   writeln('BUTTON4_DOUBLE_CLICKED', BUTTON4_DOUBLE_CLICKED);
   writeln('BUTTON4_TRIPLE_CLICKED', BUTTON4_TRIPLE_CLICKED);


   //writeln('ALL_MOUSE_EVENTS', ALL_MOUSE_EVENTS);
end.