{ Google Drive demo: list a folder, download a file and upload a file,
  using the Drive API units generated by discovery2pas and OAuth2
  (loopback redirect) for authorization. }
program drivedemo;

{$mode objfpc}{$H+}

uses
  Classes, SysUtils, CustApp, fpjson, jsonparser, fphttpwebclient, opensslsockets,
  fpoauth2, fpoauth2ini, fpopenapiclient, googleapi.client,
  drive.Dto, drive.Serializer, drive.Service.Intf, drive.Service.Impl,
  DriveFiles, GoogleAPI.OAuthRedirect;

const
  DriveScope = 'https://www.googleapis.com/auth/drive';
  DefaultPort = 8085;

type
  EDriveDemo = class(Exception);

  TDriveItem = record
    ID: String;
    Name: String;
    MimeType: String;
  end;

  { TDriveDemoApplication }

  TDriveDemoApplication = class(TCustomApplication)
  private
    FConfig: String;
    FCredentials: String;
    FSession: String;
    FLogFile: String;
    FPort: Word;
    FManual: Boolean;
    FClient: TGoogleAPIClient;
    FFiles: TDriveFilesClient;
    procedure DoUserConsent(const aURL: String; out aAuthCode: String);
    procedure EnsureService;
    function FindChild(const aParentID, aName: String; aFolderOnly: Boolean): TDriveItem;
    function GetItem(const aFileID: String): TDriveItem;
    function ResolveItem(const aSpec: String; aFolderOnly: Boolean): TDriveItem;
    procedure ListFolder(const aSpec: String);
    procedure DownloadFile(const aSpec, aLocalName, aExportMimeType: String);
    procedure UploadFile(const aLocalName, aFolderSpec: String);
  protected
    procedure DoRun; override;
  public
    constructor Create(aOwner: TComponent); override;
    // Show usage information, with aMsg as error message if not empty, and stop.
    procedure WriteHelp(const aMsg: String); virtual;
  end;

// Escape a value for use inside a quoted string of a Drive search query.
function QuoteQuery(const aValue: String): String;

begin
  Result:=StringReplace(aValue,'\','\\',[rfReplaceAll]);
  Result:=StringReplace(Result,'''','\''',[rfReplaceAll]);
end;


// Raise an exception if a service call did not succeed.
procedure CheckServiceResult(aSuccess: Boolean; aCode: Integer; const aText, aAction: String);

begin
  if not aSuccess then
    raise EDriveDemo.CreateFmt('Failed to %s: HTTP %d %s',[aAction,aCode,aText]);
end;


// Free a file list and the files in it.
procedure FreeFileList(aList: TFileList);

var
  lFile: TFile;

begin
  if aList=nil then
    exit;
  for lFile in aList.files do
    lFile.Free;
  aList.Free;
end;


// Return the MIME type for a local file name, based on its extension.
function GuessMimeType(const aFileName: String): String;

const
  Extensions: array[0..14] of String = (
    '.txt','.html','.htm','.csv','.json','.xml','.md','.pdf',
    '.png','.jpg','.jpeg','.gif','.svg','.zip','.pas');
  MimeTypes: array[0..14] of String = (
    'text/plain','text/html','text/html','text/csv','application/json','application/xml',
    'text/markdown','application/pdf','image/png','image/jpeg','image/jpeg','image/gif',
    'image/svg+xml','application/zip','text/plain');

var
  lExt: String;
  lI: Integer;

begin
  Result:='application/octet-stream';
  lExt:=LowerCase(ExtractFileExt(aFileName));
  for lI:=Low(Extensions) to High(Extensions) do
    if Extensions[lI]=lExt then
      Exit(MimeTypes[lI]);
end;


// Return the export MIME type and file extension for a Google Workspace document type.
procedure GetExportFormat(const aMimeType: String; out aExportMimeType, aExtension: String);

begin
  case aMimeType of
    GoogleAppsMimePrefix+'document':
      begin
      aExportMimeType:='application/vnd.openxmlformats-officedocument.wordprocessingml.document';
      aExtension:='.docx';
      end;
    GoogleAppsMimePrefix+'spreadsheet':
      begin
      aExportMimeType:='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
      aExtension:='.xlsx';
      end;
    GoogleAppsMimePrefix+'presentation':
      begin
      aExportMimeType:='application/vnd.openxmlformats-officedocument.presentationml.presentation';
      aExtension:='.pptx';
      end;
  else
    aExportMimeType:='application/pdf';
    aExtension:='.pdf';
  end;
end;


{ TDriveDemoApplication }

constructor TDriveDemoApplication.Create(aOwner: TComponent);

begin
  inherited Create(aOwner);
  StopOnException:=True;
end;


procedure TDriveDemoApplication.DoUserConsent(const aURL: String; out aAuthCode: String);

var
  lURL, lInput: String;
  lListener: TOAuthRedirectListener;

begin
  // Request a refresh token so the next runs need no consent
  lURL:=aURL+'&access_type=offline&prompt=consent';
  Writeln;
  Writeln('User consent required. Open the following URL in a browser:');
  Writeln;
  Writeln(lURL);
  Writeln;
  if FManual then
    begin
    Writeln('After granting access, the browser is sent to ',FClient.RedirectUri);
    Writeln('and shows a connection error. Copy the full address from the');
    Writeln('browser address bar (or only the code parameter) and paste it here.');
    Writeln;
    Write('URL or code: ');
    ReadLn(lInput);
    aAuthCode:=ExtractAuthCode(lInput);
    end
  else
    begin
    lListener:=TOAuthRedirectListener.Create(FPort);
    try
      Writeln('Waiting for the browser to return to ',lListener.RedirectURI,' ...');
      aAuthCode:=lListener.WaitForCode;
    finally
      lListener.Free;
    end;
    end;
  if aAuthCode='' then
    raise EDriveDemo.Create('No authorization code received');
  Writeln('Authorization code received, requesting tokens.');
  Writeln;
end;


procedure TDriveDemoApplication.EnsureService;

var
  lStore: TFPOAuth2IniStore;

begin
  FClient:=TGoogleAPIClient.Create(Self);
  FClient.WebClient:=TFPHTTPWebClient.Create(Self);
  if FLogFile<>'' then
    FClient.WebClient.LogFile:=FLogFile;
  lStore:=TFPOAuth2IniStore.Create(Self);
  lStore.ConfigFileName:=FConfig;
  lStore.SessionFileName:=FConfig;
  FClient.AuthHandler.Store:=lStore;
  FClient.AuthHandler.LoadConfig;
  if FCredentials<>'' then
    begin
    FClient.RedirectUri:='';
    FClient.LoadCredentials(FCredentials);
    end;
  if not FClient.HasCredentials then
    raise EDriveDemo.CreateFmt('No OAuth2 client ID/secret found in %s. Use -j to import the client JSON file.',[FConfig]);
  FClient.Scopes:=DriveScope;
  FClient.RedirectUri:=Format('http://127.0.0.1:%d',[FPort]);
  FClient.AuthHandler.Config.AccessType:=atOffline;
  if FCredentials<>'' then
    FClient.AuthHandler.SaveConfig;
  FClient.AuthHandler.LoadSession(FSession);
  FClient.OnUserConsent:=@DoUserConsent;
  FFiles:=TDriveFilesClient.Create(Self);
  FClient.ConfigureService(FFiles);
end;


function TDriveDemoApplication.GetItem(const aFileID: String): TDriveItem;

var
  lResult: TFileServiceResult;

begin
  lResult:=FFiles.Get(aFileID,'','');
  CheckServiceResult(lResult.Success,lResult.ErrorCode,lResult.ErrorText,'get file '+aFileID);
  try
    Result.ID:=lResult.Value.id;
    Result.Name:=lResult.Value.name;
    Result.MimeType:=lResult.Value.mimeType;
  finally
    lResult.Value.Free;
  end;
end;


function TDriveDemoApplication.FindChild(const aParentID, aName: String; aFolderOnly: Boolean): TDriveItem;

var
  lQuery: String;
  lResult: TFileListServiceResult;

begin
  lQuery:=Format('name = ''%s'' and ''%s'' in parents and trashed = false',[QuoteQuery(aName),QuoteQuery(aParentID)]);
  if aFolderOnly then
    lQuery:=lQuery+Format(' and mimeType = ''%s''',[DriveFolderMimeType]);
  lResult:=FFiles.List('','','','','','folder,name','',lQuery,'',False,False,10);
  CheckServiceResult(lResult.Success,lResult.ErrorCode,lResult.ErrorText,'search for '+aName);
  try
    if Length(lResult.Value.files)=0 then
      raise EDriveDemo.CreateFmt('"%s" not found',[aName]);
    if Length(lResult.Value.files)>1 then
      Writeln('Warning: ',Length(lResult.Value.files),' items named "',aName,'", using the first one.');
    Result.ID:=lResult.Value.files[0].id;
    Result.Name:=lResult.Value.files[0].name;
    Result.MimeType:=lResult.Value.files[0].mimeType;
  finally
    FreeFileList(lResult.Value);
  end;
end;


function TDriveDemoApplication.ResolveItem(const aSpec: String; aFolderOnly: Boolean): TDriveItem;

var
  lParts: TStringArray;
  lPart: String;

begin
  if (aSpec='') or (aSpec='/') then
    Result:=GetItem('root')
  else if aSpec[1]<>'/' then
    Result:=GetItem(aSpec)
  else
    begin
    Result:=GetItem('root');
    lParts:=aSpec.Split(['/'],TStringSplitOptions.ExcludeEmpty);
    for lPart in lParts do
      begin
      if Result.MimeType<>DriveFolderMimeType then
        raise EDriveDemo.CreateFmt('"%s" is not a folder',[Result.Name]);
      Result:=FindChild(Result.ID,lPart,aFolderOnly);
      end;
    end;
  if aFolderOnly and (Result.MimeType<>DriveFolderMimeType) then
    raise EDriveDemo.CreateFmt('"%s" is not a folder',[aSpec]);
end;


procedure TDriveDemoApplication.ListFolder(const aSpec: String);

var
  lFolder: TDriveItem;
  lResult: TFileListServiceResult;
  lFile: TFile;
  lQuery, lPageToken, lKind: String;
  lCount: Integer;

begin
  lFolder:=ResolveItem(aSpec,True);
  Writeln('Contents of "',lFolder.Name,'" (ID ',lFolder.ID,'):');
  Writeln;
  lQuery:=Format('''%s'' in parents and trashed = false',[QuoteQuery(lFolder.ID)]);
  lPageToken:='';
  lCount:=0;
  repeat
    lResult:=FFiles.List('','','','','','folder,name',lPageToken,lQuery,'');
    CheckServiceResult(lResult.Success,lResult.ErrorCode,lResult.ErrorText,'list folder');
    try
      for lFile in lResult.Value.files do
        begin
        Inc(lCount);
        if lFile.mimeType=DriveFolderMimeType then
          lKind:='<DIR>'
        else
          lKind:='';
        Writeln(Format('%-5s  %-40s  %-44s  %s',[lKind,lFile.name,lFile.id,lFile.mimeType]));
        end;
      lPageToken:=lResult.Value.nextPageToken;
    finally
      FreeFileList(lResult.Value);
    end;
  until lPageToken='';
  Writeln;
  Writeln(lCount,' item(s)');
end;


procedure TDriveDemoApplication.DownloadFile(const aSpec, aLocalName, aExportMimeType: String);

var
  lItem: TDriveItem;
  lExport: Boolean;
  lMimeType, lExtension, lLocalName: String;
  lStream: TFileStream;
  lResponse: TServiceResponse;
  lSize: Int64;

begin
  lItem:=ResolveItem(aSpec,False);
  if lItem.MimeType=DriveFolderMimeType then
    raise EDriveDemo.CreateFmt('"%s" is a folder',[lItem.Name]);
  lExport:=IsGoogleAppsMimeType(lItem.MimeType);
  lExtension:='';
  if lExport then
    begin
    GetExportFormat(lItem.MimeType,lMimeType,lExtension);
    if aExportMimeType<>'' then
      begin
      lMimeType:=aExportMimeType;
      lExtension:='';
      end;
    end;
  lLocalName:=aLocalName;
  if lLocalName='' then
    lLocalName:=StringReplace(lItem.Name,'/','_',[rfReplaceAll])+lExtension;
  lStream:=TFileStream.Create(lLocalName,fmCreate);
  try
    if lExport then
      begin
      Writeln('Exporting "',lItem.Name,'" as ',lMimeType);
      lResponse:=FFiles.ExportContent(lItem.ID,lMimeType,lStream);
      end
    else
      begin
      Writeln('Downloading "',lItem.Name,'"');
      lResponse:=FFiles.DownloadContent(lItem.ID,lStream);
      end;
    lSize:=lStream.Size;
  finally
    lStream.Free;
  end;
  if (lResponse.StatusCode div 100)<>2 then
    begin
    DeleteFile(lLocalName);
    raise EDriveDemo.CreateFmt('Download failed: HTTP %d %s %s',[lResponse.StatusCode,lResponse.StatusText,lResponse.Content]);
    end;
  Writeln('Saved to ',lLocalName,' (',lSize,' bytes)');
end;


procedure TDriveDemoApplication.UploadFile(const aLocalName, aFolderSpec: String);

var
  lFolder: TDriveItem;
  lStream: TFileStream;
  lResult: TFileServiceResult;

begin
  if not FileExists(aLocalName) then
    raise EDriveDemo.CreateFmt('Local file "%s" does not exist',[aLocalName]);
  lFolder:=ResolveItem(aFolderSpec,True);
  Writeln('Uploading ',aLocalName,' to "',lFolder.Name,'"');
  lStream:=TFileStream.Create(aLocalName,fmOpenRead or fmShareDenyWrite);
  try
    lResult:=FFiles.UploadContent(ExtractFileName(aLocalName),lFolder.ID,GuessMimeType(aLocalName),lStream);
  finally
    lStream.Free;
  end;
  CheckServiceResult(lResult.Success,lResult.ErrorCode,lResult.ErrorText,'upload '+aLocalName);
  try
    Writeln('Created "',lResult.Value.name,'" (ID ',lResult.Value.id,', ',lResult.Value.mimeType,')');
  finally
    lResult.Value.Free;
  end;
end;


procedure TDriveDemoApplication.DoRun;

var
  lError: String;

begin
  lError:=CheckOptions('hld:t:u:f:e:c:j:s:o:p:m',
    ['help','list','download:','to:','upload:','folder:','export-mime:',
     'config:','credentials:','session:','logfile:','port:','manual']);
  if (lError<>'') or HasOption('h','help') then
    WriteHelp(lError);
  FConfig:=GetOptionValue('c','config');
  if FConfig='' then
    FConfig:=ExtractFilePath(ParamStr(0))+'google.ini';
  FCredentials:=GetOptionValue('j','credentials');
  FSession:=GetOptionValue('s','session');
  if FSession='' then
    FSession:='me';
  FLogFile:=GetOptionValue('o','logfile');
  FPort:=StrToIntDef(GetOptionValue('p','port'),DefaultPort);
  FManual:=HasOption('m','manual');
  EnsureService;
  try
    if HasOption('d','download') then
      DownloadFile(GetOptionValue('d','download'),GetOptionValue('t','to'),GetOptionValue('e','export-mime'))
    else if HasOption('u','upload') then
      UploadFile(GetOptionValue('u','upload'),GetOptionValue('f','folder'))
    else
      ListFolder(GetOptionValue('f','folder'));
  finally
    FClient.AuthHandler.SaveSession(FSession);
  end;
  Terminate;
end;


procedure TDriveDemoApplication.WriteHelp(const aMsg: String);

begin
  if aMsg<>'' then
    Writeln('Error : ',aMsg);
  Writeln('Usage: ',ExeName,' [options]');
  Writeln;
  Writeln('Actions (default: --list):');
  Writeln('  -l --list                 List the folder given by --folder.');
  Writeln('  -d --download=FILE        Download FILE. Google Docs/Sheets/Slides are exported.');
  Writeln('  -u --upload=LOCALFILE     Upload LOCALFILE into the folder given by --folder.');
  Writeln;
  Writeln('Options:');
  Writeln('  -f --folder=FOLDER        Drive folder for --list and --upload (default: My Drive).');
  Writeln('  -t --to=LOCALFILE         Local file name for --download (default: Drive name).');
  Writeln('  -e --export-mime=MIME     Export format for Google Workspace documents.');
  Writeln('  -c --config=FILE          Config file with client data and tokens (default google.ini).');
  Writeln('  -j --credentials=FILE     Import OAuth client JSON from Google Cloud Console into the config file.');
  Writeln('  -s --session=NAME         Session (token set) name in the config file (default: me).');
  Writeln('  -p --port=PORT            Local port for the OAuth2 redirect (default ',DefaultPort,').');
  Writeln('  -m --manual               Paste the redirect URL instead of running a local listener.');
  Writeln('  -o --logfile=FILE         Log HTTP requests and responses to FILE.');
  Writeln('  -h --help                 This help.');
  Writeln;
  Writeln('FILE and FOLDER are either a Drive ID (e.g. 1AbC...) or a path starting');
  Writeln('with / relative to My Drive (e.g. /Documents/report.pdf).');
  Halt(Ord(aMsg<>''));
end;


var
  Application: TDriveDemoApplication;

begin
  Application:=TDriveDemoApplication.Create(nil);
  Application.Title:='Google Drive demo';
  Application.Run;
  Application.Free;
end.
