#
#  Makefile.fpc to create and group units needed for
#  tests for all targets
#

[target]
units=erroru

[install]
fpcpackage=y

[default]
fpcdir=../..


[rules]

# Only 1.1 has Classes in the RTL
ifneq ($(findstring 1.0.,$(FPC_VERSION)),)
FCL=fcl
endif

DUMMYINSTALLDIR=$(BASEDIR)/tmp
INSTALLOPT=INSTALL_PREFIX=$(DUMMYINSTALLDIR) INSTALL_UNITDIR=$(BASEDIR)

.PHONY: rtl clean $(FCL)

ifndef USEUNITDIR

rtl:
        $(MAKE) -C ../../rtl all "OPT=$(OPT) -n"
        $(MAKE) -C ../../rtl install $(INSTALLOPT)

ifdef FCL
fcl:
        $(MAKE) -C ../../packages/base all "OPT=$(OPT) -n"
        $(MAKE) -C ../../fcl all "OPT=$(OPT) -n"
        $(MAKE) -C ../../fcl install $(INSTALLOPT)
endif

clean : cleanall
#        $(MAKE) -C ../../rtl clean
#        $(MAKE) -C ../../fcl clean
        $(DELTREE) $(DUMMYINSTALLDIR)

else

rtl:
#       Just copying everything doesn't work, because then the Makefile will be overwritten
        -$(COPY) $(USEUNITDIR)/*$(PPUEXT) .
        -$(COPY) $(USEUNITDIR)/*$(OEXT) .
        -$(COPY) $(USEUNITDIR)/*$(ASMEXT) .
        -$(COPY) $(USEUNITDIR)/*_ppas .
        $(ECHO) Copied > $(FPCMADE)

ifdef FCL
fcl: rtl
endif

clean : cleanall
        $(DELTREE) $(DUMMYINSTALLDIR)

endif

erroru$(PPUEXT): erroru.pp rtl $(FCL)
