#
#  Makefile.fpc to create and group units needed for
#  tests for all targets
#

[target]
units=erroru


[rules]
.PHONY: rtl fcl clean

rtl:
        $(MAKE) -C ../../rtl/$(OS_TARGET) all
        $(MAKE) -C ../../rtl/$(OS_TARGET) install INSTALL_UNITDIR=$(BASEDIR)

fcl:
        $(MAKE) -C ../../fcl/$(OS_TARGET) all
        $(MAKE) -C ../../fcl/$(OS_TARGET) install INSTALL_UNITDIR=$(BASEDIR)

clean : cleanall

erroru$(PPUEXT): erroru.pp rtl fcl

