#
#   Makefile.fpc for FPCMake
#

[target]
programs=fpcres
units=msghandler paramparser sourcehandler  target
rsts=fpcres fpcresfix elfres

[clean]
units=fpcresfix elfbfd elfres

[require]
packages=rtl fcl-res

[install]
fpcpackage=y

[default]
fpcdir=../..

[rules]
