#
#   Makefile.fpc for FCL lnet example http server/client
#

[require]
packages=fcl

[target]
programs=fpget fphttpd
units=lhttpsettings

[compiler]
options=-S2

[install]
fpcpackage=y

[default]
fpcdir=../../../..
