# $Id: makefile.cpu,v 1.1 2002/11/16 20:10:31 florian Exp $
#
# Here we set processor dependent include file names.
#

CPUNAMES=sparc
# not yet: math set

CPUINCNAMES=$(addsuffix .inc,$(CPUNAMES))

#
# $Log: makefile.cpu,v $
# Revision 1.1  2002/11/16 20:10:31  florian
#   + sparc specific rtl skeleton added
#
#
#
