#!/bin/sh

CROSSTOOLSROOT=~/cross
FPCCVS=~/cvs/devel/fpc
DESTDIR=~/fpcsnap
LOGDIR=~/logs
MYINTEL=i686
EXTRAOPT=-gl
TARGETS_OS="freebsd linux netbsd openbsd solaris win32 darwin"
TARGETS_CPU="i386 powerpc sparc"


###########################################################################
# don't edit below
#
#
#
#

MYHOSTARCH=`uname -p | tr "[:upper:]" "[:lower:]"`
MYHOSTOS=`uname -s | tr "[:upper:]" "[:lower:]"`
echo HOST platform is ${MYHOSTARCH}-${MYHOSTOS}

#
#
# force slash
#

CROSSTOOLSROOT=${CROSSTOOLSROOT%/}/
FPCCVS=${FPCCVS%/}/
DESTDIR=${DESTDIR%/}/
LOGDIR=${LOGDIR%/}/

#
# BSD? -> ${MAKE}
#

MAKE=make

case "$MYHOSTOS" in
 *BSD*) MAKE=gmake
  ;;
 *bsd*) MAKE=gmake  
  ;;
esac

#
# Setup dirs
#

mkdir -p ${DESTDIR}
mkdir -p ${LOGDIR}

#
# Real build starts here
#

cd ${FPCCVS}

FAILURES=""

for CPU in $TARGETS_CPU; do

# CPU xlat. translate from FPC cpu designation to binutil's;

MCPU=${CPU}
if [ "${CPU}" = "i386" ]; then
MCPU=${MYINTEL}
fi

for OS in $TARGETS_OS; do

# xlat for OS

MOS=${OS}
if [ "${OS}" = "sunos" ]; then
MOS=solaris
fi

if [ "${OS}" = "win32" ]; then
MOS=cygwin
fi

dothisbuild=1
if [ "${CPU}" = "${MYHOSTARCH}" ]; then
if [ "${OS}" = "${MYHOSTOS}" ]; then
dothisbuild=0
fi
fi

if [ $dothisbuild -eq 1 ]; then
echo Building ${CPU}-${OS}
if [  -f ${CROSSTOOLSROOT}bin/${MCPU}-${MOS}-as ]; then
${MAKE} clean all CROSSBINDIR=${CROSSTOOLSROOT}bin OS_TARGET=${OS} CPU_TARGET=${CPU} BINUTILSPREFIX=${MCPU}-${MOS}- OPT=${EXTRAOPT} > ${FPCCVS}log-${CPU}-${OS} 2>&1
else
echo can''t find binutils-${MCPU}-${OS} for FPC-${CPU}-${OS}
fi

if [ ! $? = 0 ]; then
echo ${CPU}-${OS} FAILES!
FAILURES="${FAILURES} ${CPU}-${OS}"
else
mkdir -p ${DESTDIR}${CPU}-${OS}
${MAKE} install INSTALL_PREFIX=${DESTDIR}${CPU}-${OS} CROSSBINDIR=${CROSSTOOLSROOT}bin OS_TARGET=${OS} CPU_TARGET=${CPU} BINUTILSPREFIX=${MCPU}-${MOS}- OPT=${EXTRAOPT} > ${LOGDIR}log-${CPU}-${OS} 2>&1
fi
fi
done;
done;

echo platforms failed: ${FAILURES}

