#
#   Makefile.fpc for Free Pascal installer
#

[targets]
programs=install

[install]
packagename=fpinst
sourcesubdir=fpinst

[clean]
units=ziptypes unzip
units_os2=unzipdll

[require]
packages=api fv

[dirs]
fpcdir=..
targetdir=.
