#
#   Makefile.fpc for FPC OS/2 demos (part of FPC demo package)
#

[target]
programs_os2=basicpm pmdemo1 getctry

[default]
fpcdir=../..

[rules]
basicpm.exe: basicpm.pas
        $(COMPILER) -Dw -Ch8096 -Cs32728 basicpm.pas

pmdemo1.exe: pmdemo1.pp pmdemo1.res
        $(COMPILER) -Dw -Ch8096 -Cs32728 pmdemo1.pp

pmdemo1.res: pmdemo1.rc pmdemo1.h
        $(RC) -r pmdemo1
