#
#   Makefile.fpc for FCL Pascal source file parsing and writing units
#

[package]
main=fcl

[target]
units=pastree pscanner pparser paswrite
rsts=pscanner pparser pastree

[compiler]
options=-S2h

[install]
fpcpackage=y

[default]
fpcdir=../..
