unit h2pconst;

interface

// Generated by lexer/scanner. We may need to update this if the scanner/lexer changes

const _WHILE = 257;
const _FOR = 258;
const _DO = 259;
const _GOTO = 260;
const _CONTINUE = 261;
const _BREAK = 262;
const TYPEDEF = 263;
const DEFINE = 264;
const COLON = 265;
const SEMICOLON = 266;
const COMMA = 267;
const LKLAMMER = 268;
const RKLAMMER = 269;
const LECKKLAMMER = 270;
const RECKKLAMMER = 271;
const LGKLAMMER = 272;
const RGKLAMMER = 273;
const STRUCT = 274;
const UNION = 275;
const ENUM = 276;
const ID = 277;
const NUMBER = 278;
const CSTRING = 279;
const SHORT = 280;
const UNSIGNED = 281;
const LONG = 282;
const INT = 283;
const FLOAT = 284;
const _CHAR = 285;
const VOID = 286;
const _CONST = 287;
const _FAR = 288;
const _HUGE = 289;
const _NEAR = 290;
const NEW_LINE = 291;
const SPACE_DEFINE = 292;
const EXTERN = 293;
const STDCALL = 294;
const CDECL = 295;
const CALLBACK = 296;
const PASCAL = 297;
const WINAPI = 298;
const APIENTRY = 299;
const WINGDIAPI = 300;
const SYS_TRAP = 301;
const _PACKED = 302;
const ELLIPSIS = 303;
const _ASSIGN = 304;
const R_AND = 305;
const QUESTIONMARK = 306;
const _LOR = 307;
const _LAND = 308;
const _OR = 309;
const _XOR = 310;
const _AND = 311;
const EQUAL = 312;
const UNEQUAL = 313;
const GT = 314;
const LT = 315;
const GTE = 316;
const LTE = 317;
const _SHR = 318;
const _SHL = 319;
const _PLUS = 320;
const MINUS = 321;
const STAR = 322;
const _SLASH = 323;
const _MOD = 324;
const _NOT = 325;
const _LNOT = 326;
const PSTAR = 327;
const P_AND = 328;
const POINT = 329;
const DEREF = 330;
const STICK = 331;
const SIGNED = 332;
const INT8 = 333;
const INT16 = 334;
const INT32 = 335;
const INT64 = 336;
const _DOUBLE = 337;
const _RETURN = 338;
const _STATIC = 339;

const
  SHORT_STR = 'shortint';
  USHORT_STR = 'byte';
  //C++ SHORT types usually map to the small types
  SMALL_STR  = 'smallint';
  USMALL_STR = 'word';
  INT_STR    = 'longint';
  UINT_STR   = 'dword';
  CHAR_STR   = 'char';
  ANSICHAR_STR   = 'ansichar';
  UCHAR_STR  = USHORT_STR; { should we use byte or char for 'unsigned char' ?? }

  INT64_STR  = 'int64';
  QWORD_STR  = 'qword';
  FLOAT_STR  = 'single';
  DOUBLE_STR = 'double';
  EXTENDED_STR = 'extended';
  WCHAR_STR  = 'widechar';

  {ctypes strings}
const
  cint8_STR       = 'cint8';
  cuint8_STR      = 'cuint8';
  cchar_STR       = 'cchar';
  cschar_STR      = 'cschar';
  cuchar_STR      = 'cuchar';

  cint16_STR      = 'cint16';
  cuint16_STR     = 'cuint16';
  cshort_STR      = 'cshort';
  csshort_STR     = 'csshort';
  cushort_STR     = 'cushort';

  cint32_STR      = 'cint32';
  cuint32_STR     = 'cuint32';
  cint_STR        = 'cint';
  csint_STR       = 'csint';
  cuint_STR       = 'cuint';

  csigned_STR     = 'csigned';
  cunsigned_STR   = 'cunsigned';

  cint64_STR      = 'cint64';
  cuint64_STR     = 'cuint64';
  clonglong_STR   = 'clonglong';
  cslonglong_STR  = 'cslonglong';
  culonglong_STR  = 'culonglong';

  cbool_STR       = 'cbool';

  clong_STR       = 'clong';
  cslong_STR      = 'cslong';
  culong_STR      = 'culong';

  cfloat_STR      = 'cfloat';
  cdouble_STR     = 'cdouble';
  clongdouble_STR = 'clongdouble';

  csize_t_STR     = 'csize_t';

type
  // A standard C type name with its ctypes and its Pascal type.
  TCTypeMapping = record
    CName, CTypesName, PascalName : string;
  end;

const
  MAX_CTYPEMAPPINGS = 24;
  CTypeMappings : array [0..MAX_CTYPEMAPPINGS] of TCTypeMapping = (
    (CName: 'int8_t';    CTypesName: cint8_STR;   PascalName: 'shortint'),
    (CName: 'uint8_t';   CTypesName: cuint8_STR;  PascalName: 'byte'),
    (CName: 'int16_t';   CTypesName: cint16_STR;  PascalName: 'smallint'),
    (CName: 'uint16_t';  CTypesName: cuint16_STR; PascalName: 'word'),
    (CName: 'int32_t';   CTypesName: cint32_STR;  PascalName: 'longint'),
    (CName: 'uint32_t';  CTypesName: cuint32_STR; PascalName: 'longword'),
    (CName: 'int64_t';   CTypesName: cint64_STR;  PascalName: 'int64'),
    (CName: 'uint64_t';  CTypesName: cuint64_STR; PascalName: 'qword'),
    (CName: 'intmax_t';  CTypesName: cint64_STR;  PascalName: 'int64'),
    (CName: 'uintmax_t'; CTypesName: cuint64_STR; PascalName: 'qword'),
    (CName: 'size_t';    CTypesName: csize_t_STR; PascalName: 'SizeUInt'),
    (CName: 'ssize_t';   CTypesName: 'SizeInt';   PascalName: 'SizeInt'),
    (CName: 'intptr_t';  CTypesName: 'PtrInt';    PascalName: 'PtrInt'),
    (CName: 'uintptr_t'; CTypesName: 'PtrUInt';   PascalName: 'PtrUInt'),
    (CName: 'ptrdiff_t'; CTypesName: 'PtrInt';    PascalName: 'PtrInt'),
    (CName: '_Bool';     CTypesName: 'Boolean';   PascalName: 'Boolean'),
    (CName: 'bool';      CTypesName: 'Boolean';   PascalName: 'Boolean'),
    (CName: 'wchar_t';   CTypesName: 'UCS4Char';  PascalName: 'UCS4Char'),
    (CName: 'char16_t';  CTypesName: 'WideChar';  PascalName: 'WideChar'),
    (CName: 'char32_t';  CTypesName: 'UCS4Char';  PascalName: 'UCS4Char'),
    (CName: 'off_t';     CTypesName: 'coff_t';    PascalName: 'PtrInt'),
    (CName: 'off64_t';   CTypesName: cint64_STR;  PascalName: 'int64'),
    (CName: 'va_list';   CTypesName: 'pointer';   PascalName: 'pointer'),
    (CName: '__gnuc_va_list'; CTypesName: 'pointer'; PascalName: 'pointer'),
    (CName: '__builtin_va_list'; CTypesName: 'pointer'; PascalName: 'pointer')
  );

const
  MAX_CTYPESARRAY = 26;
  CTypesArray : array [0..MAX_CTYPESARRAY] of string =
  (cint8_STR,     cuint8_STR,
    cchar_STR,     cschar_STR,     cuchar_STR,
    cint16_STR,    cuint16_STR,
    cshort_STR,    csshort_STR,    cushort_STR,
    csigned_STR,   cunsigned_STR,
    cint32_STR,    cuint32_STR,    cint_STR,
    csint_STR,     cuint_STR,
    cint64_STR,    cuint64_STR,
    clonglong_STR, cslonglong_STR, culonglong_STR,

    cbool_STR,
    clong_STR,      cslong_STR,    culong_STR,
    csize_t_STR);



implementation
end.
