# $Id: makefile.cpu,v 1.2 2002/09/07 16:01:26 peter Exp $
#
# Here we set processor dependent include file names.
#

CPUNAMES=powerpc math set
CPUINCNAMES=$(addsuffix .inc,$(CPUNAMES))
#
# $Log: makefile.cpu,v $
# Revision 1.2  2002/09/07 16:01:26  peter
#   * old logs removed and tabs fixed
#
# Revision 1.1  2002/07/26 16:54:48  florian
#   + initial version
#
#
