{ %NORUN }
{ %TARGET=win32,win64,wince }

program tb0596;

const
  IMAGE_FILE_LARGE_ADDRESS_AWARE = $0020;
  IMAGE_REMOVABLE_RUN_FROM_SWAP  = $0400;
  IMAGE_NET_RUN_FROM_SWAP        = $0800;
  IMAGE_DLLCHARACTERISTICS_NO_ISOLATION          = $0200;
  IMAGE_DLLCHARACTERISTICS_APPCONTAINER          = $1000;
  IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE = $8000;

{$setpeflags IMAGE_FILE_LARGE_ADDRESS_AWARE}
{$setpeflags $0800}
{$setpeflags IMAGE_REMOVABLE_RUN_FROM_SWAP or IMAGE_NET_RUN_FROM_SWAP}
{$setpeflags $0008 or $0004}

{$setpeoptflags IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE}
{$setpeoptflags $0040}
{$setpeoptflags IMAGE_DLLCHARACTERISTICS_APPCONTAINER or IMAGE_DLLCHARACTERISTICS_NO_ISOLATION}
{$setpeoptflags $0008 or $0004}

begin

end.
