#
# This makefile sets some needed variable, common to all targets
#

INCNAMES=classes.inc classesh.inc bits.inc collect.inc compon.inc filer.inc \
         lists.inc parser.inc persist.inc reader.inc streams.inc stringl.inc \
         writer.inc cregist.inc

INCUNITS=inifiles registry ezcgi pipes rtfpars idea base64 gettext iostream zstream cachecls

