#
# Makefile.fpc for SQLIte FCL db units
#

[package]
main=fcl

[target]
units=sqliteds

[require]
packages=sqlite

[compiler]
targetdir=../../$(OS_TARGET)

[install]
fpcpackage=y

[default]
fpcdir=../../..
