#
#   $Id$
#   Copyright (c) 1998 by the Free Pascal Development Team
#
#   Makefile for <template>
#
#   See the file COPYING.FPC, included in this distribution,
#   for details about the copyright.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#

#####################################################################
# Defaults
#####################################################################

# Where are the files located
MAKEFILEFPC=makefile.fpc
RTL=
INC=
PROCINC=
OSINC=

# Add this dir also to the path as first
UNITDIR=

# Where need we to place the executables/ppu/objects
TARGETDIR=
UNITTARGETDIR=

#####################################################################
# Real targets
#####################################################################

UNITOBJECTS=
EXEOBJECTS=

#####################################################################
# Include default makefile
#####################################################################

include $(MAKEFILEFPC)

#####################################################################
# Dependencies
#####################################################################

#
# $Log$
# Revision 1.1  1998-10-27 14:20:12  peter
#   + initial versions
#
#
