{****************************************************************************

                   Copyright (c) 1993,94 by Florian Kl„mpfl
                  
 ****************************************************************************}
unit pmgpi;

  interface
  
    uses
       os2def,pmbitmap;

    const
       GPI_ERROR = 0;
       GPI_OK = 1;
       GPI_ALTERROR = (-1);

       CLR_NOINDEX = (-254);
       PU_ARBITRARY = $0004;
       PU_PELS = $0008;
       PU_LOMETRIC = $000C;
       PU_HIMETRIC = $0010;
       PU_LOENGLISH = $0014;
       PU_HIENGLISH = $0018;
       PU_TWIPS = $001C;
       GPIF_DEFAULT = 0;
       GPIF_SHORT = $0100;
       GPIF_LONG = $0200;
       GPIT_NORMAL = 0;
       GPIT_MICRO = $1000;
       GPIA_NOASSOC = 0;
       GPIA_ASSOC = $4000;
       HDC_ERROR = -1;

       GRES_ATTRS = $0001;
       GRES_SEGMENTS = $0002;
       GRES_ALL = $0004;
       PS_UNITS = $00FC;
       PS_FORMAT = $0F00;
       PS_TYPE = $1000;
       PS_MODE = $2000;
       PS_ASSOCIATE = $4000;
       PS_NORESET = $8000;
       GPIE_SEGMENT = 0;
       GPIE_ELEMENT = 1;
       GPIE_DATA = 2;
       DCTL_ERASE = 1;
       DCTL_DISPLAY = 2;
       DCTL_BOUNDARY = 3;
       DCTL_DYNAMIC = 4;
       DCTL_CORRELATE = 5;
       DCTL_ERROR = -1;
       DCTL_OFF = 0;
       DCTL_ON = 1;
       SDW_ERROR = -1;
       SDW_OFF = 0;
       SDW_ON = 1;
       DM_ERROR = 0;
       DM_DRAW = 1;
       DM_RETAIN = 2;
       DM_DRAWANDRETAIN = 3;

       PICKAP_DEFAULT = 0;
       PICKAP_REC = 2;
       PICKSEL_VISIBLE = 0;
       PICKSEL_ALL = 1;
       GPI_HITS = 2;

       DFORM_NOCONV = 0;
       DFORM_S370SHORT = 1;
       DFORM_PCSHORT = 2;
       DFORM_PCLONG = 4;
       ATTR_ERROR = (-1);
       ATTR_DETECTABLE = 1;
       ATTR_VISIBLE = 2;
       ATTR_CHAINED = 6;
       ATTR_DYNAMIC = 8;
       ATTR_FASTCHAIN = 9;
       ATTR_PROP_DETECTABLE = 10;
       ATTR_PROP_VISIBLE = 11;
       ATTR_OFF = 0;
       ATTR_ON = 1;
       LOWER_PRI = (-1);
       HIGHER_PRI = 1;

       SEGEM_ERROR = 0;
       SEGEM_INSERT = 1;
       SEGEM_REPLACE = 2;

       CVTC_WORLD = 1;
       CVTC_MODEL = 2;
       CVTC_DEFAULTPAGE = 3;
       CVTC_PAGE = 4;
       CVTC_DEVICE = 5;
       TRANSFORM_REPLACE = 0;
       TRANSFORM_ADD = 1;
       TRANSFORM_PREEMPT = 2;

       MPATH_STROKE = 6;
       FPATH_ALTERNATE = 0;
       FPATH_WINDING = 2;
       FPATH_EXCL = 0;
       FPATH_INCL = 8;
       SCP_ALTERNATE = 0;
       SCP_WINDING = 2;
       SCP_AND = 4;
       SCP_RESET = 0;
       SCP_EXCL = 0;
       SCP_INCL = 8;

       LCOL_RESET = $0001;
       LCOL_REALIZABLE = $0002;
       LCOL_PURECOLOR = $0004;
       LCOL_OVERRIDE_DEFAULT_COLORS = $0008;
       LCOL_REALIZED = $0010;
       LCOLF_DEFAULT = 0;
       LCOLF_INDRGB = 1;
       LCOLF_CONSECRGB = 2;
       LCOLF_RGB = 3;
       LCOLF_PALETTE = 4;
       LCOLOPT_REALIZED = $0001;
       LCOLOPT_INDEX = $0002;
       QLCT_ERROR = (-1);
       QLCT_RGB = (-2);
       QLCT_NOTLOADED = (-1);
       QCD_LCT_FORMAT = 0;
       QCD_LCT_LOINDEX = 1;
       QCD_LCT_HIINDEX = 2;
       QCD_LCT_OPTIONS = 3;
       PAL_ERROR = (-1);
       PC_RESERVED = $01;
       PC_EXPLICIT = $02;
       PC_NOCOLLAPSE = $04;

       CLR_FALSE = (-5);
       CLR_TRUE = (-4);
       CLR_ERROR = (-255);
       CLR_DEFAULT = (-3);
       CLR_WHITE = (-2);
       CLR_BLACK = (-1);
       CLR_BACKGROUND = 0;
       CLR_BLUE = 1;
       CLR_RED = 2;
       CLR_PINK = 3;
       CLR_GREEN = 4;
       CLR_CYAN = 5;
       CLR_YELLOW = 6;
       CLR_NEUTRAL = 7;
       CLR_DARKGRAY = 8;
       CLR_DARKBLUE = 9;
       CLR_DARKRED = 10;
       CLR_DARKPINK = 11;
       CLR_DARKGREEN = 12;
       CLR_DARKCYAN = 13;
       CLR_BROWN = 14;
       CLR_PALEGRAY = 15;
       RGB_ERROR = (-255);
       RGB_BLACK = $00000000;
       RGB_BLUE = $000000FF;
       RGB_GREEN = $0000FF00;
       RGB_CYAN = $0000FFFF;
       RGB_RED = $00FF0000;
       RGB_PINK = $00FF00FF;
       RGB_YELLOW = $00FFFF00;
       RGB_WHITE = $00FFFFFF;
       BA_NOBOUNDARY = 0;
       BA_BOUNDARY = $0001;
       BA_ALTERNATE = 0;
       BA_WINDING = $0002;
       BA_EXCL = 0;
       BA_INCL = 8;
       DRO_FILL = 1;
       DRO_OUTLINE = 2;
       DRO_OUTLINEFILL = 3;
       PATSYM_ERROR = (-1);
       PATSYM_DEFAULT = 0;
       PATSYM_DENSE1 = 1;
       PATSYM_DENSE2 = 2;
       PATSYM_DENSE3 = 3;
       PATSYM_DENSE4 = 4;
       PATSYM_DENSE5 = 5;
       PATSYM_DENSE6 = 6;
       PATSYM_DENSE7 = 7;
       PATSYM_DENSE8 = 8;
       PATSYM_VERT = 9;
       PATSYM_HORIZ = 10;
       PATSYM_DIAG1 = 11;
       PATSYM_DIAG2 = 12;
       PATSYM_DIAG3 = 13;
       PATSYM_DIAG4 = 14;
       PATSYM_NOSHADE = 15;
       PATSYM_SOLID = 16;
       PATSYM_HALFTONE = 17;
       PATSYM_HATCH = 18;
       PATSYM_DIAGHATCH = 19;
       PATSYM_BLANK = 64;
       LCID_ERROR = (-1);
       LCID_DEFAULT = 0;

       AM_ERROR = (-1);
       AM_PRESERVE = 0;
       AM_NOPRESERVE = 1;
       FM_ERROR = (-1);
       FM_DEFAULT = 0;
       FM_OR = 1;
       FM_OVERPAINT = 2;
       FM_LEAVEALONE = 5;
       FM_XOR = 4;
       FM_AND = 6;
       FM_SUBTRACT = 7;
       FM_MASKSRCNOT = 8;
       FM_ZERO = 9;
       FM_NOTMERGESRC = 10;
       FM_NOTXORSRC = 11;
       FM_INVERT = 12;
       FM_MERGESRCNOT = 13;
       FM_NOTCOPYSRC = 14;
       FM_MERGENOTSRC = 15;
       FM_NOTMASKSRC = 16;
       FM_ONE = 17;
       BM_ERROR = (-1);
       BM_DEFAULT = 0;
       BM_OR = 1;
       BM_OVERPAINT = 2;
       BM_LEAVEALONE = 5;
       BM_XOR = 4;
       BM_AND = 6;
       BM_SUBTRACT = 7;
       BM_MASKSRCNOT = 8;
       BM_ZERO = 9;
       BM_NOTMERGESRC = 10;
       BM_NOTXORSRC = 11;
       BM_INVERT = 12;
       BM_MERGESRCNOT = 13;
       BM_NOTCOPYSRC = 14;
       BM_MERGENOTSRC = 15;
       BM_NOTMASKSRC = 16;
       BM_ONE = 17;
       BM_SRCTRANSPARENT = 18;
       BM_DESTTRANSPARENT = 19;
       LINETYPE_ERROR = (-1);
       LINETYPE_DEFAULT = 0;
       LINETYPE_DOT = 1;
       LINETYPE_SHORTDASH = 2;
       LINETYPE_DASHDOT = 3;
       LINETYPE_DOUBLEDOT = 4;
       LINETYPE_LONGDASH = 5;
       LINETYPE_DASHDOUBLEDOT = 6;
       LINETYPE_SOLID = 7;
       LINETYPE_INVISIBLE = 8;
       LINETYPE_ALTERNATE = 9;
       LINEWIDTH_ERROR = (-1);
       LINEWIDTH_DEFAULT = 0;
       LINEWIDTH_NORMAL = $00010000;
       LINEWIDTH_THICK = $00020000;
       LINEWIDTHGEOM_ERROR = (-1);
       LINEEND_ERROR = (-1);
       LINEEND_DEFAULT = 0;
       LINEEND_FLAT = 1;
       LINEEND_SQUARE = 2;
       LINEEND_ROUND = 3;
       LINEJOIN_ERROR = (-1);
       LINEJOIN_DEFAULT = 0;
       LINEJOIN_BEVEL = 1;
       LINEJOIN_ROUND = 2;
       LINEJOIN_MITRE = 3;
       CHDIRN_ERROR = (-1);
       CHDIRN_DEFAULT = 0;
       CHDIRN_LEFTRIGHT = 1;
       CHDIRN_TOPBOTTOM = 2;
       CHDIRN_RIGHTLEFT = 3;
       CHDIRN_BOTTOMTOP = 4;
       TA_NORMAL_HORIZ = $0001;
       TA_LEFT = $0002;
       TA_CENTER = $0003;
       TA_RIGHT = $0004;
       TA_STANDARD_HORIZ = $0005;
       TA_NORMAL_VERT = $0100;
       TA_TOP = $0200;
       TA_HALF = $0300;
       TA_BASE = $0400;
       TA_BOTTOM = $0500;
       TA_STANDARD_VERT = $0600;
       CM_ERROR = (-1);
       CM_DEFAULT = 0;
       CM_MODE1 = 1;
       CM_MODE2 = 2;
       CM_MODE3 = 3;
       MARKSYM_ERROR = (-1);
       MARKSYM_DEFAULT = 0;
       MARKSYM_CROSS = 1;
       MARKSYM_PLUS = 2;
       MARKSYM_DIAMOND = 3;
       MARKSYM_SQUARE = 4;
       MARKSYM_SIXPOINTSTAR = 5;
       MARKSYM_EIGHTPOINTSTAR = 6;
       MARKSYM_SOLIDDIAMOND = 7;
       MARKSYM_SOLIDSQUARE = 8;
       MARKSYM_DOT = 9;
       MARKSYM_SMALLCIRCLE = 10;
       MARKSYM_BLANK = 64;
       CHS_OPAQUE = $0001;
       CHS_VECTOR = $0002;
       CHS_LEAVEPOS = $0008;
       CHS_CLIP = $0010;
       CHS_UNDERSCORE = $0200;
       CHS_STRIKEOUT = $0400;
       PRIM_LINE = 1;
       PRIM_CHAR = 2;
       PRIM_MARKER = 3;
       PRIM_AREA = 4;
       PRIM_IMAGE = 5;
       LBB_COLOR = $0001;
       LBB_BACK_COLOR = $0002;
       LBB_MIX_MODE = $0004;
       LBB_BACK_MIX_MODE = $0008;
       LBB_WIDTH = $0010;
       LBB_GEOM_WIDTH = $0020;
       LBB_TYPE = $0040;
       LBB_END = $0080;
       LBB_JOIN = $0100;
       CBB_COLOR = $0001;
       CBB_BACK_COLOR = $0002;
       CBB_MIX_MODE = $0004;
       CBB_BACK_MIX_MODE = $0008;
       CBB_SET = $0010;
       CBB_MODE = $0020;
       CBB_BOX = $0040;
       CBB_ANGLE = $0080;
       CBB_SHEAR = $0100;
       CBB_DIRECTION = $0200;
       CBB_TEXT_ALIGN = $0400;
       CBB_EXTRA = $0800;
       CBB_BREAK_EXTRA = $1000;
       MBB_COLOR = $0001;
       MBB_BACK_COLOR = $0002;
       MBB_MIX_MODE = $0004;
       MBB_BACK_MIX_MODE = $0008;
       MBB_SET = $0010;
       MBB_SYMBOL = $0020;
       MBB_BOX = $0040;
       ABB_COLOR = $0001;
       ABB_BACK_COLOR = $0002;
       ABB_MIX_MODE = $0004;
       ABB_BACK_MIX_MODE = $0008;
       ABB_SET = $0010;
       ABB_SYMBOL = $0020;
       ABB_REF_POINT = $0040;
       IBB_COLOR = $0001;
       IBB_BACK_COLOR = $0002;
       IBB_MIX_MODE = $0004;
       IBB_BACK_MIX_MODE = $0008;

       TXTBOX_TOPLEFT = 0;
       TXTBOX_BOTTOMLEFT = 1;
       TXTBOX_TOPRIGHT = 2;
       TXTBOX_BOTTOMRIGHT = 3;
       TXTBOX_CONCAT = 4;
       TXTBOX_COUNT = 5;
       PVIS_ERROR = 0;
       PVIS_INVISIBLE = 1;
       PVIS_VISIBLE = 2;
       RVIS_ERROR = 0;
       RVIS_INVISIBLE = 1;
       RVIS_PARTIAL = 2;
       RVIS_VISIBLE = 3;

       FONT_DEFAULT = 1;
       FONT_MATCH = 2;
       LCIDT_FONT = 6;
       LCIDT_BITMAP = 7;
       LCID_ALL = (-1);

       FWEIGHT_DONT_CARE = 0;
       FWEIGHT_ULTRA_LIGHT = 1;
       FWEIGHT_EXTRA_LIGHT = 2;
       FWEIGHT_LIGHT = 3;
       FWEIGHT_SEMI_LIGHT = 4;
       FWEIGHT_NORMAL = 5;
       FWEIGHT_SEMI_BOLD = 6;
       FWEIGHT_BOLD = 7;
       FWEIGHT_EXTRA_BOLD = 8;
       FWEIGHT_ULTRA_BOLD = 9;
       FWIDTH_DONT_CARE = 0;
       FWIDTH_ULTRA_CONDENSED = 1;
       FWIDTH_EXTRA_CONDENSED = 2;
       FWIDTH_CONDENSED = 3;
       FWIDTH_SEMI_CONDENSED = 4;
       FWIDTH_NORMAL = 5;
       FWIDTH_SEMI_EXPANDED = 6;
       FWIDTH_EXPANDED = 7;
       FWIDTH_EXTRA_EXPANDED = 8;
       FWIDTH_ULTRA_EXPANDED = 9;
       FTYPE_ITALIC = $0001;
       FTYPE_ITALIC_DONT_CARE = $0002;
       FTYPE_OBLIQUE = $0004;
       FTYPE_OBLIQUE_DONT_CARE = $0008;
       FTYPE_ROUNDED = $0010;
       FTYPE_ROUNDED_DONT_CARE = $0020;
       QFA_PUBLIC = 1;
       QFA_PRIVATE = 2;
       QFA_ERROR = GPI_ALTERROR;
       QF_PUBLIC = $0001;
       QF_PRIVATE = $0002;
       QF_NO_GENERIC = $0004;
       QF_NO_DEVICE = $0008;

       ROP_SRCCOPY = $00CC;
       ROP_SRCPAINT = $00EE;
       ROP_SRCAND = $0088;
       ROP_SRCINVERT = $0066;
       ROP_SRCERASE = $0044;
       ROP_NOTSRCCOPY = $0033;
       ROP_NOTSRCERASE = $0011;
       ROP_MERGECOPY = $00C0;
       ROP_MERGEPAINT = $00BB;
       ROP_PATCOPY = $00F0;
       ROP_PATPAINT = $00FB;
       ROP_PATINVERT = $005A;
       ROP_DSTINVERT = $0055;
       ROP_ZERO = $0000;
       ROP_ONE = $00FF;
       BBO_OR = 0;
       BBO_AND = 1;
       BBO_IGNORE = 2;
       BBO_PAL_COLORS = 4;
       BBO_NO_COLOR_INFO = 8;
       FF_BOUNDARY = 0;
       FF_SURFACE = 1;
       HBM_ERROR = -1;

       {Bitmaps}
       CBM_INIT = $0004;
       BMB_ERROR = (-1);

       {Regions}                                                                                                                                          
       CRGN_OR = 1;
       CRGN_COPY = 2;
       CRGN_XOR = 4;
       CRGN_AND = 6;
       CRGN_DIFF = 7;
       RECTDIR_LFRT_TOPBOT = 1;
       RECTDIR_RTLF_TOPBOT = 2;
       RECTDIR_LFRT_BOTTOP = 3;
       RECTDIR_RTLF_BOTTOP = 4;
       RGN_ERROR = 0;
       RGN_NULL = 1;
       RGN_RECT = 2;
       RGN_COMPLEX = 3;
       PRGN_ERROR = 0;
       PRGN_OUTSIDE = 1;
       PRGN_INSIDE = 2;
       RRGN_ERROR = 0;
       RRGN_OUTSIDE = 1;
       RRGN_PARTIAL = 2;
       RRGN_INSIDE = 3;
       EQRGN_ERROR = 0;
       EQRGN_NOTEQUAL = 1;
       EQRGN_EQUAL = 2;
       HRGN_ERROR = -1;
       
       {Metafiles}
       PMF_SEGBASE = 0;
       PMF_LOADTYPE = 1;
       PMF_RESOLVE = 2;
       PMF_LCIDS = 3;
       PMF_RESET = 4;
       PMF_SUPPRESS = 5;
       PMF_COLORTABLES = 6;
       PMF_COLORREALIZABLE = 7;
       PMF_DEFAULTS = 8;
       PMF_DELETEOBJECTS = 9;
       RS_DEFAULT = 0;
       RS_NODISCARD = 1;
       LC_DEFAULT = 0;
       LC_NOLOAD = 1;
       LC_LOADDISC = 3;
       LT_DEFAULT = 0;
       LT_NOMODIFY = 1;
       LT_ORIGINALVIEW = 4;
       RES_DEFAULT = 0;
       RES_NORESET = 1;
       RES_RESET = 2;
       SUP_DEFAULT = 0;
       SUP_NOSUPPRESS = 1;
       SUP_SUPPRESS = 2;
       CTAB_DEFAULT = 0;
       CTAB_NOMODIFY = 1;
       CTAB_REPLACE = 3;
       CTAB_REPLACEPALETTE = 4;
       CREA_DEFAULT = 0;
       CREA_REALIZE = 1;
       CREA_NOREALIZE = 2;
       CREA_DOREALIZE = 3;
       DDEF_DEFAULT = 0;
       DDEF_IGNORE = 1;
       DDEF_LOADDISC = 3;
       DOBJ_DEFAULT = 0;
       DOBJ_NODELETE = 1;
       DOBJ_DELETE = 2;
       RSP_DEFAULT = 0;
       RSP_NODISCARD = 1;
       
       {Polygons}
       POLYGON_NOBOUNDARY = 0;
       POLYGON_BOUNDARY = $0001;
       POLYGON_ALTERNATE = 0;
       POLYGON_WINDING = $0002;
       POLYGON_EXCL = 0;
       POLYGON_INCL = $0008;
       
    type
       SIZEL = record
          cx : longint;
          cy : longint;
       end;             
       PSIZEL = ^SIZEL;

       MATRIXLF = record
          fxM11 : longint;
          fxM12 : longint;
          lM13 : longint;
          fxM21 : longint;
          fxM22 : longint;
          lM23 : longint;
          lM31 : longint;
          lM32 : longint;
          lM33 : longint;
       end;

       PMATRIXLF = ^MATRIXLF;

       ARCPARAMS = record
          lP : longint;
          lQ : longint;
          lR : longint;
          lS : longint;
       end;

       PARCPARAMS = ^ARCPARAMS;

       SIZEF = record
          cx : longint;
          cy : longint;
       end;

       PSIZEF = ^SIZEF;

       GRADIENTL = record
          x : longint;
          y : longint;
       end;

       PGRADIENTL = ^GRADIENTL;

       LINEBUNDLE = record
          lColor : longint;
          lBackColor : longint;
          usMixMode : word;
          usBackMixMode : word;
          fxWidth : longint;
          lGeomWidth : longint;
          usType : word;
          usEnd : word;
          usJoin : word;
          usReserved : word;
       end;

       PLINEBUNDLE = ^LINEBUNDLE;

       CHARBUNDLE = record
          lColor : longint;
          lBackColor : longint;
          usMixMode : word;
          usBackMixMode : word;
          usSet : word;
          usPrecision : word;
          sizfxCell : SIZEF;
          ptlAngle : POINTL;
          ptlShear : POINTL;
          usDirection : word;
          usTextAlign : word;
          fxExtra : longint;
          fxBreakExtra : longint;
       end;

       PCHARBUNDLE = ^CHARBUNDLE;

       MARKERBUNDLE = record
          lColor : longint;
          lBackColor : longint;
          usMixMode : word;
          usBackMixMode : word;
          usSet : word;
          usSymbol : word;
          sizfxCell : SIZEF;
       end;

       PMARKERBUNDLE = ^MARKERBUNDLE;

       AREABUNDLE = record
          lColor : longint;
          lBackColor : longint;
          usMixMode : word;
          usBackMixMode : word;
          usSet : word;
          usSymbol : word;
          ptlRefPoint : POINTL;
       end;

       PAREABUNDLE = ^AREABUNDLE;

       IMAGEBUNDLE = record
          lColor : longint;
          lBackColor : longint;
          usMixMode : word;
          usBackMixMode : word;
       end;

       PIMAGEBUNDLE = ^IMAGEBUNDLE;

       KERNINGPAIRS = record
          sFirstChar : integer;
          sSecondChar : integer;
          lKerningAmount : longint;
       end;

       PKERNINGPAIRS = ^KERNINGPAIRS;

       FACENAMEDESC = record
          usSize : word;
          usWeightClass : word;
          usWidthClass : word;
          usReserved : word;
          flOptions : cardinal;
       end;

       PFACENAMEDESC = ^FACENAMEDESC;

       FFDESCS = array[0..1,0..FACESIZE-1] of char;
    
       PFFDESCS = ^FFDESCS;

       FFDESCS2 = record
          cbLength : cardinal;
          cbFacenameOffset : cardinal;
          abFamilyName : array[0..1-1] of BYTE;
       end;

       PFFDESCS2 = ^FFDESCS2;

       RGNRECT = record
          ircStart : cardinal;
          crc : cardinal;
          crcReturned : cardinal;
          ulDirection : cardinal;
       end;

       PRGNRECT = ^RGNRECT;
       
          POLYGON = record
          ulPoints : cardinal;
          aPointl : PPOINTL;
       end;

       PPOLYGON = ^POLYGON;

       POLYSET = record
          ulPolys : cardinal;
          aPolygon : array[0..1-1] of POLYGON;
       end;

       PPOLYSET = ^POLYSET;
       
    function GpiCreatePS(hab,hdc : cardinal;psizlSize : PSIZEL;flOptions : cardinal) : cardinal;cdecl;          
    function GpiDestroyPS(hps : cardinal) : longbool;cdecl;
    function GpiAssociate(hps,hdc : cardinal) : longbool;cdecl;
    function GpiRestorePS(hps : cardinal;lPSid : longint) : longbool;cdecl;
    function GpiSavePS(hps : cardinal) : longint;cdecl;                
    function GpiErase(hps : cardinal) : longbool;cdecl;                 
    function GpiQueryDevice(hps : cardinal) : cardinal;cdecl;                
    function GpiResetPS(hps,flOptions : cardinal) : longbool;cdecl; 
    function GpiSetPS(hps : cardinal;psizlsize : PSIZEL;flOptions : cardinal) : longbool;cdecl;      
    function GpiQueryPS(hps : cardinal;psizlSize : PSIZEL) : cardinal;cdecl;                 
    function GpiErrorSegmentData(hps : cardinal;plSegment,plContext : plongint) : longint; cdecl;
    function GpiQueryDrawControl(hps : cardinal;lControl : longint) : longint;cdecl;                     
    function GpiSetDrawControl(hps : cardinal;lControl,lValue : longint) : longbool;cdecl;         
    function GpiQueryDrawingMode(hps : cardinal) : longint;cdecl;                                     
    function GpiSetDrawingMode(hps : cardinal;lMode : longint) : longbool;cdecl;
    function GpiQueryStopDraw(hps : cardinal) : longint;cdecl;              
    function GpiSetStopDraw(hps : cardinal;lValue : longint) : longbool;cdecl;                                      
    function GpiCorrelateChain(hps : cardinal;lType : longint;pptlPick : PPOINTL;lMaxHits,lMaxDepth : longint;pl2 : plongint) : longint;cdecl;     
    function GpiQueryTag(hps : cardinal;plTag : plongint) : longbool;cdecl;             
    function GpiSetTag(hps : cardinal;lTag : longint) : longbool;cdecl;                 
    function GpiQueryPickApertureSize(hps : cardinal;psizlSize : PSIZEL) : longbool; cdecl;                       
    function GpiSetPickApertureSize(hps : cardinal;lOptions : longint;psizlSize : PSIZEL) : longbool; cdecl;         
    function GpiQueryPickAperturePosition(hps : cardinal;pptlPoint : PPOINTL) : longbool; cdecl;                  
    function GpiSetPickAperturePosition(hps : cardinal;pptlPick : PPOINTL) : longbool; cdecl;                     
    function GpiQueryBoundaryData(hps : cardinal;prclBoundary : PRECTL) : longbool; cdecl;                        
    function GpiResetBoundaryData(hps : cardinal) : longbool; cdecl;                                              
    function GpiCorrelateFrom(hps : cardinal;lFirstSegment,lLastSegment,lType : longint;pptlPick : PPOINTL;lMaxHits,lMaxDepth : longint;plSegTag : plongint) : longint; cdecl;                
    function GpiCorrelateSegment(hps : cardinal;lSegment,lType : longint;pptlPick : PPOINTL;lMaxHits,lMaxDepth : longint;alSegTag : plongint) : longint; cdecl;                             
    function GpiOpenSegment(hps : cardinal;lSegment : longint) : longbool; cdecl;     
    function GpiCloseSegment(hps : cardinal) : longbool; cdecl;                    
    function GpiDeleteSegment(hps : cardinal;lSegid : longint) : longbool; cdecl;     
    function GpiQueryInitialSegmentAttrs(hps : cardinal;lAttribute : longint) : longint; cdecl;      
    function GpiSetInitialSegmentAttrs(hps : cardinal;lAttribute,lValue : longint) : longbool; cdecl;          
    function GpiQuerySegmentAttrs(hps : cardinal;lSegid,lAttribute : longint) : longint; cdecl;               
    function GpiSetSegmentAttrs(hps : cardinal;lSegid,lAttribute,lValue : longint) : longbool; cdecl;   
    function GpiQuerySegmentPriority(hps : cardinal;lRefSegid,lOrder : longint) : longint; cdecl;             
    function GpiSetSegmentPriority(hps : cardinal;lSegid,lRefSegid,lOrder : longint) : longbool; cdecl; 
    function GpiDeleteSegments(hps : cardinal;lFirstSegment,lLastSegment : longint) : longbool; cdecl;         
    function GpiQuerySegmentNames(hps : cardinal;lFirstSegid,lLastSegid,lMax : longint;alSegids : plongint) : longint; cdecl;        
    function GpiGetData(hps : cardinal;lSegid : longint;plOffset : plongint;lFormat,lLength : longint;pbData : PBYTE) : longint; cdecl;        
    function GpiPutData(hps : cardinal;lFormat : longint;plCount : plongint;pbData : PBYTE) : longint; cdecl;  
    function GpiDrawChain(hps : cardinal) : longbool; cdecl; 
    function GpiDrawFrom(hps : cardinal;lFirstSegment,lLastSegment : longint) : longbool; cdecl;
    function GpiDrawSegment(hps : cardinal;lSegment : longint) : longbool; cdecl;                      
    function GpiDrawDynamics(hps : cardinal) : longbool; cdecl;                                     
    function GpiRemoveDynamics(hps : cardinal;lFirstSegid,lLastSegid : longint) : longbool; cdecl;
    function GpiBeginElement(hps : cardinal;lType : longint;pszDesc : pchar) : longbool; cdecl;  
    function GpiEndElement(hps : cardinal) : longbool; cdecl;                               
    function GpiLabel(hps : cardinal;lLabel : longint) : longbool; cdecl;                      
    function GpiElement(hps : cardinal;lType : longint;pszDesc : pchar;lLength : longint;pbData : PBYTE) : longint; cdecl;  
    function GpiQueryElement(hps : cardinal;lOff,lMaxLength : longint;pbData : PBYTE) : longint; cdecl;         
    function GpiDeleteElement(hps : cardinal) : longbool; cdecl;                                                     
    function GpiDeleteElementRange(hps : cardinal;lFirstElement,lLastElement : longint) : longbool; cdecl;       
    function GpiDeleteElementsBetweenLabels(hps : cardinal;lFirstLabel,lLastLabel : longint) : longbool; cdecl;  
    function GpiQueryEditMode(hps : cardinal) : longint; cdecl;                                                    
    function GpiSetEditMode(hps : cardinal;lMode : longint) : longbool; cdecl;                                         
    function GpiQueryElementPointer(hps : cardinal) : longint; cdecl;                                              
    function GpiSetElementPointer(hps : cardinal;lElement : longint) : longbool; cdecl;                                
    function GpiOffsetElementPointer(hps : cardinal;loffset : longint) : longbool; cdecl;                              
    function GpiQueryElementType(hps : cardinal;plType : plongint;lLength : longint;pszData : pchar) : longint; cdecl;
    function GpiSetElementPointerAtLabel(hps : cardinal;lLabel : longint) : longbool; cdecl;
    function GpiQuerySegmentTransformMatrix(hps : cardinal;lSegid,lCount : longint;pmatlfArray : PMATRIXLF) : longbool; cdecl;  
    function GpiSetSegmentTransformMatrix(hps : cardinal;lSegid,lCount : longint;pmatlfarray : PMATRIXLF;lOptions : longint) : longbool; cdecl;        
    function GpiConvert(hps : cardinal;lSrc,lTarg,lCount : longint;aptlPoints : PPOINTL) : longbool; cdecl;                                  
    function GpiConvertWithMatrix(hps : cardinal;lCountp : longint;aptlPoints : PPOINTL;lCount : longint;pmatlfArray : PMATRIXLF) : longbool; cdecl;          
    function GpiQueryModelTransformMatrix(hps : cardinal;lCount : longint;pmatlfArray : PMATRIXLF) : longbool; cdecl;                                      
    function GpiSetModelTransformMatrix(hps : cardinal;lCount : longint;pmatlfArray : PMATRIXLF;lOptions : longint) : longbool; cdecl;                        
    function GpiCallSegmentMatrix(hps : cardinal;lSegment,lCount : longint;pmatlfArray : PMATRIXLF;lOptions : longint) : longint; cdecl;              
    function GpiQueryDefaultViewMatrix(hps : cardinal;lCount : longint;pmatlfArray : PMATRIXLF) : longbool; cdecl;                                         
    function GpiSetDefaultViewMatrix(hps : cardinal;lCount : longint;pmatlfarray : PMATRIXLF;lOptions : longint) : longbool; cdecl;                           
    function GpiQueryPageViewport(hps : cardinal;prclViewport : PRECTL) : longbool; cdecl;
    function GpiSetPageViewport(hps : cardinal;prclViewport : PRECTL) : longbool; cdecl;  
    function GpiQueryViewingTransformMatrix(hps : cardinal;lCount : longint;pmatlfArray : PMATRIXLF) : longbool; cdecl; 
    function GpiSetViewingTransformMatrix(hps : cardinal;lCount : longint;pmatlfArray : PMATRIXLF;lOptions : longint) : longbool; cdecl;   
    function GpiTranslate(hps : cardinal;pmatrixlf : PMATRIXLF;long : longint;ppointl : PPOINTL) : longbool; cdecl;                     
    function GpiScale(hps : cardinal;p1 : PMATRIXLF;p2 : longint;p3 : plongint;p4 : PPOINTL) : longbool; cdecl;                           
    function GpiRotate(p1 : cardinal;p2 : PMATRIXLF;p3,p4 : longint;p5 : PPOINTL) : longbool; cdecl;                            
    function GpiSetGraphicsField(hps : cardinal;prclField : PRECTL) : longbool; cdecl;                                               
    function GpiQueryGraphicsField(hps : cardinal;prclField : PRECTL) : longbool; cdecl;                                             
    function GpiSetViewingLimits(hps : cardinal;prclLimits : PRECTL) : longbool; cdecl;                                              
    function GpiQueryViewingLimits(hps : cardinal;prclLimits : PRECTL) : longbool; cdecl;                                            
    function GpiBeginPath(hps : cardinal;lPath : longint) : longbool; cdecl;
    function GpiEndPath(hps : cardinal) : longbool; cdecl;               
    function GpiCloseFigure(hps : cardinal) : longbool; cdecl;           
    function GpiModifyPath(hps : cardinal;lPath,lMode : longint) : longbool; cdecl; 
    function GpiFillPath(hps : cardinal;lPath,lOptions : longint) : longint; cdecl;
    function GpiSetClipPath(hps : cardinal;lPath,lOptions : longint) : longbool; cdecl; 
    function GpiOutlinePath(hps : cardinal;lPath,lOptions : longint) : longint; cdecl; 
    function GpiPathToRegion(GpiH : cardinal;lPath,lOptions : longint) : cardinal; cdecl;
    function GpiStrokePath(hps : cardinal;lPath : longint;flOptions : cardinal) : longint; cdecl; 
    function GpiCreateLogColorTable(hps,flOptions : cardinal;lFormat,lStart,lCount : longint;alTable : plongint) : longbool; cdecl; 
    function GpiQueryColorData(hps : cardinal;lCount : longint;alArray : plongint) : longbool; cdecl;                                                     
    function GpiQueryLogColorTable(hps,flOptions : cardinal;lStart,lCount : longint;alArray : plongint) : longint; cdecl;                 
    function GpiQueryRealColors(hps,flOptions : cardinal;lStart,lCount : longint;alColors : plongint) : longint; cdecl;                   
    function GpiQueryNearestColor(hps,flOptions : cardinal;lRgbIn : longint) : longint; cdecl;                                                
    function GpiQueryColorIndex(hps,flOptions : cardinal;lRgbColor : longint) : longint; cdecl;                                               
    function GpiQueryRGBColor(hps,flOptions : cardinal;lColorIndex : longint) : longint; cdecl;                                               
    function GpiCreatePalette(hab,flOptions,ulFormat,ulCount : cardinal;aulTable : pcardinal) : cardinal; cdecl;      
    function GpiDeletePalette(hpal : cardinal) : longbool; cdecl;                                                                         
    function GpiSelectPalette(hps,hpal : cardinal) : cardinal; cdecl;                                                               
    function GpiAnimatePalette(hpal,ulFormat,ulStart,ulCount : cardinal;aulTable : pcardinal) : longint; cdecl;     
    function GpiSetPaletteEntries(hpal,ulFormat,ulStart,ulCount : cardinal;aulTable : pcardinal) : longbool; cdecl;  
    function GpiQueryPalette(hps : cardinal) : cardinal; cdecl;        
    function GpiQueryPaletteInfo(hpal,hps,flOptions,ulStart,ulCount : cardinal;aulArray : pcardinal) : longint; cdecl;
    function GpiSetColor(hps : cardinal;lColor : longint) : longbool; cdecl;  
    function GpiQueryColor(hps : cardinal) : longint; cdecl;              
    function GpiBox(hps : cardinal;lControl : longint;pptlPoint : PPOINTL;lHRound,lVRound : longint) : longint; cdecl;
    function GpiMove(hps : cardinal;pptlPoint : PPOINTL) : longbool; cdecl;                                             
    function GpiLine(hps : cardinal;pptlEndPoint : PPOINTL) : longint; cdecl;                                          
    function GpiPolyLine(hps : cardinal;lCount : longint;aptlPoints : PPOINTL) : longint; cdecl;                          
    function GpiPolyLineDisjoint(hps : cardinal;lCount : longint;aptlPoints : PPOINTL) : longint; cdecl;                  
    function GpiSetPattern(hps : cardinal;lPatternSymbol : longint) : longbool; cdecl;                                     
    function GpiQueryPattern(hps : cardinal) : longint;  cdecl;                                                        
    function GpiBeginArea(hps,flOptions : cardinal) : longbool; cdecl;                                          
    function GpiEndArea(hps : cardinal) : longint; cdecl;                                                              
    function GpiCharString(hps : cardinal;lCount : longint;pchString : pshortint) : longint; cdecl;                             
    function GpiCharStringAt(hps : cardinal;pptlPoint : PPOINTL;lCount : longint;pchString : pshortint) : longint; cdecl;      
    function GpiSetAttrMode(hps : cardinal;lMode : longint) : longbool; cdecl; 
    function GpiQueryAttrMode(hps : cardinal) : longint; cdecl;            
    function GpiSetAttrs(hps : cardinal;lPrimType : longint;flAttrMask,flDefMask : cardinal;ppbunAttrs : pointer) : longbool; cdecl;
    function GpiQueryAttrs(hps : cardinal;lPrimType : longint;flAttrMask : cardinal;ppbunAttrs : pointer) : longint; cdecl;                
    function GpiSetBackColor(hps : cardinal;lColor : longint) : longbool; cdecl;                                                         
    function GpiQueryBackColor(hps : cardinal) : longint; cdecl;                                                                     
    function GpiSetMix(hps : cardinal;lMixMode : longint) : longbool; cdecl;                                                             
    function GpiQueryMix(hps : cardinal) : longint; cdecl;                                                                           
    function GpiSetBackMix(hps : cardinal;lMixMode : longint) : longbool; cdecl;  
    
    function GpiQueryBackMix(hps : cardinal) : longint; cdecl;                
    function GpiSetLineType(hps : cardinal;lLineType : longint) : longbool; cdecl; 
    function GpiQueryLineType(hps : cardinal) : longint; cdecl;                
    function GpiSetLineWidth(hps : cardinal;fxLineWidth : longint) : longbool; cdecl;
    function GpiQueryLineWidth(hps : cardinal) : longint; cdecl;                 
    function GpiSetLineWidthGeom(hps : cardinal;lLineWidth : longint) : longbool; cdecl; 
    function GpiQueryLineWidthGeom(hps : cardinal) : longint; cdecl;                 
    function GpiSetLineEnd(hps : cardinal;lLineEnd : longint) : longbool; cdecl;         
    function GpiQueryLineEnd(hps : cardinal) : longint; cdecl;                       
    function GpiSetLineJoin(hps : cardinal;lLineJoin : longint) : longbool; cdecl;       
    function GpiQueryLineJoin(hps : cardinal) : longint; cdecl;                      
    function GpiSetCurrentPosition(hps : cardinal;pptlPoint : PPOINTL) : longbool; cdecl; 
    function GpiQueryCurrentPosition(hps : cardinal;pptlPoint : PPOINTL) : longbool; cdecl;
    function GpiSetArcParams(hps : cardinal;parcpArcParams : PARCPARAMS) : longbool; cdecl;
    function GpiQueryArcParams(hps : cardinal;parcpArcParams : PARCPARAMS) : longbool; cdecl; 
    function GpiPointArc(hps : cardinal;pptl2 : PPOINTL) : longint; cdecl;                   
    function GpiFullArc(hps : cardinal;lControl,fxMultiplier : longint) : longint; cdecl;  
    function GpiPartialArc(hps : cardinal;pptlCenter : PPOINTL;fxMultiplier,fxStartAngle,fxSweepAngle : longint) : longint; cdecl;
    function GpiPolyFillet(hps : cardinal;lCount : longint;aptlPoints : PPOINTL) : longint; cdecl;                                                 
    function GpiPolySpline(hps : cardinal;lCount : longint;aptlPoints : PPOINTL) : longint; cdecl;                                                 
    function GpiPolyFilletSharp(hps : cardinal;lCount : longint;aptlPoints : PPOINTL;afxPoints : plongint) : longint; cdecl;                         
    function GpiSetPatternSet(hps : cardinal;lSet : longint) : longbool; cdecl;   
    function GpiQueryPatternSet(hps : cardinal) : longint; cdecl;             
    function GpiSetPatternRefPoint(hps : cardinal;pptlRefPoint : PPOINTL) : longbool; cdecl;   
    function GpiQueryPatternRefPoint(hps : cardinal;pptlRefPoint : PPOINTL) : longbool; cdecl; 
    function GpiQueryCharStringPos(hps,flOptions : cardinal;lCount : longint;pchString : pshortint;alXincrements : plongint;aptlPositions : PPOINTL) : longbool; cdecl;     
    function GpiQueryCharStringPosAt(hps : cardinal;pptlStart : PPOINTL;flOptions : cardinal;lCount : longint;pchString : pshortint;alXincrements : plongint;aptlPositions : PPOINTL) : longbool; cdecl; 
    function GpiQueryTextBox(hps : cardinal;lCount1 : longint;pchString : pshortint;lCount2 : longint;aptlPoints : PPOINTL) : longbool; cdecl;                                                        
    function GpiQueryDefCharBox(hps : cardinal;psizlSize : PSIZEL) : longbool; cdecl;                                                                                                     
    function GpiSetCharSet(hps : cardinal;llcid : longint) : longbool; cdecl;                                                                                                                
    function GpiQueryCharSet(hps : cardinal) : longint; cdecl;                                    
    function GpiSetCharBox(hps : cardinal;psizfxBox : PSIZEF) : longbool; cdecl;                   
    function GpiQueryCharBox(hps : cardinal;psizfxSize : PSIZEF) : longbool; cdecl;                
    function GpiSetCharAngle(hps : cardinal;pgradlAngle : PGRADIENTL) : longbool; cdecl;           
    function GpiQueryCharAngle(hps : cardinal;pgradlAngle : PGRADIENTL) : longbool; cdecl;         
    function GpiSetCharShear(hps : cardinal;pptlAngle : PPOINTL) : longbool; cdecl;                
    function GpiQueryCharShear(hps : cardinal;pptlShear : PPOINTL) : longbool; cdecl;              
    function GpiSetCharDirection(hps : cardinal;lDirection : longint) : longbool; cdecl;              
    function GpiQueryCharDirection(hps : cardinal) : longint; cdecl;                              
    function GpiSetCharMode(hps : cardinal;lMode : longint) : longbool; cdecl;                        
    function GpiQueryCharMode(hps : cardinal) : longint; cdecl;                                   
    function GpiSetTextAlignment(hps : cardinal;lHoriz,lVert : longint) : longbool; cdecl;     
    function GpiQueryTextAlignment(hps : cardinal;plHoriz,plVert : plongint) : longbool; cdecl; 
    function GpiCharStringPos(hps : cardinal;prclRect : PRECTL;flOptions : cardinal;lCount : longint;pchString : pshortint;alAdx : plongint) : longint; cdecl;      
    function GpiCharStringPosAt(hps : cardinal;pptlStart : PPOINTL;prclRect : PRECTL;flOptions : cardinal;lCount : longint;pchString : pshortint;alAdx : plongint) : longint; cdecl;       
    function GpiSetCharExtra(hps : cardinal;Extra : longint) : longbool;  cdecl;                 
    function GpiSetCharBreakExtra(hps : cardinal;BreakExtra : longint) : longbool; cdecl;        
    function GpiQueryCharExtra(hps : cardinal;Extra : plongint) : longbool; cdecl;               
    function GpiQueryCharBreakExtra(hps : cardinal;BreakExtra : plongint) : longbool; cdecl;     
    function GpiMarker(hps : cardinal;pptlPoint : PPOINTL) : longint; cdecl;                  
    function GpiPolyMarker(hps : cardinal;lCount : longint;aptlPoints : PPOINTL) : longint; cdecl;
    function GpiSetMarker(hps : cardinal;lSymbol : longint) : longbool; cdecl;                     
    function GpiSetMarkerBox(hps : cardinal;psizfxSize : PSIZEF) : longbool; cdecl;             
    function GpiSetMarkerSet(hps : cardinal;lSet : longint) : longbool; cdecl;                     
    function GpiQueryMarker(hps : cardinal) : longint; cdecl;                                  
    function GpiQueryMarkerBox(hps : cardinal;psizfxSize : PSIZEF) : longbool; cdecl;           
    function GpiQueryMarkerSet(hps : cardinal) : longint; cdecl;                               
    function GpiImage(hps : cardinal;lFormat : longint;psizlImageSize : PSIZEL;lLength : longint;pbData : PBYTE) : longint; cdecl;     
    function GpiPop(hps : cardinal;lCount : longint) : longbool; cdecl;                                                              
    function GpiPtVisible(hps : cardinal;pptlPoint : PPOINTL) : longint; cdecl;                                                  
    function GpiRectVisible(hps : cardinal;prclRectangle : PRECTL) : longint; cdecl;                                             
    function GpiComment(hps : cardinal;lLength : longint;pbData : PBYTE) : longbool; cdecl;
    function GpiCreateLogFont(hps : cardinal;pName : PSTR8;lLcid : longint;pfatAttrs : PFATTRS) : longint; cdecl;   
    function GpiDeleteSetId(hps : cardinal;lLcid : longint) : longbool; cdecl;                                       
    function GpiLoadFonts(hab : cardinal;pszFilename : pchar) : longbool; cdecl;                                    
    function GpiUnloadFonts(hab : cardinal;pszFilename : pchar) : longbool; cdecl;                                  
    function GpiQueryFonts(hps,flOptions : cardinal;pszFacename : pchar;plReqFonts : plongint;lMetricsLength : longint;afmMetrics : PFONTMETRICS) : longint; cdecl;        
    function GpiQueryFontMetrics(hps : cardinal;lMetricsLength : longint;pfmMetrics : PFONTMETRICS) : longbool; cdecl;                                                         
    function GpiQueryKerningPairs(hps : cardinal;lCount : longint;akrnprData : PKERNINGPAIRS) : longint; cdecl;                                                               
    function GpiQueryWidthTable(hps : cardinal;lFirstChar,lCount : longint;alData : plongint) : longbool; cdecl;                                                           
    function GpiQueryNumberSetIds(hps : cardinal) : longint; cdecl;     
    function GpiQuerySetIds(hps : cardinal;lCount : longint;alTypes : plongint;aNames : PSTR8;allcids : plongint) : longbool; cdecl;  
    function GpiQueryFaceString(PS : cardinal;FamilyName : pchar;attrs : PFACENAMEDESC;length : longint;CompoundFaceName : pchar) : cardinal; cdecl;
    function GpiQueryLogicalFont(PS : cardinal;lcid : longint;name : PSTR8;attrs : PFATTRS;length : longint) : longbool; cdecl; 
    function GpiQueryFontAction(anchor,options : cardinal) : cardinal; cdecl;                                    
    function GpiLoadPublicFonts(p1 : cardinal;p2 : pchar);longbool; cdecl;                                                
    function GpiUnloadPublicFonts(p1 : cardinal;p2 : pchar) : longbool; cdecl;                                              
    function GpiSetCp(hps,ulCodePage : cardinal) : longbool;  cdecl;                                              
    function GpiQueryCp(hps : cardinal) : cardinal; cdecl;                                                               
    function GpiQueryFontFileDescriptions(hab : cardinal;pszFilename : pchar;plCount : plongint;affdescsNames : PFFDESCS) : longint;  cdecl; 
    function GpiQueryFullFontFileDescs(hab : cardinal;pszFilename : pchar;plCount : plongint;pNames : pointer;plNamesBuffLength : plongint) : longint; cdecl;  
    function GpiBitBlt(hpsTarget,hpsSource : cardinal;lCount : longint;aptlPoints : PPOINTL;lRop : longint;flOptions : cardinal) : longint; cdecl;             
    function GpiDeleteBitmap(hbm : cardinal) : longbool; cdecl;                                                                                          
    function GpiLoadBitmap(hps,Resource,idBitmap : cardinal;lWidth,lHeight : longint) : cardinal; cdecl;                            
    function GpiSetBitmap(hps,hbm : cardinal) : cardinal; cdecl; 
    function GpiWCBitBlt(hpsTarget,hbmSource : cardinal;lCount : longint;aptlPoints : PPOINTL;lRop : longint;flOptions : cardinal) : longint; cdecl;
    function GpiCreateBitmap(hps : cardinal;pbmpNew : PBITMAPINFOHEADER2;flOptions : cardinal;pbInitData : PBYTE;pbmiInfoTable : PBITMAPINFO2) : cardinal; cdecl;
    function GpiSetBitmapBits(hps : cardinal;lScanStart,lScans : longint;pbBuffer : PBYTE;pbmiInfoTable : PBITMAPINFO2) : longint; cdecl;                   
    function GpiSetBitmapDimension(hbm : cardinal;psizlBitmapDimension : PSIZEL) : longbool; cdecl;                                                          
    function GpiSetBitmapId(hps,hbm : cardinal;lLcid : longint) : longbool; cdecl;                                                                        
    function GpiQueryBitmapBits(hps : cardinal;lScanStart,lScans : longint;pbBuffer : PBYTE;pbmiInfoTable : PBITMAPINFO2) : longint; cdecl;                 
    function GpiQueryBitmapDimension(hbm : cardinal;psizlBitmapDimension : PSIZEL) : longbool; cdecl;                                                        
    function GpiQueryBitmapHandle(hps : cardinal;lLcid : longint) : cardinal;  cdecl;                                                                            
    function GpiQueryBitmapParameters(hbm : cardinal;pbmpData : PBITMAPINFOHEADER) : longbool; cdecl;                                                        
    function GpiQueryBitmapInfoHeader(hbm : cardinal;pbmpData : PBITMAPINFOHEADER2) : longbool; cdecl;                                                       
    function GpiQueryDeviceBitmapFormats(hps : cardinal;lCount : longint;alArray : plongint) : longbool; cdecl;                                                        
    function GpiSetPel(hps : cardinal;pptlPoint : PPOINTL) : longint; cdecl;                                                                                    
    function GpiQueryPel(hps : cardinal;pptlPoint : PPOINTL) : longint; cdecl;                                                                                  
    function GpiFloodFill(hps : cardinal;lOptions,lColor : longint) : longint; cdecl;                                                                       
    function GpiDrawBits(hps : cardinal;pBits : pointer;pbmiInfoTable : PBITMAPINFO2;lCount : longint;aptlPoints : PPOINTL;lRop : longint;flOptions : cardinal) : longint; cdecl; 
    function GpiCombineRegion(hps,hrgnDest,hrgnSrc1,hrgnSrc2 : cardinal;lMode : longint) : longint;  cdecl;
    function GpiCreateRegion(hps : cardinal;lCount : longint;arclRectangles : PRECTL) : cardinal;  cdecl;                        
    function GpiDestroyRegion(hps,hrgn : cardinal) : longbool;  cdecl;                                                 
    function GpiEqualRegion(hps,hrgnSrc1,hrgnSrc2 : cardinal) : longint; cdecl;                                
    function GpiOffsetRegion(hps,Hrgn : cardinal;pptlOffset : PPOINTL) : longbool; cdecl;                              
    function GpiPaintRegion(hps,hrgn : cardinal) : longint; cdecl;                                                    
    function GpiFrameRegion(hps,hrgn : cardinal;thickness : PSIZEL) : longint; cdecl;                                 
    function GpiPtInRegion(hps,hrgn : cardinal;pptlPoint : PPOINTL) : longint; cdecl;                                 
    function GpiQueryRegionBox(hps,hrgn : cardinal;prclBound : PRECTL) : longint; cdecl;                              
    function GpiQueryRegionRects(hps,hrgn : cardinal;prclBound : PRECTL;prgnrcControl : PRGNRECT;prclRect : PRECTL) : longbool; cdecl;     
    function GpiRectInRegion(hps,hrgn : cardinal;prclRect : PRECTL) : longint; cdecl;                                                     
    function GpiSetRegion(hps,hrgn : cardinal;lcount : longint;arclRectangles : PRECTL) : longbool;cdecl;  
    function GpiSetClipRegion(hps,hrgn : cardinal;phrgnOld : pcardinal) : longint; cdecl;                  
    function GpiQueryClipRegion(hps : cardinal) : cardinal;  cdecl;                                            
    function GpiQueryClipBox(hps : cardinal;prclBound : PRECTL) : longint; cdecl;                             
    function GpiExcludeClipRectangle(hps : cardinal;prclRectangle : PRECTL) : longint; cdecl;                 
    function GpiIntersectClipRectangle(hps : cardinal;prclRectangle : PRECTL) : longint; cdecl;               
    function GpiOffsetClipRegion(hps : cardinal;pptlPoint : PPOINTL) : longint; cdecl;                        
    function GpiCopyMetaFile(hmf : cardinal) : cardinal; cdecl;                       
    function GpiDeleteMetaFile(hmf : cardinal) : longbool; cdecl;                    
    function GpiLoadMetaFile(hab : cardinal;pszFilename : pchar) : cardinal; cdecl;     
    function GpiPlayMetaFile(hps,hmf : cardinal;lCount1 : longint;alOptarray,plSegCount : plongint;lCount2 : longint;pszDesc : pchar) : longint;  cdecl;  
    function GpiQueryMetaFileBits(hmf : cardinal;lOffset,lLength : longint;pbData : PBYTE) : longbool;  cdecl;                                            
    function GpiQueryMetaFileLength(hmf : cardinal) : longint;  cdecl;                                                                                       
    function GpiSaveMetaFile(hmf : cardinal;pszFilename : pchar) : longbool; cdecl;                                                                             
    function GpiSetMetaFileBits(hmf : cardinal;lOffset,lLength : longint;pbBuffer : PBYTE) : longbool; cdecl;                                             
    function GpiQueryDefArcParams(hps : cardinal;parcpArcParams : PARCPARAMS) : longbool; cdecl;                                                              
    function GpiQueryDefAttrs(hps : cardinal;lPrimType : longint;flAttrMask : cardinal;ppbunAttrs : pointer) : longbool; cdecl;                                     
    function GpiQueryDefTag(hps : cardinal;plTag : plongint) : longbool; cdecl;                                                                                  
    function GpiQueryDefViewingLimits(hps : cardinal;prclLimits : PRECTL) : longbool; cdecl;                                                                  
    function GpiSetDefArcParams(hps : cardinal;parcpArcParams : PARCPARAMS) : longbool; cdecl;                                                                
    function GpiSetDefAttrs(hps : cardinal;lPrimType : longint;flAttrMask : cardinal;ppbunAttrs : pointer) : longbool;cdecl;                                        
    function GpiSetDefTag(hps : cardinal;lTag : longint) : longbool; cdecl;                                                                                      
    function GpiSetDefViewingLimits(hps : cardinal;prclLimits : PRECTL) : longbool; cdecl;                                          
    function GpiPolygons(hps,ulCount : cardinal;paplgn : PPOLYGON;flOptions,flModel : cardinal) : longint; cdecl;

  implementation

    function GpiCreatePS(hab,hdc : cardinal;psizlSize : PSIZEL;flOptions : cardinal) : cardinal;cdecl;external;
    function GpiDestroyPS(hps : cardinal) : longbool;cdecl;external;
    function GpiAssociate(hps,hdc : cardinal) : longbool;cdecl;external;
    function GpiRestorePS(hps : cardinal;lPSid : longint) : longbool;cdecl;external;
    function GpiSavePS(hps : cardinal) : longint;cdecl;external;
    function GpiErase(hps : cardinal) : longbool;cdecl;external;
    function GpiQueryDevice(hps : cardinal) : cardinal;cdecl;external;
    function GpiResetPS(hps,flOptions : cardinal) : longbool;cdecl;external;
    function GpiSetPS(hps : cardinal;psizlsize : PSIZEL;flOptions : cardinal) : longbool;cdecl;external;
    function GpiQueryPS(hps : cardinal;psizlSize : PSIZEL) : cardinal;cdecl;external;
    function GpiErrorSegmentData(hps : cardinal;plSegment,plContext : plongint) : longint;cdecl;external;
    function GpiQueryDrawControl(hps : cardinal;lControl : longint) : longint;cdecl;external;
    function GpiSetDrawControl(hps : cardinal;lControl,lValue : longint) : longbool;cdecl;external;
    function GpiQueryDrawingMode(hps : cardinal) : longint;cdecl;external;
    function GpiSetDrawingMode(hps : cardinal;lMode : longint) : longbool;cdecl;external;
    function GpiQueryStopDraw(hps : cardinal) : longint;cdecl; external;
    function GpiSetStopDraw(hps : cardinal;lValue : longint) : longbool; cdecl; external;
    function GpiCorrelateChain(hps : cardinal;lType : longint;pptlPick : PPOINTL;lMaxHits : longint;lMaxDepth : longint;pl2 : plongint) : longint; cdecl; external;
    function GpiQueryTag(hps : cardinal;plTag : plongint) : longbool; cdecl; external;
    function GpiSetTag(hps : cardinal;lTag : longint) : longbool; cdecl; external;
    function GpiQueryPickApertureSize(hps : cardinal;psizlSize : PSIZEL) : longbool; cdecl; external;
    function GpiSetPickApertureSize(hps : cardinal;lOptions : longint;psizlSize : PSIZEL) : longbool; cdecl; external;
    function GpiQueryPickAperturePosition(hps : cardinal;pptlPoint : PPOINTL) : longbool; cdecl; external;
    function GpiSetPickAperturePosition(hps : cardinal;pptlPick : PPOINTL) : longbool; cdecl; external;
    function GpiQueryBoundaryData(hps : cardinal;prclBoundary : PRECTL) : longbool; cdecl; external;
    function GpiResetBoundaryData(hps : cardinal) : longbool; cdecl; external;
    function GpiCorrelateFrom(hps : cardinal;lFirstSegment,lLastSegment,lType : longint;pptlPick : PPOINTL;lMaxHits,lMaxDepth : longint;plSegTag : plongint) : longint; cdecl; external;
    function GpiCorrelateSegment(hps : cardinal;lSegment,lType : longint;pptlPick : PPOINTL;lMaxHits,lMaxDepth : longint;alSegTag : plongint) : longint; cdecl; external;
    function GpiOpenSegment(hps : cardinal;lSegment : longint) : longbool; cdecl; external;
    function GpiCloseSegment(hps : cardinal) : longbool; cdecl; external;
    function GpiDeleteSegment(hps : cardinal;lSegid : longint) : longbool; cdecl; external;
    function GpiQueryInitialSegmentAttrs(hps : cardinal;lAttribute : longint) : longint; cdecl; external;
    function GpiSetInitialSegmentAttrs(hps : cardinal;lAttribute,lValue : longint) : longbool; cdecl; external;
    function GpiQuerySegmentAttrs(hps : cardinal;lSegid,lAttribute : longint) : longint; cdecl; external;
    function GpiSetSegmentAttrs(hps : cardinal;lSegid,lAttribute,lValue : longint) : longbool; cdecl; external;
    function GpiQuerySegmentPriority(hps : cardinal;lRefSegid,lOrder : longint) : longint; cdecl; external;
    function GpiSetSegmentPriority(hps : cardinal;lSegid,lRefSegid,lOrder : longint) : longbool; cdecl; external;
    function GpiDeleteSegments(hps : cardinal;lFirstSegment,lLastSegment : longint) : longbool; cdecl; external;
    function GpiQuerySegmentNames(hps : cardinal;lFirstSegid,lLastSegid,lMax : longint;alSegids : plongint) : longint; cdecl; external;
    function GpiGetData(hps : cardinal;lSegid : longint;plOffset : plongint;lFormat,lLength : longint;pbData : PBYTE) : longint; cdecl; external;
    function GpiPutData(hps : cardinal;lFormat : longint;plCount : plongint;pbData : PBYTE) : longint; cdecl; external;
    function GpiDrawChain(hps : cardinal) : longbool; cdecl; external;
    function GpiDrawFrom(hps : cardinal;lFirstSegment,lLastSegment : longint) : longbool; cdecl; external;
    function GpiDrawSegment(hps : cardinal;lSegment : longint) : longbool; cdecl; external;
    function GpiDrawDynamics(hps : cardinal) : longbool; cdecl; external;
    function GpiRemoveDynamics(hps : cardinal;lFirstSegid,lLastSegid : longint) : longbool; cdecl; external;
    function GpiBeginElement(hps : cardinal;lType : longint;pszDesc : pchar) : longbool; cdecl; external;
    function GpiEndElement(hps : cardinal) : longbool; cdecl; external;
    function GpiLabel(hps : cardinal;lLabel : longint) : longbool; cdecl; external;
    function GpiElement(hps : cardinal;lType : longint;pszDesc : pchar;lLength : longint;pbData : PBYTE) : longint; cdecl; external;
    function GpiQueryElement(hps : cardinal;lOff,lMaxLength : longint;pbData : PBYTE) : longint; cdecl; external;
    function GpiDeleteElement(hps : cardinal) : longbool; cdecl; external;
    function GpiDeleteElementRange(hps : cardinal;lFirstElement,lLastElement : longint) : longbool; cdecl; external;
    function GpiDeleteElementsBetweenLabels(hps : cardinal;lFirstLabel,lLastLabel : longint) : longbool; cdecl; external;
    function GpiQueryEditMode(hps : cardinal) : longint; cdecl; external;
    function GpiSetEditMode(hps : cardinal;lMode : longint) : longbool; cdecl; external;
    function GpiQueryElementPointer(hps : cardinal) : longint; cdecl; external;
    function GpiSetElementPointer(hps : cardinal;lElement : longint) : longbool; cdecl; external;
    function GpiOffsetElementPointer(hps : cardinal;loffset : longint) : longbool; cdecl; external;
    function GpiQueryElementType(hps : cardinal;plType : plongint;lLength : longint;pszData : pchar) : longint; cdecl; external;
    function GpiSetElementPointerAtLabel(hps : cardinal;lLabel : longint) : longbool; cdecl; external;
    function GpiQuerySegmentTransformMatrix(hps : cardinal;lSegid,lCount : longint;pmatlfArray : PMATRIXLF) : longbool; cdecl; external;
    function GpiSetSegmentTransformMatrix(hps : cardinal;lSegid,lCount : longint;pmatlfarray : PMATRIXLF;lOptions : longint) : longbool; cdecl; external;
    function GpiConvert(hps : cardinal;lSrc,lTarg,lCount : longint;aptlPoints : PPOINTL) : longbool; cdecl; external;
    function GpiConvertWithMatrix(hps : cardinal;lCountp : longint;aptlPoints : PPOINTL;lCount : longint;pmatlfArray : PMATRIXLF) : longbool; cdecl; external;
    function GpiQueryModelTransformMatrix(hps : cardinal;lCount : longint;pmatlfArray : PMATRIXLF) : longbool; cdecl; external;
    function GpiSetModelTransformMatrix(hps : cardinal;lCount : longint;pmatlfArray : PMATRIXLF;lOptions : longint) : longbool; cdecl; external;
    function GpiCallSegmentMatrix(hps : cardinal;lSegment,lCount : longint;pmatlfArray : PMATRIXLF;lOptions : longint) : longint; cdecl; external;
    function GpiQueryDefaultViewMatrix(hps : cardinal;lCount : longint;pmatlfArray : PMATRIXLF) : longbool; cdecl; external;
    function GpiSetDefaultViewMatrix(hps : cardinal;lCount : longint;pmatlfarray : PMATRIXLF;lOptions : longint) : longbool; cdecl; external;
    function GpiQueryPageViewport(hps : cardinal;prclViewport : PRECTL) : longbool; cdecl; external;
    function GpiSetPageViewport(hps : cardinal;prclViewport : PRECTL) : longbool; cdecl; external;
    function GpiQueryViewingTransformMatrix(hps : cardinal;lCount : longint;pmatlfArray : PMATRIXLF) : longbool; cdecl; external;
    function GpiSetViewingTransformMatrix(hps : cardinal;lCount : longint;pmatlfArray : PMATRIXLF;lOptions : longint) : longbool; cdecl; external;
    function GpiTranslate(hps : cardinal;pmatrixlf : PMATRIXLF;long : longint;ppointl : PPOINTL) : longbool; cdecl; external;
    function GpiScale(hps : cardinal;p1 : PMATRIXLF;p2 : longint;p3 : plongint;p4 : PPOINTL) : longbool; cdecl; external;
    function GpiRotate(p1 : cardinal;p2 : PMATRIXLF;p3,p4 : longint;p5 : PPOINTL) : longbool; cdecl; external;
    function GpiSetGraphicsField(hps : cardinal;prclField : PRECTL) : longbool; cdecl; external;
    function GpiQueryGraphicsField(hps : cardinal;prclField : PRECTL) : longbool; cdecl; external;
    function GpiSetViewingLimits(hps : cardinal;prclLimits : PRECTL) : longbool; cdecl; external;
    function GpiQueryViewingLimits(hps : cardinal;prclLimits : PRECTL) : longbool; cdecl; external;
    function GpiBeginPath(hps : cardinal;lPath : longint) : longbool; cdecl; external;
    function GpiEndPath(hps : cardinal) : longbool; cdecl; external;
    function GpiCloseFigure(hps : cardinal) : longbool; cdecl; external;
    function GpiModifyPath(hps : cardinal;lPath,lMode : longint) : longbool; cdecl; external;
    function GpiFillPath(hps : cardinal;lPath,lOptions : longint) : longint; cdecl; external;
    function GpiSetClipPath(hps : cardinal;lPath,lOptions : longint) : longbool; cdecl; external;
    function GpiOutlinePath(hps : cardinal;lPath,lOptions : longint) : longint; cdecl; external;
    function GpiPathToRegion(GpiH : cardinal;lPath,lOptions : longint) : cardinal; cdecl; external;
    function GpiStrokePath(hps : cardinal;lPath : longint;flOptions : cardinal) : longint; cdecl; external;
    function GpiCreateLogColorTable(hps,flOptions : cardinal;lFormat,lStart,lCount : longint;alTable : plongint) : longbool; cdecl; external;
    function GpiQueryColorData(hps : cardinal;lCount : longint;alArray : plongint) : longbool; cdecl; external;
    function GpiQueryLogColorTable(hps,flOptions : cardinal;lStart,lCount : longint;alArray : plongint) : longint; cdecl; external;
    function GpiQueryRealColors(hps,flOptions : cardinal;lStart,lCount : longint;alColors : plongint) : longint; cdecl; external;
    function GpiQueryNearestColor(hps,flOptions : cardinal;lRgbIn : longint) : longint; cdecl; external;
    function GpiQueryColorIndex(hps,flOptions : cardinal;lRgbColor : longint) : longint; cdecl; external;
    function GpiQueryRGBColor(hps,flOptions : cardinal;lColorIndex : longint) : longint; cdecl; external;
    function GpiCreatePalette(hab,flOptions,ulFormat,ulCount : cardinal;aulTable : pcardinal) : cardinal; cdecl; external;
    function GpiDeletePalette(hpal : cardinal) : longbool; cdecl; external;
    function GpiSelectPalette(hps,hpal : cardinal) : cardinal; cdecl; external;
    function GpiAnimatePalette(hpal,ulFormat,ulStart,ulCount : cardinal;aulTable : pcardinal) : longint; cdecl; external;
    function GpiSetPaletteEntries(hpal,ulFormat,ulStart,ulCount : cardinal;aulTable : pcardinal) : longbool; cdecl; external;
    function GpiQueryPalette(hps : cardinal) : cardinal; cdecl; external;
    function GpiQueryPaletteInfo(hpal,hps,flOptions,ulStart,ulCount : cardinal;aulArray : pcardinal) : longint; cdecl; external;
    function GpiSetColor(hps : cardinal;lColor : longint) : longbool; cdecl; external;
    function GpiQueryColor(hps : cardinal) : longint; cdecl; external;
    function GpiBox(hps : cardinal;lControl : longint;pptlPoint : PPOINTL;lHRound,lVRound : longint) : longint; cdecl; external;
    function GpiMove(hps : cardinal;pptlPoint : PPOINTL) : longbool; cdecl; external;
    function GpiLine(hps : cardinal;pptlEndPoint : PPOINTL) : longint; cdecl; external;
    function GpiPolyLine(hps : cardinal;lCount : longint;aptlPoints : PPOINTL) : longint; cdecl; external;
    function GpiPolyLineDisjoint(hps : cardinal;lCount : longint;aptlPoints : PPOINTL) : longint; cdecl; external;
    function GpiSetPattern(hps : cardinal;lPatternSymbol : longint) : longbool; cdecl; external;
    function GpiQueryPattern(hps : cardinal) : longint; cdecl; external;
    function GpiBeginArea(hps,flOptions : cardinal) : longbool; cdecl; external;
    function GpiEndArea(hps : cardinal) : longint; cdecl; external;
    function GpiCharString(hps : cardinal;lCount : longint;pchString : pshortint) : longint; cdecl; external;
    function GpiCharStringAt(hps : cardinal;pptlPoint : PPOINTL;lCount : longint;pchString : pshortint) : longint; cdecl; external;
    function GpiSetAttrMode(hps : cardinal;lMode : longint) : longbool; cdecl; external;
    function GpiQueryAttrMode(hps : cardinal) : longint; cdecl; external;
    function GpiSetAttrs(hps : cardinal;lPrimType : longint;flAttrMask,flDefMask : cardinal;ppbunAttrs : pointer) : longbool; cdecl; external;
    function GpiQueryAttrs(hps : cardinal;lPrimType : longint;flAttrMask : cardinal;ppbunAttrs : pointer) : longint; cdecl; external;
    function GpiSetBackColor(hps : cardinal;lColor : longint) : longbool; cdecl; external;
    function GpiQueryBackColor(hps : cardinal) : longint; cdecl; external;
    function GpiSetMix(hps : cardinal;lMixMode : longint) : longbool; cdecl; external;
    function GpiQueryMix(hps : cardinal) : longint; cdecl; external;
    function GpiSetBackMix(hps : cardinal;lMixMode : longint) : longbool; cdecl; external;
    
    function GpiQueryBackMix(hps : cardinal) : longint; cdecl; external;
    function GpiSetLineType(hps : cardinal;lLineType : longint) : longbool; cdecl; external;
    function GpiQueryLineType(hps : cardinal) : longint; cdecl; external;
    function GpiSetLineWidth(hps : cardinal;fxLineWidth : longint) : longbool; cdecl; external;
    function GpiQueryLineWidth(hps : cardinal) : longint; cdecl; external;
    function GpiSetLineWidthGeom(hps : cardinal;lLineWidth : longint) : longbool; cdecl; external;
    function GpiQueryLineWidthGeom(hps : cardinal) : longint; cdecl; external;
    function GpiSetLineEnd(hps : cardinal;lLineEnd : longint) : longbool; cdecl; external;
    function GpiQueryLineEnd(hps : cardinal) : longint; cdecl; external;
    function GpiSetLineJoin(hps : cardinal;lLineJoin : longint) : longbool; cdecl; external;
    function GpiQueryLineJoin(hps : cardinal) : longint; cdecl; external;
    function GpiSetCurrentPosition(hps : cardinal;pptlPoint : PPOINTL) : longbool; cdecl; external;
    function GpiQueryCurrentPosition(hps : cardinal;pptlPoint : PPOINTL) : longbool; cdecl; external;
    function GpiSetArcParams(hps : cardinal;parcpArcParams : PARCPARAMS) : longbool; cdecl; external;
    function GpiQueryArcParams(hps : cardinal;parcpArcParams : PARCPARAMS) : longbool; cdecl; external;
    function GpiPointArc(hps : cardinal;pptl2 : PPOINTL) : longint; cdecl; external;
    function GpiFullArc(hps : cardinal;lControl,fxMultiplier : longint) : longint; cdecl; external;
    function GpiPartialArc(hps : cardinal;pptlCenter : PPOINTL;fxMultiplier,fxStartAngle,fxSweepAngle : longint) : longint; cdecl; external;
    function GpiPolyFillet(hps : cardinal;lCount : longint;aptlPoints : PPOINTL) : longint; cdecl; external;
    function GpiPolySpline(hps : cardinal;lCount : longint;aptlPoints : PPOINTL) : longint; cdecl; external;
    function GpiPolyFilletSharp(hps : cardinal;lCount : longint;aptlPoints : PPOINTL;afxPoints : plongint) : longint; cdecl; external;
    function GpiSetPatternSet(hps : cardinal;lSet : longint) : longbool; cdecl; external;
    function GpiQueryPatternSet(hps : cardinal) : longint; cdecl; external;
    function GpiSetPatternRefPoint(hps : cardinal;pptlRefPoint : PPOINTL) : longbool; cdecl; external;
    function GpiQueryPatternRefPoint(hps : cardinal;pptlRefPoint : PPOINTL) : longbool; cdecl; external;
    function GpiQueryCharStringPos(hps,flOptions : cardinal;lCount : longint;pchString : pshortint;alXincrements : plongint;aptlPositions : PPOINTL) : longbool; cdecl; external;
    function GpiQueryCharStringPosAt(hps : cardinal;pptlStart : PPOINTL;flOptions : cardinal;lCount : longint;pchString : pshortint;alXincrements : plongint;aptlPositions : PPOINTL) : longbool; cdecl; external;
    function GpiQueryTextBox(hps : cardinal;lCount1 : longint;pchString : pshortint;lCount2 : longint;aptlPoints : PPOINTL) : longbool; cdecl; external;
    function GpiQueryDefCharBox(hps : cardinal;psizlSize : PSIZEL) : longbool; cdecl; external;
    function GpiSetCharSet(hps : cardinal;llcid : longint) : longbool; cdecl; external;
    function GpiQueryCharSet(hps : cardinal) : longint; cdecl; external;
    function GpiSetCharBox(hps : cardinal;psizfxBox : PSIZEF) : longbool; cdecl; external;
    function GpiQueryCharBox(hps : cardinal;psizfxSize : PSIZEF) : longbool; cdecl; external;
    function GpiSetCharAngle(hps : cardinal;pgradlAngle : PGRADIENTL) : longbool; cdecl; external;
    function GpiQueryCharAngle(hps : cardinal;pgradlAngle : PGRADIENTL) : longbool; cdecl; external;
    function GpiSetCharShear(hps : cardinal;pptlAngle : PPOINTL) : longbool; cdecl; external;
    function GpiQueryCharShear(hps : cardinal;pptlShear : PPOINTL) : longbool; cdecl; external;
    function GpiSetCharDirection(hps : cardinal;lDirection : longint) : longbool; cdecl; external;
    function GpiQueryCharDirection(hps : cardinal) : longint; cdecl; external;
    function GpiSetCharMode(hps : cardinal;lMode : longint) : longbool; cdecl; external;
    function GpiQueryCharMode(hps : cardinal) : longint; cdecl; external;
    function GpiSetTextAlignment(hps : cardinal;lHoriz,lVert : longint) : longbool; cdecl; external;
    function GpiQueryTextAlignment(hps : cardinal;plHoriz,plVert : plongint) : longbool; cdecl; external;
    function GpiCharStringPos(hps : cardinal;prclRect : PRECTL;flOptions : cardinal;lCount : longint;pchString : pshortint;alAdx : plongint) : longint; cdecl; external;
    function GpiCharStringPosAt(hps : cardinal;pptlStart : PPOINTL;prclRect : PRECTL;flOptions : cardinal;lCount : longint;pchString : pshortint;alAdx : plongint) : longint; cdecl; external;
    function GpiSetCharExtra(hps : cardinal;Extra : longint) : longbool; cdecl; external;
    function GpiSetCharBreakExtra(hps : cardinal;BreakExtra : longint) : longbool; cdecl; external;
    function GpiQueryCharExtra(hps : cardinal;Extra : plongint) : longbool; cdecl; external;
    function GpiQueryCharBreakExtra(hps : cardinal;BreakExtra : plongint) : longbool; cdecl; external;
    function GpiMarker(hps : cardinal;pptlPoint : PPOINTL) : longint; cdecl; external;
    function GpiPolyMarker(hps : cardinal;lCount : longint;aptlPoints : PPOINTL) : longint; cdecl; external;
    function GpiSetMarker(hps : cardinal;lSymbol : longint) : longbool; cdecl; external;
    function GpiSetMarkerBox(hps : cardinal;psizfxSize : PSIZEF) : longbool; cdecl; external;
    function GpiSetMarkerSet(hps : cardinal;lSet : longint) : longbool; cdecl; external;
    function GpiQueryMarker(hps : cardinal) : longint; cdecl; external;
    function GpiQueryMarkerBox(hps : cardinal;psizfxSize : PSIZEF) : longbool; cdecl; external;
    function GpiQueryMarkerSet(hps : cardinal) : longint; cdecl; external;
    function GpiImage(hps : cardinal;lFormat : longint;psizlImageSize : PSIZEL;lLength : longint;pbData : PBYTE) : longint; cdecl; external;
    function GpiPop(hps : cardinal;lCount : longint) : longbool; cdecl; external;
    function GpiPtVisible(hps : cardinal;pptlPoint : PPOINTL) : longint; cdecl; external;
    function GpiRectVisible(hps : cardinal;prclRectangle : PRECTL) : longint; cdecl; external;
    function GpiComment(hps : cardinal;lLength : longint;pbData : PBYTE) : longbool; cdecl; external;
    function GpiCreateLogFont(hps : cardinal;pName : PSTR8;lLcid : longint;pfatAttrs : PFATTRS) : longint; cdecl; external;
    function GpiDeleteSetId(hps : cardinal;lLcid : longint) : longbool; cdecl; external;
    function GpiLoadFonts(hab : cardinal;pszFilename : pchar) : longbool; cdecl; external;
    function GpiUnloadFonts(hab : cardinal;pszFilename : pchar) : longbool; cdecl; external;
    function GpiQueryFonts(hps,flOptions : cardinal;pszFacename : pchar;plReqFonts : plongint;lMetricsLength : longint;afmMetrics : PFONTMETRICS) : longint; cdecl; external;
    function GpiQueryFontMetrics(hps : cardinal;lMetricsLength : longint;pfmMetrics : PFONTMETRICS) : longbool; cdecl; external;
    function GpiQueryKerningPairs(hps : cardinal;lCount : longint;akrnprData : PKERNINGPAIRS) : longint; cdecl; external;
    function GpiQueryWidthTable(hps : cardinal;lFirstChar,lCount : longint;alData : plongint) : longbool; cdecl; external;
    function GpiQueryNumberSetIds(hps : cardinal) : longint; cdecl; external;
    function GpiQuerySetIds(hps : cardinal;lCount : longint;alTypes : plongint;aNames : PSTR8;allcids : plongint) : longbool; cdecl; external;
    function GpiQueryFaceString(PS : cardinal;FamilyName : pchar;attrs : PFACENAMEDESC;length : longint;CompoundFaceName : pchar) : cardinal; cdecl; external;
    function GpiQueryLogicalFont(PS : cardinal;lcid : longint;name : PSTR8;attrs : PFATTRS;length : longint) : longbool; cdecl; external;
    function GpiQueryFontAction(anchor,options : cardinal) : cardinal; cdecl; external;
    function GpiLoadPublicFonts(p1 : cardinal;p2 : pchar) : longbool; cdecl; external;
    function GpiUnloadPublicFonts(p1 : cardinal;p2 : pchar) : longbool; cdecl; external;
    function GpiSetCp(hps,ulCodePage : cardinal) : longbool; cdecl; external;
    function GpiQueryCp(hps : cardinal) : cardinal; cdecl; external;
    function GpiQueryFontFileDescriptions(hab : cardinal;pszFilename : pchar;plCount : plongint;affdescsNames : PFFDESCS) : longint; cdecl; external;
    function GpiQueryFullFontFileDescs(hab : cardinal;pszFilename : pchar;plCount : plongint;pNames : pointer;plNamesBuffLength : plongint) : longint; cdecl; external;
    function GpiBitBlt(hpsTarget,hpsSource : cardinal;lCount : longint;aptlPoints : PPOINTL;lRop : longint;flOptions : cardinal) : longint; cdecl; external;
    function GpiDeleteBitmap(hbm : cardinal) : longbool; cdecl; external;
    function GpiLoadBitmap(hps,Resource,idBitmap:cardinal;lWidth,lHeight : longint) : cardinal; cdecl; external;
    function GpiSetBitmap(hps,hbm : cardinal) : cardinal; cdecl; external;
    function GpiWCBitBlt(hpsTarget,hbmSource : cardinal;lCount : longint;aptlPoints : PPOINTL;lRop : longint;flOptions : cardinal) : longint; cdecl; external;
    function GpiCreateBitmap(hps : cardinal;pbmpNew : PBITMAPINFOHEADER2;flOptions : cardinal;pbInitData : PBYTE;pbmiInfoTable : PBITMAPINFO2) : cardinal; cdecl; external;
    function GpiSetBitmapBits(hps : cardinal;lScanStart,lScans : longint;pbBuffer : PBYTE;pbmiInfoTable : PBITMAPINFO2) : longint; cdecl; external;
    function GpiSetBitmapDimension(hbm : cardinal;psizlBitmapDimension : PSIZEL) : longbool; cdecl; external;
    function GpiSetBitmapId(hps,hbm : cardinal;lLcid : longint) : longbool; cdecl; external;
    function GpiQueryBitmapBits(hps : cardinal;lScanStart,lScans : longint;pbBuffer : PBYTE;pbmiInfoTable : PBITMAPINFO2) : longint; cdecl; external;
    function GpiQueryBitmapDimension(hbm : cardinal;psizlBitmapDimension : PSIZEL) : longbool; cdecl; external;
    function GpiQueryBitmapHandle(hps : cardinal;lLcid : longint) : cardinal; cdecl; external;
    function GpiQueryBitmapParameters(hbm : cardinal;pbmpData : PBITMAPINFOHEADER) : longbool; cdecl; external;
    function GpiQueryBitmapInfoHeader(hbm : cardinal;pbmpData : PBITMAPINFOHEADER2) : longbool; cdecl; external;
    function GpiQueryDeviceBitmapFormats(hps : cardinal;lCount : longint;alArray : plongint) : longbool; cdecl; external;
    function GpiSetPel(hps : cardinal;pptlPoint : PPOINTL) : longint; cdecl; external;
    function GpiQueryPel(hps : cardinal;pptlPoint : PPOINTL) : longint; cdecl; external;
    function GpiFloodFill(hps : cardinal;lOptions,lColor : longint) : longint; cdecl; external;
    function GpiDrawBits(hps : cardinal;pBits : pointer;pbmiInfoTable : PBITMAPINFO2;lCount : longint;aptlPoints : PPOINTL;lRop : longint;flOptions : cardinal) : longint; cdecl; external;
    function GpiCombineRegion(hps,hrgnDest,hrgnSrc1,hrgnSrc2 : cardinal;lMode : longint) : longint; cdecl; external;
    function GpiCreateRegion(hps : cardinal;lCount : longint;arclRectangles : PRECTL) : cardinal; cdecl; external;
    function GpiDestroyRegion(hps,hrgn : cardinal) : longbool; cdecl; external;
    function GpiEqualRegion(hps,hrgnSrc1,hrgnSrc2 : cardinal) : longint; cdecl; external;
    function GpiOffsetRegion(hps,Hrgn : cardinal;pptlOffset : PPOINTL) : longbool; cdecl; external;
    function GpiPaintRegion(hps,hrgn : cardinal) : longint; cdecl; external;
    function GpiFrameRegion(hps,hrgn : cardinal;thickness : PSIZEL) : longint; cdecl; external;
    function GpiPtInRegion(hps,hrgn : cardinal;pptlPoint : PPOINTL) : longint; cdecl; external;
    function GpiQueryRegionBox(hps,hrgn : cardinal;prclBound : PRECTL) : longint; cdecl; external;
    function GpiQueryRegionRects(hps,hrgn : cardinal;prclBound : PRECTL;prgnrcControl : PRGNRECT;prclRect : PRECTL) : longbool; cdecl; external;
    function GpiRectInRegion(hps,hrgn : cardinal;prclRect : PRECTL) : longint; cdecl; external;
    function GpiSetRegion(hps,hrgn : cardinal;lcount : longint;arclRectangles : PRECTL) : longbool; cdecl; external;
    function GpiSetClipRegion(hps,hrgn : cardinal;phrgnOld : pcardinal) : longint; cdecl; external;
    function GpiQueryClipRegion(hps : cardinal) : cardinal; cdecl; external;
    function GpiQueryClipBox(hps : cardinal;prclBound : PRECTL) : longint; cdecl; external;
    function GpiExcludeClipRectangle(hps : cardinal;prclRectangle : PRECTL) : longint; cdecl; external;
    function GpiIntersectClipRectangle(hps : cardinal;prclRectangle : PRECTL) : longint; cdecl; external;
    function GpiOffsetClipRegion(hps : cardinal;pptlPoint : PPOINTL) : longint; cdecl; external;
    function GpiCopyMetaFile(hmf : cardinal) : cardinal; cdecl; external;
    function GpiDeleteMetaFile(hmf : cardinal) : longbool; cdecl; external;
    function GpiLoadMetaFile(hab : cardinal;pszFilename : pchar) : cardinal; cdecl; external;
    function GpiPlayMetaFile(hps,hmf : cardinal;lCount1 : longint;alOptarray,plSegCount : plongint;lCount2 : longint;pszDesc : pchar) : longint; cdecl; external;
    function GpiQueryMetaFileBits(hmf : cardinal;lOffset,lLength : longint;pbData : PBYTE) : longbool; cdecl; external;
    function GpiQueryMetaFileLength(hmf : cardinal) : longint; cdecl; external;
    function GpiSaveMetaFile(hmf : cardinal;pszFilename : pchar) : longbool; cdecl; external;
    function GpiSetMetaFileBits(hmf : cardinal;lOffset,lLength : longint;pbBuffer : PBYTE) : longbool; cdecl; external;
    function GpiQueryDefArcParams(hps : cardinal;parcpArcParams : PARCPARAMS) : longbool; cdecl; external;
    function GpiQueryDefAttrs(hps : cardinal;lPrimType : longint;flAttrMask : cardinal;ppbunAttrs : pointer) : longbool; cdecl; external;
    function GpiQueryDefTag(hps : cardinal;plTag : plongint) : longbool; cdecl; external;
    function GpiQueryDefViewingLimits(hps : cardinal;prclLimits : PRECTL) : longbool; cdecl; external;
    function GpiSetDefArcParams(hps : cardinal;parcpArcParams : PARCPARAMS) : longbool; cdecl; external;
    function GpiSetDefAttrs(hps : cardinal;lPrimType : longint;flAttrMask : cardinal;ppbunAttrs : pointer) : longbool; cdecl; external;
    function GpiSetDefTag(hps : cardinal;lTag : longint) : longbool; cdecl; external;
    function GpiSetDefViewingLimits(hps : cardinal;prclLimits : PRECTL) : longbool; cdecl; external;
    function GpiPolygons(hps,ulCount : cardinal;paplgn : PPOLYGON;flOptions,flModel : cardinal) : longint; cdecl; external;

end.
