#!/bin/bash
if [[ "$#" != "0" ]]
then
  cd "`dirname "$0"`/.."
  FPCSRC="$PWD"
  cd $FPCSRC/tests/sparc
  $FPCSRC/compiler/ppcsparc -s -al -Fi$FPCSRC/rtl/{unix,linux,sparc,inc} -dSPARC "$@"
else
  fpc pp -gl -oppcsparc -dExtDebug -Fusparc -Fusystems -dSPARC -dNoOpt -dGDB
fi
