#
# Makefile.fpc for MySql FCL db units
#

[package]
main=fcl

[target]
units=mysqldb4 mysqldb3
rsts=mysqldb
examples=mtest

[clean]
units=mysql mysql_com mysql_version

[require]
packages=mysql

[compiler]
options=-S2

[install]
fpcpackage=y

[default]
fpcdir=../../..
