#
#   Makefile.fpc for XML for FCL
#

[package]
main=fcl

[target]
units=dom htmldoc xmlcfg xmlread xmlstreaming xmlwrite xhtml htmldefs htmwrite

[compiler]
options=-S2
targetdir=../$(OS_TARGET)

[install]
fpcpackage=y

[default]
fpcdir=../..
