#
# Makefile.fpc for SQL IBConnection
#

[package]
main=fcl

[target]
units=mysql40conn mysql41conn mysql50conn mysql4conn

[require]
packages=mysql

[compiler]
options=-S2

[install]
fpcpackage=y

[default]
fpcdir=../../../..
