#
#   Makefile.fpc for FPCMake
#

[target]
programs=fpcreslipo
units=msghandler paramparser sourcehandler

[clean]
units=fpcresfix elfbfd elfres

[require]
packages=rtl fcl-res

[install]
fpcpackage=y

[default]
fpcdir=../..

[rules]
