#
#   Makefile.fpc for Free Pascal Symbian Build Tool
#

[target]
programs=mksymbian

[clean]
units=cfgfile cmdline compiler constants projectparser sdkutil

[require]
packages=

[compiler]

[install]
fpcpackage=y

[default]
fpcdir=../..

[rules]
.NOTPARALLEL:
mksymbian$(EXEEXT): mksymbian.pas
