This dirctory contains some utilities that come with the Free Pascal
Compiler. They can be compiled by typing 'make all' in this directory.

Currently, the following things are provided:

ppdep   : Creates a makefile which includes all interdependant units.

ptop    : Pascal source beautifier

delp    : Deletes all files generated by Free Pascal, as well 
          temporary files.

h2pas/  : Contains the h2pas program, which converts C header files to pascal
          unit files.
tply/   : Pascal Lex and Yacc
fpcm/   : fpcmake - utility to generate makefiles to regenerate compiler

Typing a 'make install' will put everything into place.

Happy Coding !
The Free Pascal Development Team.
