#
#   Makefile.fpc for fprcp
#

[targets]
programs=fprcp

[clean]
units=comments expr pasprep

[dirs]
fpcdir=../..


[rules]
fpcrp$(EXEEXT): fpcrp$(PASEXT) comments$(PASEXT) pexpr$(PASEXT) pasprep$(PASEXT)
