#!/bin/bash
#
# Create debian files from *.in files.
# 
# $1 = path to debian files
#
if [ $# != 1 ]; then
  echo 'Usage : fixdeb path'
  exit 1
fi

PACKAGEVERSION=`head -n 1 $1/changelog | awk '{ print $2 }' | tr -d '[()]'`
FPCVERSION=`echo $PACKAGEVERSION | awk -F '-' '{ print $1 }'`

echo 'PackageVersion: ' $PACKAGEVERSION
echo 'FPCVersion    : ' $FPCVERSION

for i in $1/*.in
do
  j=${i/.in/}
  sed -e 's/#FPCVERSION#/'$FPCVERSION'/g;s/#PACKAGEVERSION#/'$PACKAGEVERSION'/g' $i > $j
done
