#!/bin/bash

EXAMPLE_TEMP=$1
DOC_DIR=$2

move_examples()
{
    for package in $2; do
        # Move dir
        mv -f $EXAMPLE_TEMP/$package/examples $DOC_DIR/fp-units-$1/examples/
	# Rename dir
	mv $DOC_DIR/fp-units-$1/examples/examples $DOC_DIR/fp-units-$1/examples/$package
    done
}


FCL_PACKAGES="fcl"
GTK_PACKAGES="gtk"
GNOME1_PACKAGES="imlib zvt gnome gconf"
BASE_PACKAGES="paszlib pasjpeg regexpr ncurses"
GFX_PACKAGES="forms ggi libgdb svgalib opengl"
DB_PACKAGES="ibase mysql oracle postgres gdbm odbc"
MISC_PACKAGES="gdbint utmp syslog cdrom tcl"
NET_PACKAGES="inet netdb"

move_examples fcl $FCL_PACKAGES
move_examples gtk $GTK_PACKAGES
move_examples gnome1 $GNOME1_PACKAGES
move_examples base $BASE_PACKAGES
move_examples gfx $GFX_PACKAGES
move_examples db $DB_PACKAGES
move_examples misc $MISC_PACKAGES
move_examples net $NET_PACKAGES
