#!/bin/bash

set -e

EXAMPLE_TEMP=$1
DOC_DIR=$2

move_examples()
{
    # Make examples dir
    install -d -m 755 $DOC_DIR/fp-units-$1/examples/
    
    for package in $2; do
        if [ -d $EXAMPLE_TEMP/$package/examples ]; then
            echo "Moving examples of $package"
            # Move dir
            mv -f $EXAMPLE_TEMP/$package/examples $DOC_DIR/fp-units-$1/examples/
	    # Rename dir
	    mv -f $DOC_DIR/fp-units-$1/examples/examples $DOC_DIR/fp-units-$1/examples/$package
            rmdir $EXAMPLE_TEMP/$package
        fi
    done
}


FCL_PACKAGES="fcl"
FV_PACKAGES="fv"
GTK_PACKAGES="gtk"
GTK2_PACKAGES="gtk2"
GNOME1_PACKAGES="imlib zvt gnome gconf"
BASE_PACKAGES="paszlib pasjpeg regexpr ncurses md5"
GFX_PACKAGES="forms ggi libgd svgalib opengl"
DB_PACKAGES="ibase mysql oracle postgres gdbm odbc"
MISC_PACKAGES="gdbint utmp syslog cdrom tcl newt"
NET_PACKAGES="netdb"

move_examples fcl "$FCL_PACKAGES"
move_examples fv "$FV_PACKAGES"
move_examples gtk "$GTK_PACKAGES"
move_examples gtk2 "$GTK2_PACKAGES"
move_examples gnome1 "$GNOME1_PACKAGES"
move_examples base "$BASE_PACKAGES"
move_examples gfx "$GFX_PACKAGES"
move_examples db "$DB_PACKAGES"
move_examples misc "$MISC_PACKAGES"
move_examples net "$NET_PACKAGES"

rmdir $EXAMPLE_TEMP

