#! /bin/sh

# create link
ln -sf /usr/lib/fpc/0.99.11/ppc386 /usr/bin/ppc386

# create /etc/ppc386.cfg
/usr/lib/fpc/0.99.11/samplecfg /usr/lib/fpc/0.99.11 `dirname \`find /usr/lib/gcc-lib/ -name libgcc.a -print | grep -v egcs \``

# update ld.so cache
ldconfig
