#
# Makefile.fpc for SQL FCL db units
#

[package]
main=fcl

[target]
dirs_linux=interbase postgres
dirs_freebsd=interbase postgres
dirs_darwin=interbase postgres
dirs_netbsd=interbase postgres
dirs_openbsd=interbase postgres
dirs_win32=interbase postgres
units=sqldb
rsts=sqldb

[clean]
units=ibas40 ibase60

[require]
packages=ibase

[compiler]
options=-S2 
targetdir=../../$(OS_TARGET)

[install]
fpcpackage=y

[default]
fpcdir=../../..
