#
# Makefile.fpc for SQL FCL db units
#

[package]
main=fcl

[target]
dirs_linux=interbase postgres mysql
dirs_freebsd=interbase postgres mysql
dirs_darwin=interbase postgres mysql
dirs_netbsd=interbase postgres mysql
dirs_openbsd=interbase postgres mysql
dirs_win32=interbase postgres mysql
units=sqldb
rsts=sqldb

[compiler]
options=-S2

[install]
fpcpackage=y

[default]
fpcdir=../../..
