#
#   Makefile.fpc for FPDoc
#

[package]
name=instantfpc
version=2.5.1

[require]
packages=fcl-process

[target]
programs=instantfpc

[compiler]
options=-S2h

[default]
fpcdir=../..

[clean]
units=instantfptools

[rules]
.NOTPARALLEL:
fpdoc$(EXEEXT): instantfpc.pp instantfptools.pp

