#!/bin/sh
#
# Shell script to make a FPC .tar package for Linux
# Copyright 1996-2000 Michael Van Canneyt and Peter Vreman
#

# Version
VERSION=0.99.14
RELEASE=ELF

unset FPCDIR

make linux
#make source
#make docs
#make demo

SOURCES=`/bin/ls *src.tar.gz`
FILES=`/bin/ls *linux.tar.gz`
RELFILES="binary.tar sources.tar demo.tar.gz docs.tar.gz install.sh"

echo Creating binary.tar
tar cf binary.tar $FILES
echo Creating sources.tar
tar cf sources.tar $SOURCES

echo Creating fpc-$VERSION.$RELEASE.tar
tar cf fpc-$VERSION.$RELEASE.tar $RELFILES 
