#!/bin/sh

set -e

if [ $# -ne 1 ]; then
  echo "Usage: $0 <version>"
  exit 1
fi

makefiles=`find . -name Makefile.fpc`

for f in $makefiles; do
  sed s+version=[0-9\.]*$+version=$1+ $f > $f.tmp
  mv $f.tmp $f
  fpcmake -Tall $f
done
