#
# Makefile.fpc for SQL IBConnection
#

[package]
main=fcl

[target]
units=ibconnection

[require]
packages=ibase

[compiler]
options=-S2 
targetdir=../../../$(OS_TARGET)

[install]
fpcpackage=y

[default]
fpcdir=../../../..
