{
    $Id$
    This file is part of the Free Pascal run time library.
    Copyright (c) 1998-2000 by the Free Pascal development team.

    See the file COPYING.FPC, included in this distribution,
    for details about the copyright.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 **********************************************************************}
{$define amiga}
{$undef go32v2}
{$undef os2}
{$undef linux}
{$undef win32}
{$undef macos}
{$undef atari}

{
  $Log$
  Revision 1.2  2000-01-07 16:32:22  daniel
    * copyright 2000 added

  Revision 1.1.1.1  1998/03/25 11:18:47  root
  * Restored version

  Revision 1.3  1998/01/30 13:22:24  carl
   - undef amiga!

  Revision 1.2  1998/01/26 12:02:47  michael
  + Added log at the end


  
  Working file: rtl/amiga/os.inc
  description:
  ----------------------------
  revision 1.1
  date: 1998/01/24 05:11:03;  author: carl;  state: Exp;
    + initial revision
  =============================================================================
}
