#
#   Makefile.fpc for Free Pascal Utils
#

[package]
name=dxegen
version=1.05

[target]
dirs=fpcm tply h2pas fprcp
programs_go32v2=dxegen

[clean]
units=coff

[install]
fpcpackage=y

[default]
fpcdir=../..

[rules]

dxegen$(EXEEXT): dxegen.pp coff$(PPUEXT)

coff$(PPUEXT)  : coff.pp


