#
#   Makefile.fpc for FPC demo package
#

[package]
name=demo
version=1.9.6

[target]
dirs=text
dirs_go32v2=modex graph
dirs_win32=win32 graph
dirs_linux=linux graph
dirs_os2=os2 graph
dirs_netware=netware

[install]
fpcpackage=y

[rules]
#################################
# Demo installation for linux
#

.PHONY: installexamples demozip

installexamples:
        $(MKDIR) $(INSTALL_SOURCEDIR)
        $(COPYTREE) * $(INSTALL_SOURCEDIR)

demozip: zipsourceinstall

[default]
fpcdir=..
