#
#   Makefile.fpc for FCL FPCUnit test framework.
#

[package]
main=fcl

[target]
units=asserttest frameworktest suitetest

[compiler]
options=-S2h
targetdir=../../$(OS_TARGET)

[install]
fpcpackage=y

[default]
fpcdir=../../..
