#
#   Makefile.fpc for FCL net units
#

[package]
main=fcl

[require]
packages=paszlib

[target]
units=fpimgcmn fpimage pngcomn fpreadpng  fpreadxpm  fpwritexpm 
examples=imgconv

[compiler]
targetdir=../$(OS_TARGET)

[install]
fpcpackage=y

[default]
fpcdir=../..
