#
# Makefile.fpc for interbase FCL db units
#

[package]
main=fcl

[target]
units=interbase
examples=testib

[clean]
units=ibas40 ibase60

[require]
packages=ibase

[compiler]
options=-S2

[install]
fpcpackage=y

[default]
fpcdir=../../..
