#
# Makefile.fpc for interbase.pp units

[targets]
units=interbase
examples=testib

[require]
options=-S2 
packages=fcl ibase

[install]
unitssubdir=fcl
packagename=interbase

[dirs]
fpcdir=../../..
targetdir=../../$(OS_TARGET)
