#
# Makefile.fpc for interbase FCL db units
#

[package]
main=fcl

[target]
units=interbase
examples=testib

[require]
packages=ibase

[compiler]
options=-S2 
targetdir=../../$(OS_TARGET)

[default]
fpcdir=../../..
