#
# Makefile.fpc for fpODBC db units
#

[package]
main=fcl

[target]
units=fpodbc
examples=testbcon testcon testdrcon testenv testfl testpa testpk\
         testpr testsql testst testtl


[clean]
units=

[require]
packages=odbc

[compiler]
options=-S2

[install]
fpcpackage=y

[default]
fpcdir=../../../..
