#
# Create HTML using hevea tex 2 html conversion
#

%.html: %.tex fpc-hevea.tex
	$(HEVEA) $(HEVEAOPTS) $<

user: $(INCLUDES) user.html
units: $(INCLUDES) units.html
prog: $(INCLUDES) prog.html
onechap: $(INCLUDES) onechap.html
ref: $(INCLUDES) ref.html
fpdoc: $(INCLUDES) fpdoc.html

html: $(INCLUDES) $(addsuffix .html,$(HTML))
