#
# Create HTML using hevea tex 2 html conversion
#

%.chk: %.tex fpc-hevea.tex
	cp -f preamble.hev preamble.inc
	$(HEVEA) $(HEVEAOPTS) $<
	touch $(basename $<).chk

user.chk: $(INCLUDES) user.tex messages.inc
prog.chk: $(INCLUDES) prog.tex
onechap.chk: $(INCLUDES) onechap.tex
ref.chk: $(INCLUDES) ref.tex
fpdoc.chk: $(INCLUDES) fpdoc.tex

