.TH ppudump 1 "5 June 1999" FreePascal "Free Pascal Unit dump utility"
.SH NAME
ppudump \- The FPC Pascal unit dump program.

.SH SYNOPSIS

\fIppudump\fP [-h] [-v[h|i|m|d|s|b|a]] ppu-file1 ppufile2 ...

.SH Description

\fIppudump\fP writes the contents of a Free Pascal unit file to standard
output. It gives a listing of all definitions in the unit file. The format
of the listing can be controlled by the options.

.SH Usage

You can invoke ppudump with as arguments the names of the units that you
want to dump. You need not specify a extension, by default \fI.ppu\fP is
assumed. The output goes to standard output.

.SH Options

\fIppudump\fP has only two options:

.IP \fI\-h\fP 
shows a short help screen.
.IP \fI\-v\fP
Controls the level of verbosity. \-v accepts any combination of the following 
letters behind it:
.RS
.IP \fIa\fP
Shows all information stored in the PPU file.
.IP \fIb\fP
Shows the browser information in the PPU file (if present).
.IP \fId\fP
Shows the definitions in the PPU file.
.IP \fIh\fP 
Shows the header information in the PPU file.
.IP \fIi\fP
Shows only interface information, implementation information is
not shown.
.IP \fIm\fP
Shows only implementation information, interface interface is not shown.
.IP \fIs\fP
Shows the symbols stored in the PPU file.
.RE

.SH SEE ALSO
.IP 
.BR  ppc386 (1)
.BR  ppumove (1)
