#
#   Makefile.fpc for FCL lnet units
#

[package]
main=fcl

[target]
units=lnet lcommon levents lcontrolstack ltelnet lftp lsmtp lhttputil lhttp \
      lmimetypes lprocess lstrbuffer fastcgi lfastcgi lspawnfcgi lwebserver
units_os2=lnet lcommon levents lcontrolstack ltelnet lftp lsmtp
exampledirs=examples

[require]
packages=netdb 

[compiler]
options=-S2 -Sm
includedir=sys

[install]
fpcpackage=y

[default]
fpcdir=../..
