{
    $Id$
    This file is part of the Free Pascal run time library.
    Copyright (c) 1999-2000 by Michael Van Canneyt
    member of the Free Pascal development team

    See the file COPYING.FPC, included in this distribution,
    for details about the copyright.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 **********************************************************************}

{ OS handling utilities }

Function GetEnvironmentVariable(Const EnvVar : String) : String;

{
  $Log$
  Revision 1.2  2001-02-20 22:14:39  peter
    * new file

  Revision 1.1.2.1  2001/02/20 21:15:14  michael
  + Added GetEnvironmentVariable function

}