#
#   Makefile.fpc for Free Component Library Examples/Tests
#

[targets]
programs=stringl dparser fstream mstream list threads testrtf \
         cfgtest xmldump htdump testcgi tidea \
         b64test b64test2 b64enc b64dec restest
programs_win32=testz testz2

[clean]
files=restest.rst

[packages]
fcl=1

[dirs]
fpcdir=../..
targetdir=.

[defaults]
defaultoptions=-S2
