#
#   Makefile.fpc for Free Component Library Examples/Tests
#

[targets]
programs=stringl dparser fstream mstream list threads testrtf \
         cfgtest xmldump htdump testcgi tidea \
         b64test b64test2 b64enc b64dec restest testz testz2
programs_win32=showver

rst=restest

[require]
options=-S2
packages=fcl
packages_linux=zlib
packages_win32=paszlib
packages_go32=paszlib

[dirs]
fpcdir=../..
targetdir=.
