WINDOWS_FILES=base errors defines struct redef \
              ascfun ascdef unifun unidef func

  $Log$
  Revision 1.5  2000-07-14 10:33:12  michael
  + Conditionals fixed

  Revision 1.2  2000/07/13 11:34:00  michael
  + removed logs
 
}
