WINDOWS_FILES=base errors defines struct redef \
              ascfun ascdef unifun unidef func
{
  $Log$
  Revision 1.3  2000-07-14 06:57:11  michael
  + Fixed log

  Revision 1.2  2000/07/13 11:34:00  michael
  + removed logs
 
}
