#
#   Makefile.fpc for MIPSEL PlayStation 1
#
[package]
main=rtl
[target]
loaders=
units=$(SYSTEMUNIT) $(OBJPASUNIT) $(FPINTRESUNIT) $(CTYPESUNIT) \
  $(UUCHARUNIT) $(STRINGSUNIT) \
  ps1System ps1CDRom ps1COP0 ps1GPU ps1GTE ps1SPU \
  si_prc

[require]
nortl=y
[install]
fpcpackage=y
[default]
target=ps1
cpu=mipsel
[compiler]
includedir=$(INC) $(PROCINC)
sourcedir=$(INC) $(PROCINC) $(COMMON) ./bare-metal
[prerules]
RTL=..
INC=../inc
COMMON=$(RTL)/common
PROCINC=../$(CPU_TARGET)
UNITPREFIX=rtl

# Paths
OBJPASDIR=$(RTL)/objpas
# Insert exception handler in system unit
ifdef EXCEPTIONS_IN_SYSTEM
override FPCOPT+=-dEXCEPTIONS_IN_SYSTEM
endif
# Insert exception handler in system unit
ifdef NO_EXCEPTIONS_IN_SYSTEM
override FPCOPT+=-dNO_EXCEPTIONS_IN_SYSTEM
endif
[rules]
# Get the system independent include file names.
# This will set the following variables :
# SYSINCNAMES
include $(INC)/makefile.inc
SYSINCDEPS=$(addprefix $(INC)/,$(SYSINCNAMES))
# Get the processor dependent include file names.
# This will set the following variables :
# CPUINCNAMES
include $(PROCINC)/makefile.cpu
SYSCPUDEPS=$(addprefix $(PROCINC)/,$(CPUINCNAMES))
# Put system unit dependencies together.
SYSDEPS=$(SYSINCDEPS) $(SYSCPUDEPS)


# Extract only the -Cf option from rtl.cfg.
RTL_FPU_OPT=$(shell grep -E '^[[:space:]]*-Cf' rtl.cfg | tail -n 1)


# Build System with the explicit minimal feature set.
override FPC_SYSTEM_OPT += @rtl.cfg

# Make all PS1 RTL units smart-linkable.
override FPCOPT += -CX


# ObjPas must use the same FPU ABI as System.
$(OBJPASUNIT)$(PPUEXT): $(OBJPASDIR)/objpas.pp $(INC)/except.inc $(SYSTEMUNIT)$(PPUEXT)
        $(COMPILER) $(RTL_FPU_OPT) -Fi$(OBJPASDIR) $(OBJPASDIR)/objpas.pp

        
# BARE-METAL units
ps1System$(PPUEXT) : bare-metal/ps1System.pas $(SYSTEMUNIT)$(PPUEXT)
        $(COMPILER) $(RTL_FPU_OPT) $<

ps1CDRom$(PPUEXT) : bare-metal/ps1CDRom.pas ps1System$(PPUEXT) $(SYSTEMUNIT)$(PPUEXT)
        $(COMPILER) $(RTL_FPU_OPT) $<

ps1COP0$(PPUEXT) : bare-metal/ps1COP0.pas ps1System$(PPUEXT) $(SYSTEMUNIT)$(PPUEXT)
        $(COMPILER) $(RTL_FPU_OPT) $<

ps1GPU$(PPUEXT) : bare-metal/ps1GPU.pas ps1System$(PPUEXT) $(SYSTEMUNIT)$(PPUEXT)
        $(COMPILER) $(RTL_FPU_OPT) $<

ps1GTE$(PPUEXT) : bare-metal/ps1GTE.pas ps1System$(PPUEXT) ps1GPU$(PPUEXT) $(SYSTEMUNIT)$(PPUEXT)
        $(COMPILER) $(RTL_FPU_OPT) $<

ps1SPU$(PPUEXT) : bare-metal/ps1SPU.pas ps1System$(PPUEXT) $(SYSTEMUNIT)$(PPUEXT)
        $(COMPILER) $(RTL_FPU_OPT) $<

si_prc$(PPUEXT) : si_prc.pp $(SYSTEMUNIT)$(PPUEXT)
        $(COMPILER) $(RTL_FPU_OPT) $<