#
# Makefile.fpc for SQL PQConnection
#

[package]
main=fcl

[target]
rsts=pqconnection
units=pqconnection

[require]
packages=postgres

[compiler]
options=-S2

[install]
fpcpackage=y

[default]
fpcdir=../../../..
