#
#   Makefile.fpc for FCL FPCUnit test framework.
#

[package]
main=fcl

[target]
units=testregistry testreport testdecorator ubmockobject xmlreporter \
      fpcunitreport latextestreport xmltestreport plaintestreport
exampledirs=exampletests

[compiler]
options=-S2h
targetdir=.

[install]
fpcpackage=y

[default]
fpcdir=../..
