#
#   Makefile.fpc for FCL FPCUnit test framework.
#

[package]
main=fcl

[target]
units=fpcunit testregistry testreport testutils testdecorator ubmockobject xmlreporter
exampledirs=exampletests

[compiler]
options=-S2h
targetdir=.

[install]
fpcpackage=y

[default]
fpcdir=../..
