.TH fprcp 1 "12 November 2004" "Free Pascal" "windres preprocessor"
.SH NAME 
fprcp \- Free Pascal windres preprocessor program.

.SH SYNOPSIS

.B fprcp -i file_name [-n] [-C] [-l PASCAL|C] [-p <include_path>] 

.SH DESCRIPTION

.B fprcp
reads a .rc file and preprocesses it, writing the result to standard output
as it goes along. It replaces defined constants with their values, so
.B windres
can process the resulting file and create a resource.

.SH USAGE

.B fprcp
needs as a minimum the 
.B \-i filename
option, which is the file to process.

.SH OPTIONS
fprcp has a small number of options to control its behaviour:

.TP
.B \-C 
Define the symbol 
.I symbol
before processing is started.
.TP
.B \-i file
Specify the input file name. This argument is mandatory.
.TP
.B \-l language
Set the programming language for include files. The
.I language
constant may be one of the following:
.RS
.TP
.I C
The C programming language.
.TP
.I PASCAL
the Pascal programming language
.RE
.TP
.B \-n 
Do not support nested comments. By default, pascal nested comments are
enabled.
.TP
.B \-p path
Set the include path. This may contain several files, separated by
semicolons.

.SH SEE ALSO
.IP 
.BR  ppc386 (1)
.BR  windres (1)

