.TH ppudump 1 "5 June 1999" "Free Pascal" "Free Pascal Unit dump utility"
.SH NAME
ppudump \- The FPC Pascal unit dump program.

.SH SYNOPSIS

\fIppudump\fP [-h] [-v[h|i|m|d|s|b|a]] ppu-file1 ppufile2 ...

.SH Description

.B ppudump
writes the contents of a Free Pascal unit file to standard output. 
It gives a listing of all definitions in the unit file. The format
of the listing can be controlled by the options.

.SH Usage

You can invoke ppudump with as arguments the names of the units that you
want to dump. You need not specify a extension, by default \fI.ppu\fP is
assumed. The output goes to standard output.

.SH Options

.B ppudump
has only two options:

.TP
.BI \-h
shows a short help screen.
.TP
.BI \-v xxx
Controls the level of verbosity. 
.I xxx 
is  any combination of the following letters:
.RS
.TP
.I a
Shows all information stored in the PPU file.
.TP
.I b
Shows the browser information in the PPU file (if present).
.TP
.I d
Shows the definitions in the PPU file.
.TP
.I h 
Shows the header information in the PPU file.
.TP
.I i
Shows only interface information, implementation information is
not shown.
.TP
.I m
Shows only implementation information, interface interface is not shown.
.TP
.I s
Shows the symbols stored in the PPU file.
.RE

.SH SEE ALSO
.IP 
.BR  ppc386 (1)
.BR  ppumove (1)
