.TH ppufiles 1 "9 June 1999" "Free Pascal" "Free Pascal unit object file lister"
.SH NAME
ppufiles \- The FPC Pascal unit object file lister.

.SH SYNOPSIS

\fBppufiles\fP [options] [file [file [file]]]

.SH Description

.B ppufiles
lists all the binary files that are needed to link a unit file. This
includes any object files or libraries that must be linked in through some
directive in the unit.

.SH Usage

You can invoke 
.B ppufiles
with as arguments the name of the units whose object files you wish to 
list. An extension must be given. This can be useful for creating a 
listing of all created object files and deleting them in a Makefile.

.SH Options

.B ppufiles
has several options, which are case insensitive:

.RS
.TP
.B \-a
This option tells 
.B ppufiles
to list all files.
.TP
.B \-h 
Help screen.
.TP
.B \-l
This option tells 
.B ppufiles
to list only shared libraries.
.TP
.B \-o 
This option tells 
.B ppufiles
to list only object files.
.TP
.B \-s 
This option tells 
.B ppufiles
to list only static libraries.
.RE
.SH ERRORS
In case the unit is in an older or unrecognised format, ppufiles will
complain about that.
.SH SEE ALSO
.IP 
.BR  ppc386 (1)
.BR  ppumove (1)
.BR  make (1)
