.TH ppmove 1 "9 June 1999" "Free Pascal" "Free Pascal unit mover"
.SH NAME
ppdep \- The FPC Pascal unit mover.

.SH SYNOPSIS

\fBppumove\fP [-sqbhw] [-o File] [-d path] [-e extension] files...

.SH Description

\fBppumove\fP collects one or several Free Pascal unit files and archives
them in a static or shared library.

.SH Usage

You can invoke \fBppumove\fP with as the only required argument the 
name of the unit from which you want to make an archive. Specifying 
multiple files is also possible, they will be put in the same archive.

.SH Options

\fBppumove\fP has several options, which are case sensitive:

.TP
.B \-b
This option tells \fBppumove\fP to write a shell script (a batch file on
DOS) that performs the needed calls to \fBar\fP and \fBld\fP. The script
will be called \fBpmove\fP, with an extension of \fB.sh\fP on Linux,
and \fB.bat\fP on DOS. You can then call this script manually afterwards.

.TP 
.BI \-d " path"
This option tells \fBppumove\fP where to generate the new unit files.
By default, this is the same directory as where the files are found. 
If you specify as the output extension the same extension as the units
you want to move, not specifying the destination directory may cause
problems.

.TP 
.BI \-e " ext"
This option sets the extension of the new unit files to \fBext\fP. By
default \fB.ppl\fP is used. However, you can specify \fB.ppu\fP as the
extension. If you do, be sure to use also the \fI\-d\fP switch, or you will
overwrite the old units. Note however, that the compiler will only look for
extensions \fB.ppu\fP and \fB.ppl\fP when looking for units.

.TP
.B -h
Shows a short help screen.

.TP 
.BI \-o " file"
This option allows you to specify the name of the library to be generated.
You \fBmust\fP use this option if you specify more than one unit on the
command-line. If you specified only one unit on the command-line, the generated library
will have the unit name, with \fBlib\fP prepended (on Linux).
You do not need to specify the \fBlib\fP part, this will be prepended
automatically if needed.

.TP
.B \-q
Tells \fBppumove\fP to operate quietly.

.TP
.B \-s
Tells \fBppumove\fP to generate a static library. By default, a shared
library is generated (except on DOS). 

.TP 
.B \-w
Tells \fBppumove\fP it should use the windows linker and archiver. Do not
use this option on Linux.

.SH SEE ALSO
.IP 
.BR  ppc386 (1)
.BR  ppudep (1)
.BR  ppudump (1)