.TH rstconv 1 "10 Jan 2000" "Free Pascal" "Free Pascal resource string converter tool"
.SH NAME
rstconv \- The Free Pascal resource string converter tool.

.SH SYNOPSIS

.B rstconv [options] -o outfile

.SH DESCRIPTION

.B rstconv
reads a resource string file (
.I .rst
) that was produced by the Free Pascal compiler and outputs a file that can 
be used by an internationalization tool
(currently only GNU
.I gettext
is supported) for internationalizing your application.

.SH USAGE

.B rstconv
has one required option: 
.BI \-o " outfile"
to specify the output file name. If no input file is specified, then
standard input is assumed.

.SH OPTIONS
.TP
.BI -f " format"
Specify the output file format. Currently only the following format is
supported:
.RS
.TP
.I po
emit a 
.I .po
file for use with GNU 
.I gettext
, which converts it to a .mo file, that can be read with the 
.I gettext
unit.
.RE
.TP
.B "-h (or --help)"
outputs a short help message.
.TP
.BI \-i " infile"
Specifies the input file name. If omitted, then standard input is assumed.
.TP
.BI \-o " outfile"
(Required) specify the output file name.
.SH SEE ALSO
.IP 
.BR  gettext (1)
.BR  ppc386 (1)
