#
#   Makefile.fpc for Free Component Library
#

[targets]
dirs=go32v2 linux win32 os2 test

[defaults]
defaultdir=$(OS_TARGET)

[install]
packagename=api
sourcesubdirs=0

[sections]
none=1
zipsourceinstall=1
