#
#   Makefile.fpc for Free Component Library
#

[targets]
dirs=go32v2 linux win32 os2 freebsd
exampledirs=test

[defaults]
defaultdir=$(OS_TARGET)

[install]
packagename=api
examplesubdir=api

[sections]
none=1
zipsourceinstall=1
zipexampleinstall=1
