#
# Makefile.fpc for Free Pascal testing utilities
#

[install]
fpcpackage=y

[default]
fpcdir=../..

[require]
# We depend on the installed compiler with it's fpc.cfg
nortl=y

[target]
programs=dotest fptime fail testfail digest concat $(DBDIGEST) $(MSDOSPROG)
programs_win32=prepup
programs_win64=prepup
programs_go32v2=prepup

[clean]
programs=dbdigest dbconfig

[prerules]

ifneq ($(findstring dosbox_wrapper,$(EMULATOR)),)
  MSDOSPROG=dosbox/dosbox_wrapper$(SRCEXEEXT)
else
  MSDOSPROG=
endif

[rules]
.NOTPARALLEL:

utils: all

dosbox/dosbox_wrapper$(SRCEXEEXT): dosbox/dosbox_wrapper.pas  
	$(COMPILER) -FE./dosbox $<

utilsdb:
        $(MAKE) utils DBDIGEST="dbdigest dbconfig"
